/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic.interfac.pesquisa;

import classes.clsaux;
import conexoes.conexao;
import grafic.interfac.CRUDCadPizza;
import grafic.interfac.FrmCadAdicional;
import grafic.interfac.FrmCadInventario;
import grafic.interfac.FrmCadTamPizza;
import grafic.interfac.LancamentoItemDocumento;
import grafic.interfac.OsItem;
import grafic.interfac.OsServico;
import grafic.interfac.cadProdutos;
import grafic.interfac.frmCadCondicional;
import grafic.interfac.frmCadOrcamentoItem;
import grafic.interfac.frmImpressaoEtiquetas;
import grafic.interfac.frmLancamentoItemNfe;
import grafic.interfac.frmSaidaLocacaoItem;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import relatorios.frmRelLocacaoProduto;
import relatorios.relVendasVendedor;
import relatorios.relVendasporProdutos;
import relatorios.relVendasporProdutosCusto;

/**
 *
 * @author Rodrigo
 */
public class localizaProduto extends javax.swing.JDialog {

    /**
     * Creates new form localizaProduto
     */
    public localizaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.entertable(tbProdPesq);
        this.pegaDuploClick();
    }
    public static String idchamado;
    public static String tipoBusca;
    String buscaautomatica="N";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtlocaliza = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnConfirm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProdPesq = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Produtos");

        jPanel1.setBackground(new java.awt.Color(219, 227, 227));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));

        jPanel3.setBackground(new java.awt.Color(219, 227, 227));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Localiza Produtos");

        txtlocaliza.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtlocaliza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlocalizaActionPerformed(evt);
            }
        });
        txtlocaliza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtlocalizaKeyReleased(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IncluirFinan.png"))); // NOI18N
        jButton1.setText("Novo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Refresh2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnConfirm.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        btnConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnConfirmFocusGained(evt);
            }
        });
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(txtlocaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConfirm)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtlocaliza, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tbProdPesq.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbProdPesq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Barras", "Descrição", "Preço Venda", "id Produto", "Referencia", "X"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProdPesq.setRowHeight(24);
        tbProdPesq.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbProdPesq);
        if (tbProdPesq.getColumnModel().getColumnCount() > 0) {
            tbProdPesq.getColumnModel().getColumn(0).setPreferredWidth(100);
            tbProdPesq.getColumnModel().getColumn(1).setPreferredWidth(180);
            tbProdPesq.getColumnModel().getColumn(2).setPreferredWidth(10);
            tbProdPesq.getColumnModel().getColumn(3).setPreferredWidth(5);
            tbProdPesq.getColumnModel().getColumn(4).setPreferredWidth(120);
            tbProdPesq.getColumnModel().getColumn(5).setResizable(false);
            tbProdPesq.getColumnModel().getColumn(5).setPreferredWidth(30);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     cadProdutos dialog = new cadProdutos(new javax.swing.JFrame(), true);
     dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.buscaProdutos(txtlocaliza.getText());
        tbProdPesq.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        this.acaoBtnConfirma();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void txtlocalizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlocalizaActionPerformed
        this.buscaProdutos(txtlocaliza.getText());
        tbProdPesq.requestFocus();
    }//GEN-LAST:event_txtlocalizaActionPerformed

    private void btnConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnConfirmFocusGained
       this.acaoBtnConfirma();
    }//GEN-LAST:event_btnConfirmFocusGained

    private void txtlocalizaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlocalizaKeyReleased
        if(buscaautomatica.equals("S")){
            buscaProdutos(txtlocaliza.getText().trim());
        }
    }//GEN-LAST:event_txtlocalizaKeyReleased
    public void buscaProdutos(String campopesquisado){
         
        try {
            String sql="select tb.codigo_barras,\n" +
                    "       tp.nomecurto,\n" +
                    "       tc.preco_venda,\n" +
                    "       tp.id,tb.referencia \n" +
                    " from tprodutos tp\n" +
                    " join tbarras tb on tp.id=tb.id_produto\n" +
                    " join tprecos tc on tp.id=tc.id\n" +
                    " where (tp.nomecurto like '%"+campopesquisado+"%'  or tb.codigo_barras like '%"+campopesquisado+"%' or tb.referencia like '%"+campopesquisado+"%') and tp.excluido='N' and tipo_produto=0;";
            if (tipoBusca=="servicos"){
                sql="select tb.codigo_barras,\n" +
                    "       tp.nomecurto,\n" +
                    "       tc.preco_venda,\n" +
                    "       tp.id,tb.referencia \n" +
                    " from tprodutos tp\n" +
                    " join tbarras tb on tp.id=tb.id_produto\n" +
                    " join tprecos tc on tp.id=tc.id\n" +
                    " where tp.nomecurto like '%"+campopesquisado+"%' and tp.excluido='N' and tipo_produto=9;";
            }else if(tipoBusca=="locacao"){
                 sql="select tb.codigo_barras,\n" +
                    "       tp.nomecurto,\n" +
                    "       tc.preco_venda,\n" +
                    "       tp.id,tb.referencia \n" +
                    " from tprodutos tp\n" +
                    " join tbarras tb on tp.id=tb.id_produto\n" +
                    " join tprecos tc on tp.id=tc.id\n" +
                    " where (tp.nomecurto like '%"+campopesquisado+"%'  or tb.codigo_barras like '%"+campopesquisado+"%') and tp.excluido='N' and tipo_produto=0 and tp.locacao='S'";
            }else if(tipoBusca=="todos"){
                sql="select tb.codigo_barras,\n" +
                    "       tp.nomecurto,\n" +
                    "       tc.preco_venda,\n" +
                    "       tp.id,tb.referencia \n" +
                    " from tprodutos tp\n" +
                    " join tbarras tb on tp.id=tb.id_produto\n" +
                    " join tprecos tc on tp.id=tc.id\n" +
                    " where (tp.nomecurto like '%"+campopesquisado+"%'  or tb.codigo_barras like '%"+campopesquisado+"%'  or tb.referencia like '%"+campopesquisado+"%') and tp.excluido='N'";
            }else if(tipoBusca=="grupos"){
                sql="select tg.id_grupo, tg.nome, tg.comissao,tg.id_grupo from tgrupos tg";
            }
            PreparedStatement ps = conexao.getPreparedStatement(sql);
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tb = (DefaultTableModel) tbProdPesq.getModel();
            tb.setNumRows(0);
            while (rs.next()){
                tb.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    clsaux.formato(rs.getDouble(3)),
                    rs.getString(4),
                    rs.getString(5),
                    new Boolean(false)
                });
            }
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(localizaProduto.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao buscar Produtos \n" +ex.getMessage());
        }
         
     
     }
    public void acaoBtnConfirma(){
         String codBarra= tbProdPesq.getValueAt(tbProdPesq.getSelectedRow(), 0).toString();
         String idproduto=tbProdPesq.getValueAt(tbProdPesq.getSelectedRow(), 3).toString();
         String descricao=tbProdPesq.getValueAt(tbProdPesq.getSelectedRow(), 1).toString();
         if (idchamado.equals("1")){
             LancamentoItemDocumento.txtCodBarras.setText(codBarra);
             LancamentoItemDocumento.txtCodBarras.requestFocus();
         } else if(idchamado=="2"){
             OsItem.txtCodProdOs.setText(codBarra);
             OsItem.txtCodProdOs.requestFocus();
         } else if (idchamado=="3"){
             OsServico.txtCodProdOs.setText(codBarra);
             OsServico.txtCodProdOs.requestFocus();
         } else if(idchamado=="4"){
             frmCadCondicional.txtCodBarra.setText(codBarra);
             frmCadCondicional.txtCodBarra.requestFocus();
         }else if(idchamado=="5"){
             frmLancamentoItemNfe.txtCodBarras.setText(codBarra);
             frmLancamentoItemNfe.txtCodBarras.requestFocus();
         }else if(idchamado=="6"){
             frmCadOrcamentoItem.txtBarra.setText(codBarra);
             frmCadOrcamentoItem.txtBarra.requestFocus();
         }else if(idchamado=="7"){
             frmImpressaoEtiquetas.txtCampoPesquisado.setText(codBarra);
             frmImpressaoEtiquetas.txtCampoPesquisado.requestFocus();
         }else if(idchamado=="9"){
             cadProdutos.txtCodigo.setText(codBarra);
             cadProdutos.txtCodigo.requestFocus();
         }else if(idchamado=="10"){
             frmSaidaLocacaoItem.txtCodProdOs.setText(codBarra);
             frmSaidaLocacaoItem.txtCodProdOs.requestFocus();
             frmSaidaLocacaoItem.idproduto=idproduto;
         }else if(idchamado=="11"){
             frmRelLocacaoProduto.txtProduto.setText(codBarra);
             frmRelLocacaoProduto.lbProduto.setText(descricao);
         }else if(idchamado=="12"){
             FrmCadAdicional.txtCodProdBase.setText(codBarra);
             FrmCadAdicional.txtCodProdBase.requestFocus();
         }else if(idchamado=="13"){
             FrmCadTamPizza.txtCodProdBase.setText(codBarra);
             FrmCadTamPizza.txtCodProdBase.requestFocus();
         }else if(idchamado=="14"){
             buscaTodosSelecionados();
         }else if(idchamado=="15"){
             CRUDCadPizza.txtCodInserir.setText(codBarra);
             CRUDCadPizza.txtCodInserir.requestFocus();
         }else if(idchamado=="16"){
             buscaTodosSelecionados1();
         }else if(idchamado=="17"){
             FrmCadInventario.txtcodigo.setText(codBarra);
         }else if(idchamado=="18"){
             buscaTodosSelecionados2();
         }
         localizaProduto.tipoBusca="normal";
         this.dispose();
     }
    public void recebeDadosAuto(String inf){
        buscaautomatica="S";
        txtlocaliza.setText(inf+" ");
        buscaProdutos(inf);
       // txtlocaliza.requestFocusInWindow();
        
            txtlocaliza.setSelectionStart(txtlocaliza.getText().length()-1);
            txtlocaliza.setSelectionEnd(txtlocaliza.getText().length()-1);
          
        
    }
    
    public void buscaTodosSelecionados(){
        int tamanho=tbProdPesq.getRowCount();
        relVendasporProdutos.ProdutosSelecionados.clear();
        for(int i=0; i<tamanho; i++){
            if((Boolean) tbProdPesq.getValueAt(i, 4)==true){
                relVendasporProdutos.ProdutosSelecionados.add(tbProdPesq.getValueAt(i, 0).toString());
            }
        }
        
        
         relVendasporProdutos.txtProduto.requestFocus();
    }
    public void buscaTodosSelecionados1(){
        int tamanho=tbProdPesq.getRowCount();
         relVendasporProdutosCusto.ProdutosSelecionados.clear();
        for(int i=0; i<tamanho; i++){
            if((Boolean) tbProdPesq.getValueAt(i, 5)==true){
                relVendasporProdutosCusto.ProdutosSelecionados.add(tbProdPesq.getValueAt(i, 0).toString());
            }
        }
         relVendasporProdutosCusto.txtProduto.requestFocus();
    }
     public void buscaTodosSelecionados2(){
        int tamanho=tbProdPesq.getRowCount();
         relVendasVendedor.gruposSelecionados.clear();
        for(int i=0; i<tamanho; i++){
            if((Boolean) tbProdPesq.getValueAt(i, 5)==true){
                relVendasVendedor.gruposSelecionados.add(tbProdPesq.getValueAt(i, 0).toString());
            }
        }
         relVendasVendedor.txtGrupos.requestFocus();
    }
    private void entertable(final JTable tbl){
        tbl.getInputMap(tbl.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke("ENTER"), "enterAction");
        tbl.getActionMap().put("enterAction", new AbstractAction(){
            public void actionPerformed(ActionEvent e){
               btnConfirm.requestFocus();
            }
        });
    
    }
    public void pegaDuploClick(){
        tbProdPesq.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e ){
                if (e.getClickCount()==2){
                   btnConfirm.requestFocus();
                } 
            }
          
        }); 
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(localizaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(localizaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(localizaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(localizaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                localizaProduto dialog = new localizaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProdPesq;
    private javax.swing.JTextField txtlocaliza;
    // End of variables declaration//GEN-END:variables
}
