/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic.interfac;

import DAO.ContasReceberDAO;
import DAO.permissaoUsuarioDAO;
import model.CadContasRecPagar;
import classes.clsaux;
import titulos.FormRecibo;
import titulos.FormContasPagarReceber;
import conexoes.conexao;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import titulos.FormBaixaTitulos;
import Boletos.GeraBoletos;

/**
 *
 * @author Rodrigo
 */
public class CRUDTitulo extends javax.swing.JDialog {

    /**
     * Creates new form CRUDTitulo
     */
    public CRUDTitulo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.preencheData();
        this.pegaDuploClick();
        this.validaCamposUsuario();
    }
    
    public static String tipo=null;
    Double selecionado;
    List<CadContasRecPagar> con = new ArrayList<>();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbTitulos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbtipo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtValortotal = new javax.swing.JTextField();
        lbTotalreg = new javax.swing.JLabel();
        lbTotalregvalor = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbValorSelecionado = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnBaixarTitulo = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        JcbFiltrarPor = new javax.swing.JComboBox<>();
        JcbEstadoTitulo = new javax.swing.JComboBox<>();
        JtxtPesquisa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnPesq = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JftfDatInicio = new javax.swing.JFormattedTextField();
        JftfDatFim = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        cbTipoTitulo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(219, 227, 227));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);

        TbTitulos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TbTitulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pagar", "Id", "Documento", "Parceiro", "Valor", "Data Lançamento", "Data Vencimento", "Data pagamento", "Valor Pago", "Estado", "Tipo Titulo", "Id Movimento", "Id Parceiro", "Parcela", "Observação", "Tipo Financeiro", "SubTipo Financeiro", "Juros", "Multa", "SubTotal", "Boleto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbTitulos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TbTitulos.setRowHeight(20);
        TbTitulos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbTitulos);
        if (TbTitulos.getColumnModel().getColumnCount() > 0) {
            TbTitulos.getColumnModel().getColumn(0).setResizable(false);
            TbTitulos.getColumnModel().getColumn(1).setResizable(false);
            TbTitulos.getColumnModel().getColumn(2).setResizable(false);
            TbTitulos.getColumnModel().getColumn(2).setPreferredWidth(120);
            TbTitulos.getColumnModel().getColumn(3).setResizable(false);
            TbTitulos.getColumnModel().getColumn(3).setPreferredWidth(300);
            TbTitulos.getColumnModel().getColumn(4).setResizable(false);
            TbTitulos.getColumnModel().getColumn(5).setResizable(false);
            TbTitulos.getColumnModel().getColumn(6).setResizable(false);
            TbTitulos.getColumnModel().getColumn(7).setResizable(false);
            TbTitulos.getColumnModel().getColumn(8).setResizable(false);
            TbTitulos.getColumnModel().getColumn(9).setResizable(false);
            TbTitulos.getColumnModel().getColumn(9).setPreferredWidth(150);
            TbTitulos.getColumnModel().getColumn(10).setResizable(false);
            TbTitulos.getColumnModel().getColumn(11).setResizable(false);
            TbTitulos.getColumnModel().getColumn(12).setResizable(false);
            TbTitulos.getColumnModel().getColumn(13).setResizable(false);
            TbTitulos.getColumnModel().getColumn(13).setPreferredWidth(90);
            TbTitulos.getColumnModel().getColumn(14).setResizable(false);
            TbTitulos.getColumnModel().getColumn(14).setPreferredWidth(400);
            TbTitulos.getColumnModel().getColumn(15).setResizable(false);
            TbTitulos.getColumnModel().getColumn(15).setPreferredWidth(150);
            TbTitulos.getColumnModel().getColumn(16).setResizable(false);
            TbTitulos.getColumnModel().getColumn(16).setPreferredWidth(200);
            TbTitulos.getColumnModel().getColumn(17).setResizable(false);
            TbTitulos.getColumnModel().getColumn(18).setResizable(false);
            TbTitulos.getColumnModel().getColumn(19).setResizable(false);
            TbTitulos.getColumnModel().getColumn(20).setResizable(false);
            TbTitulos.getColumnModel().getColumn(20).setPreferredWidth(80);
        }

        jPanel1.setBackground(new java.awt.Color(219, 227, 227));

        lbtipo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbtipo.setForeground(new java.awt.Color(0, 153, 51));
        lbtipo.setText("Títulos Pendentes");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fecharprincipal.png"))); // NOI18N

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IncluirFinan.png"))); // NOI18N
        jButton5.setText("Incluir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mudar2.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/DelFinan.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close2.png"))); // NOI18N
        jButton8.setText("Fechar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("- Financeiro / Títulos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(btnAlterar)
                        .addComponent(btnExcluir)
                        .addComponent(jButton8))
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbtipo)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel8))))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Valor Exibido:");

        txtValortotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtValortotal.setText("0,00");
        txtValortotal.setEnabled(false);

        lbTotalreg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTotalreg.setText("Total Registros:");

        lbTotalregvalor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Valor Selecionado:");

        lbValorSelecionado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbValorSelecionado.setText("0,00");
        lbValorSelecionado.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbTotalreg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalregvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbValorSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbValorSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtValortotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTotalreg, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTotalregvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );

        jPanel5.setBackground(new java.awt.Color(145, 182, 182));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnBaixarTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBaixarTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Credito.png"))); // NOI18N
        btnBaixarTitulo.setText("       Baixar Titulos");
        btnBaixarTitulo.setActionCommand("Baixar Títulos");
        btnBaixarTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaixarTituloActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        jButton10.setText("      Marcar Todos");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Printer.png"))); // NOI18N
        jButton11.setText("   Imprimir Recibo");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11jButton4ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Documento.png"))); // NOI18N
        jButton12.setText("   Itens Referentes");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancela.png"))); // NOI18N
        jButton13.setText("      Anular Titulos");

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        jButton14.setText(" Exportar Excel");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        jButton15.setText("Imprimir Boletos");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBaixarTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBaixarTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBaixarTitulo, jButton13});

        jPanel2.setBackground(new java.awt.Color(219, 227, 227));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));
        jPanel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        JcbFiltrarPor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JcbFiltrarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emissão", "Vencimento", "Pagamento", "Todos" }));
        JcbFiltrarPor.setSelectedIndex(1);
        JcbFiltrarPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbFiltrarPorActionPerformed(evt);
            }
        });

        JcbEstadoTitulo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JcbEstadoTitulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Vencido", "Quitado", "Anulado", "Todos" }));

        JtxtPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JtxtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtxtPesquisaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Filtrar Por:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Estado do Título:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nome, Código, Cpf");

        btnPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar.png"))); // NOI18N
        btnPesq.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnPesqFocusGained(evt);
            }
        });
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Data Inicío:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Data Término :");

        try {
            JftfDatInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JftfDatInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JftfDatInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JftfDatInicioActionPerformed(evt);
            }
        });

        try {
            JftfDatFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        JftfDatFim.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tipo Titulo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(JftfDatInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JftfDatFim, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JcbEstadoTitulo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbTipoTitulo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JcbFiltrarPor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 127, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(0, 79, Short.MAX_VALUE))
                            .addComponent(JtxtPesquisa))
                        .addGap(18, 18, 18)
                        .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JcbFiltrarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addGap(5, 5, 5)
                .addComponent(cbTipoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(8, 8, 8)
                .addComponent(JcbEstadoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(JftfDatInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JftfDatFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JtxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1294, 705));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        FormContasPagarReceber dialog = new FormContasPagarReceber(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton11jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11jButton4ActionPerformed
        FormRecibo dialog = new FormRecibo(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButton11jButton4ActionPerformed

    private void JftfDatInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JftfDatInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JftfDatInicioActionPerformed

    private void JcbFiltrarPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbFiltrarPorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbFiltrarPorActionPerformed

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        this.acaoBtnBuscar();
    }//GEN-LAST:event_btnPesqActionPerformed

    private void btnBaixarTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaixarTituloActionPerformed
        this.acaoTipoForm();
        this.acaoBtnBaixaTitulos();
    }//GEN-LAST:event_btnBaixarTituloActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        this.acaoBtnAlterar();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Object[] opcoes = {"Sim", "Não"};
        int opc = JOptionPane.showOptionDialog(null, "Deseja realmente cancelar o Titulo?", "Cancelamento De Titulos...", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,null, opcoes,opcoes[1]);
        if(opc==0){
            this.acaoBtnExcluir();           
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       this.acaoBtnItensReferente();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.acaoBtnMarcarTodos();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void JtxtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtxtPesquisaActionPerformed
        this.acaoBtnBuscar();
    }//GEN-LAST:event_JtxtPesquisaActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            this.exportarArquivoExcel();
        } catch (IOException ex) {
            Logger.getLogger(CRUDTitulo.class.getName()).log(Level.SEVERE, null, ex);
            Logs.gravarLog.main(ex.getMessage());
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void btnPesqFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPesqFocusGained
       this.acaoBtnBuscar();
    }//GEN-LAST:event_btnPesqFocusGained

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        try {
            GeraBoletos gera= new GeraBoletos();
            String boleto="";
            boleto=clsaux.trataCampoNulo(TbTitulos.getValueAt(TbTitulos.getSelectedRow(), 20));
            if(clsaux.verificaNulo(boleto)==false && boleto!="0"&&tipo=="E"){
                gera.geraBoleto(TbTitulos.getValueAt(TbTitulos.getSelectedRow(), 1).toString());
            }else{
                JOptionPane.showMessageDialog(null, "Boleto Nao Pode Ser Gerado!!!");
            }
        } catch (IOException ex) {
            Logger.getLogger(CRUDTitulo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton15ActionPerformed
    
    public void validaCamposUsuario(){
        if(permissaoUsuarioDAO.verificaPermissaoUsuConectado("107"));else {
            btnBaixarTitulo.setEnabled(false);
        }
        if(permissaoUsuarioDAO.verificaPermissaoUsuConectado("108"));else {
            btnAlterar.setEnabled(false);
        }
        if(permissaoUsuarioDAO.verificaPermissaoUsuConectado("109"));else {
            btnExcluir.setEnabled(false);
        }
    
    
    
    }
    
    public void buscaTitulosOutraOrigem(String id){
        try {
            String sql="select tc.id,\n" +
                    "            tc.id_movimento,\n" +
                    "            tp.razao_social,\n" +
                    "            tc.data_emissao,\n" +
                    "            tc.data_vencimento,\n" +
                    "            tc.data_pagamento,\n" +
                    "            tc.valor,\n" +
                    "            tc.valor_pago,\n" +
                    "            teo.descricao,\n" +
                    "            tip.descricao,"
                    + "tp.idparceiro,tc.parcela,tc.observacao,tc.id_tipo_financeiro||'- '||tf.descricao_movimento,tc.id_subtipo_financeiro||'- '||tf1.descricao_movimento, tc.numero_documento"
                    + " ,tc.juros,tc.multa,tc.valor_total,nosso_numero,tc.pagar_receber\n" +
                    "            from tcontas_a_receber_pagar tc\n" +
                    "            join tparceiros tp on tc.id_parceiro=tp.idparceiro\n" +
                    "            left join ttipo_movimento tf on tc.id_tipo_financeiro=tf.id_tipo\n" +
                    "            left join ttipo_movimento tf1 on tc.id_subtipo_financeiro=tf1.id_tipo\n" +
                    "            join ttiptitulos tip on tc.tipo_titulo=tip.id\n" +
                    "            join testado_operacoes teo on tc.estado=teo.id "
                    + " where tc.id=?";
            PreparedStatement pscon=conexao.getPreparedStatement(sql);
            pscon.setString(1, id );
            ResultSet rscon=pscon.executeQuery();
             if(rscon.next()){
                CadContasRecPagar novo= new CadContasRecPagar();
                novo.setIdtitulo(rscon.getString(1));
                novo.setNumero(rscon.getString(16));
                novo.setRazaoparceiro(rscon.getString(3));
                novo.setValor(clsaux.formato(rscon.getDouble(7)));
                novo.setEmisao(rscon.getDate(4));
                novo.setVencimento(rscon.getDate(5));
                novo.setPagamento(rscon.getDate(6));
                novo.setValorpago(rscon.getString(8));
                novo.setEstadotitulo(rscon.getString(9));
                novo.setTipo_titulo(rscon.getString(10));
                novo.setIdmovto(rscon.getString(2));
                novo.setParceiro(rscon.getString(11));
                novo.setParcela(rscon.getString(12));
                novo.setObservacao(rscon.getString(13));
                novo.setTipofinanceiro(rscon.getString(14));
                novo.setSubtipofinanceiro(rscon.getString(15));
                novo.setJuros(rscon.getString(17));
                novo.setMulta(rscon.getString(18));
                novo.setValortotal(rscon.getString(19));
                novo.setNumboleto(rscon.getString(20));
                novo.setTipo(rscon.getString(21));
                if(novo.getTipo().equals("1")){
                    tipo="Cadastro de Contas a Pagar";
                    this.setTitle("Cadastro de Contas a Pagar"); 
                    lbtipo.setText(tipo);
                }else{
                     tipo="Cadastro de Contas a Receber";
                     this.setTitle("Cadastro de Contas a Receber"); 
                     lbtipo.setText(tipo);
                }
                con.add(novo);
            }
            rscon.close();
            pscon.close();
            this.preencherTabela();
        } catch (SQLException ex) {
            Logger.getLogger(CRUDTitulo.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        
    }
    public void buscaTitulos(String estado,String filtro,String dataini,String datafim,String campo){
            boolean erroexibido=false; 
            String sql=null,direcao=null;
            String tipotitulo=clsaux.retornaId(cbTipoTitulo.getSelectedItem());
            String comtipo="";
            if(tipotitulo.equals("0")){
                
            }else{
                comtipo="and tc.tipo_titulo='"+tipotitulo+"'";
            }
             if (tipo=="E"){
                 direcao="2";
             }if (tipo=="S"){
                 direcao="1";
             }
             if(filtro.equals("Emissão")){
             sql="select tc.id,\n" +
"            tc.id_movimento,\n" +
"            tp.razao_social,\n" +
"            tc.data_emissao,\n" +
"            tc.data_vencimento,\n" +
"            tc.data_pagamento,\n" +
"            tc.valor,\n" +
"            tc.valor_pago,\n" +
"            teo.descricao,\n" +
"            tip.descricao,"
          + "tp.idparceiro,tc.parcela,tc.observacao,tc.id_tipo_financeiro||'- '||tf.descricao_movimento,tc.id_subtipo_financeiro||'- '||tf1.descricao_movimento, tc.numero_documento"
                     + " ,tc.juros,tc.multa,tc.valor_total,nosso_numero,id_vendedor,tc.numero_parcelas \n" +
"            from tcontas_a_receber_pagar tc\n" +
"            join tparceiros tp on tc.id_parceiro=tp.idparceiro\n" +
"            left join ttipo_movimento tf on tc.id_tipo_financeiro=tf.id_tipo\n" +
"            left join ttipo_movimento tf1 on tc.id_subtipo_financeiro=tf1.id_tipo\n" +
"            join ttiptitulos tip on tc.tipo_titulo=tip.id\n" +
"            join testado_operacoes teo on tc.estado=teo.id "
         + " where tc.data_emissao between '"+dataini+"'and'"+datafim+"' and tp.razao_social like '%"+campo+"%'"
                     + " and (tc.estado="+estado+") and tc.pagar_receber='"+direcao+"'"+comtipo;
             }
             if(filtro.equals("Pagamento")){
             sql="select tc.id,\n" +
"            tc.id_movimento,\n" +
"            tp.razao_social,\n" +
"            tc.data_emissao,\n" +
"            tc.data_vencimento,\n" +
"            tc.data_pagamento,\n" +
"            tc.valor,\n" +
"            tc.valor_pago,\n" +
"            teo.descricao,\n" +
"            tip.descricao,"
          + "tp.idparceiro,tc.parcela,tc.observacao,tc.id_tipo_financeiro||'- '||tf.descricao_movimento,tc.id_subtipo_financeiro||'- '||tf1.descricao_movimento, tc.numero_documento"
                     + " ,tc.juros,tc.multa,tc.valor_total,nosso_numero,id_vendedor,tc.numero_parcelas \n" +
"            from tcontas_a_receber_pagar tc\n" +
"            join tparceiros tp on tc.id_parceiro=tp.idparceiro\n" +
"            left join ttipo_movimento tf on tc.id_tipo_financeiro=tf.id_tipo\n" +
"            left join ttipo_movimento tf1 on tc.id_subtipo_financeiro=tf1.id_tipo\n" +
"            join ttiptitulos tip on tc.tipo_titulo=tip.id\n" +
"            join testado_operacoes teo on tc.estado=teo.id "
         + " where tc.data_pagamento between '"+dataini+"'and'"+datafim+"' and tp.razao_social like '%"+campo+"%'"
                     + " and (tc.estado="+estado+") and tc.pagar_receber='"+direcao+"' "+comtipo;
             }
             if(filtro.equals("Vencimento")){
             sql="select tc.id,\n" +
"            tc.id_movimento,\n" +
"            tp.razao_social,\n" +
"            tc.data_emissao,\n" +
"            tc.data_vencimento,\n" +
"            tc.data_pagamento,\n" +
"            tc.valor,\n" +
"            tc.valor_pago,\n" +
"            teo.descricao,\n" +
"            tip.descricao,"
          + "tp.idparceiro,tc.parcela,tc.observacao,tc.id_tipo_financeiro||'- '||tf.descricao_movimento,tc.id_subtipo_financeiro||'- '||tf1.descricao_movimento, tc.numero_documento "
                     + " ,tc.juros,tc.multa,tc.valor_total,nosso_numero,id_vendedor,tc.numero_parcelas \n" +
"            from tcontas_a_receber_pagar tc\n" +
"            join tparceiros tp on tc.id_parceiro=tp.idparceiro\n" +
"            left join ttipo_movimento tf on tc.id_tipo_financeiro=tf.id_tipo\n" +
"            left join ttipo_movimento tf1 on tc.id_subtipo_financeiro=tf1.id_tipo\n"
          + " join ttiptitulos tip on tc.tipo_titulo=tip.id  \n" +
"             join testado_operacoes teo on tc.estado=teo.id "
         + " where tc.data_vencimento between '"+dataini+"'and'"+datafim+"'and tp.razao_social like '%"+campo+"%'"
         + " and( tc.estado="+estado+" )and tc.pagar_receber='"+direcao+"' " +comtipo;
                     
             }
             if(filtro.equals("Todos")){
             sql="select tc.id,\n" +
"            tc.id_movimento,\n" +
"            tp.razao_social,\n" +
"            tc.data_emissao,\n" +
"            tc.data_vencimento,\n" +
"            tc.data_pagamento,\n" +
"            tc.valor,\n" +
"            tc.valor_pago,\n" +
"            teo.descricao,\n" +
"            tip.descricao,tp.idparceiro,tc.parcela,tc.observacao,tc.id_tipo_financeiro||'- '||tf.descricao_movimento,tc.id_subtipo_financeiro||'- '||tf1.descricao_movimento, tc.numero_documento  ,tc.juros,tc.multa,tc.valor_total,nosso_numero,id_vendedor,tc.numero_parcelas\n" +
"            from tcontas_a_receber_pagar tc\n" +
"            join tparceiros tp on tc.id_parceiro=tp.idparceiro\n" +
"            left join ttipo_movimento tf on tc.id_tipo_financeiro=tf.id_tipo\n" +
"            left join ttipo_movimento tf1 on tc.id_subtipo_financeiro=tf1.id_tipo \n" +
"            join ttiptitulos tip on tc.tipo_titulo=tip.id\n" +
"            join testado_operacoes teo on tc.estado=teo.id \n"
          + "where (tc.estado="+estado+" )and tc.pagar_receber='"+direcao+"' "+comtipo;
             }
             if (estado.equals("0")){
                 sql="select tc.id,\n" +
"            tc.id_movimento,\n" +
"            tp.razao_social,\n" +
"            tc.data_emissao,\n" +
"            tc.data_vencimento,\n" +
"            tc.data_pagamento,\n" +
"            tc.valor,\n" +
"            tc.valor_pago,\n" +
"            teo.descricao,\n" +
"            tip.descricao,tp.idparceiro,tc.parcela,tc.observacao,tc.id_tipo_financeiro||'- '||tf.descricao_movimento,tc.id_subtipo_financeiro||'- '||tf1.descricao_movimento, tc.numero_documento  ,tc.juros,tc.multa,tc.valor_total,nosso_numero,id_vendedor,tc.numero_parcelas\n" +
"            from tcontas_a_receber_pagar tc\n" +
"            join tparceiros tp on tc.id_parceiro=tp.idparceiro\n" +
"            left join ttipo_movimento tf on tc.id_tipo_financeiro=tf.id_tipo\n" +
"            left join ttipo_movimento tf1 on tc.id_subtipo_financeiro=tf1.id_tipo \n" +
"            join ttiptitulos tip on tc.tipo_titulo=tip.id\n" +
"            join testado_operacoes teo on tc.estado=teo.id \n"
         + " where tc.data_emissao between '"+dataini+"'and'"+datafim+"' and tp.razao_social like '%"+campo+"%'"
                     + "and tc.pagar_receber='"+direcao+"' "+comtipo;
             }
            try{
                
                System.out.println(sql);
            PreparedStatement pscon=conexao.getPreparedStatement(sql);
            ResultSet rscon=pscon.executeQuery();
            
            Double total=0.00;
            
            int contador=0;
            
            while(rscon.next()&& !erroexibido){
                CadContasRecPagar novo= new CadContasRecPagar();
                novo.setIdtitulo(rscon.getString(1));
                novo.setNumero(rscon.getString(16));
                novo.setRazaoparceiro(rscon.getString(3));
                novo.setValor(clsaux.formato(rscon.getDouble(7)));
                novo.setEmisao(rscon.getDate(4));
                novo.setVencimento(rscon.getDate(5));
                novo.setPagamento(rscon.getDate(6));
                novo.setValorpago(rscon.getString(8));
                novo.setEstadotitulo(rscon.getString(9));
                novo.setTipo_titulo(rscon.getString(10));
                novo.setIdmovto(rscon.getString(2));
                novo.setParceiro(rscon.getString(11));
                novo.setParcela(rscon.getString(12));
                novo.setObservacao(rscon.getString(13));
                novo.setTipofinanceiro(rscon.getString(14));
                novo.setSubtipofinanceiro(rscon.getString(15));
                novo.setJuros(rscon.getString(17));
                novo.setMulta(rscon.getString(18));
                novo.setValortotal(rscon.getString(19));
                novo.setNumboleto(rscon.getString(20));
                novo.setVendedor(rscon.getString(21));
                novo.setQntParcelas(rscon.getString(22));
                con.add(novo);
                contador++;
                total=total+rscon.getDouble(7);
            }
            lbTotalregvalor.setText(String.valueOf(contador));
            txtValortotal.setText(clsaux.formato(total));
            rscon.close();
            pscon.close();
            this.preencherTabela();
        } catch (SQLException ex) {
           
            if(!erroexibido){
                erroexibido=true;
                if(ex.getErrorCode()==335544334){
                    Logs.gravarLog.gravaSemMensagem(ex.getMessage());
                    //JOptionPane.showMessageDialog(null,"Atenção, Data Invalida!!!");
                    
                }else{
                    Logs.gravarLog.main(ex.getMessage());
                }
              
                Logger.getLogger(CRUDTitulo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
         }
    }
    
    public void preencherTabela(){
            DefaultTableModel tb=(DefaultTableModel) TbTitulos.getModel();
            TbTitulos.setRowSorter(new TableRowSorter(tb));
            tb.setNumRows(0);
            for(CadContasRecPagar novo: con){
                tb.addRow(new Object[]{
                    new Boolean(false),
                    novo.getIdtitulo(),
                    novo.getNumero(),
                    novo.getRazaoparceiro(),
                    novo.getValortotal(),
                    clsaux.convertDataExib(novo.getEmisao()),
                    clsaux.convertDataExib(novo.getVencimento()),
                    clsaux.convertDataExib(novo.getPagamento()),
                    novo.getValorpago(),
                    novo.getEstadotitulo(),
                    novo.getTipo_titulo(),
                    novo.getIdmovto(),
                    novo.getParceiro(),
                    novo.getParcela()+"-"+novo.getQntParcelas(),
                    novo.getObservacao(),
                    novo.getTipofinanceiro(),
                    novo.getSubtipofinanceiro(),
                    novo.getJuros(),
                    novo.getMulta(),
                    novo.getValor(),
                    novo.getNumboleto()
                });
            }
    }
    public void preencheData(){
        JftfDatInicio.setText(clsaux.calcularData(-Integer.parseInt(clsaux.retornaDia())+1, clsaux.retornaData(clsaux.preencheData())));
        JftfDatFim.setText(clsaux.retornaUltimoDiaMes());
        lbtipo.setText(tipo);
        DefaultComboBoxModel cbtiptitulo= new DefaultComboBoxModel(ContasReceberDAO.tipoTitulo().toArray());
        cbTipoTitulo.setModel(cbtiptitulo);
        clsaux.carregaComboBox(cbTipoTitulo, "0");
    }
    public void acaoBtnBaixaTitulos(){
           DefaultTableModel tb = (DefaultTableModel)TbTitulos.getModel();
           String parceiro=null;
           int valorcoluna=0;
           int cont= tb.getRowCount();
           List<CadContasRecPagar> contas= new ArrayList<>();
           for (int i=0; i<cont; i++){
               if((Boolean)tb.getValueAt(i, 0)==true){
                   if(TbTitulos.getValueAt(i, 9).toString().equals("Pendente")||TbTitulos.getValueAt(i, 9).toString().equals("Restante")){
                        valorcoluna=valorcoluna+1;
                        parceiro=tb.getValueAt(i, 12).toString();
                        contas.add(con.get(i));
                   }
               }
           }
           if (valorcoluna>0){
                FormBaixaTitulos.idparceir=parceiro;
                FormBaixaTitulos.lista=contas;
                FormBaixaTitulos dialog = new FormBaixaTitulos(new javax.swing.JFrame(), true);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
           } else {
                JOptionPane.showMessageDialog(null, "Nenhum Titulo Selecionado :(");
           }
    }
    public void validaCelulaMarcada(){
        selecionado=0.00;
             for (int i=0; i<TbTitulos.getRowCount(); i++){
               if((Boolean)TbTitulos.getValueAt(i, 0)==true){
                   if(TbTitulos.getValueAt(i, 9).toString().equals("Pendente")||TbTitulos.getValueAt(i, 9).toString().equals("Restante")){
                       selecionado=selecionado+ clsaux.capturaValores(TbTitulos.getValueAt(i, 4).toString());
                   }else TbTitulos.setValueAt(false, i, 0);
                   
               }
           }
          
        lbValorSelecionado.setText(clsaux.formato(selecionado));
    }
    public void acaoTipoForm(){
            tipo= this.getTitle();
            if (tipo.equals("Cadastro de Contas a Receber")){
            tipo="E";
            }if (tipo.equals("Cadastro de Contas a Pagar")){
            tipo="S";
            }if (tipo.equals("")){
            }
    }
    public void acaoBtnAlterar(){
        CadContasRecPagar cp= new CadContasRecPagar();
        ContasReceberDAO crDAO= new ContasReceberDAO();
        String parc= TbTitulos.getValueAt(TbTitulos.getSelectedRow(), 1).toString();
        crDAO.pesquisaRegistroAlterar(cp, parc);
        FormContasPagarReceber dialog = new FormContasPagarReceber(new javax.swing.JFrame(), true);
        dialog.alterarContaReceber(cp);
        dialog.setVisible(true);
    }
    public void acaoBtnExcluir(){
        ContasReceberDAO crDAO= new ContasReceberDAO();
        String idtitulo =TbTitulos.getValueAt(TbTitulos.getSelectedRow(), 1).toString();
        crDAO.excluir(idtitulo);
    
    }
    public void acaoBtnItensReferente(){
        List<String> id= new ArrayList();
        DefaultTableModel tb = (DefaultTableModel)TbTitulos.getModel();
        int tam=tb.getRowCount();
        for (int l=0; l<tam; l++){
            if ((Boolean) tb.getValueAt(l, 0)==true){
                id.add(tb.getValueAt(l, 1).toString());
            }
        }
        frmInformaItensReferente.idtitulos=id;
        frmInformaItensReferente dialog = new frmInformaItensReferente(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        
    }
    public void acaoBtnMarcarTodos(){
        DefaultTableModel tb = (DefaultTableModel)TbTitulos.getModel();
        int tamanho= tb.getRowCount();
        for(int l=0; l<tamanho; l++){
            tb.setValueAt(true, l, 0);
        }
        validaCelulaMarcada();
    }
    public void exportarArquivoExcel() throws IOException{
        String caminho="c:/esfhera/adm/expor/titulos.xls";
        
        HSSFWorkbook book= new HSSFWorkbook();
           
        HSSFSheet sheet = book.createSheet("titulos");
        
        HSSFRow cabecalho= sheet.createRow(0);
        cabecalho.createCell(0).setCellValue("Documento");
        cabecalho.createCell(1).setCellValue("Parceiro");
        cabecalho.createCell(2).setCellValue("Valor");
        cabecalho.createCell(3).setCellValue("Data Lancamento");
        cabecalho.createCell(4).setCellValue("Data Vencimento");
        cabecalho.createCell(5).setCellValue("Observacao");
        for(int i=0; i<TbTitulos.getRowCount();i++){
             HSSFRow row=sheet.createRow(i+1);
             row.createCell(0).setCellValue(clsaux.trataCampoNulo(TbTitulos.getValueAt(i, 2)));
             row.createCell(1).setCellValue(TbTitulos.getValueAt(i, 3).toString());
             row.createCell(2).setCellValue(clsaux.capturaValores(TbTitulos.getValueAt(i, 4).toString()));
             row.createCell(3).setCellValue(TbTitulos.getValueAt(i, 5).toString());
             row.createCell(4).setCellValue(TbTitulos.getValueAt(i, 6).toString());
             row.createCell(5).setCellValue(clsaux.trataCampoNulo(TbTitulos.getValueAt(i, 14)));
        }
        FileOutputStream fil= new FileOutputStream(new File(caminho));
        
        book.write(fil);
        fil.close();
       
        JOptionPane.showMessageDialog(null, "Planilha Gerada Com Sucesso!!!\nCaminho Do Arquivo "+caminho);
    
    }
    public void acaoBtnBuscar(){
        String filtrarpor=JcbFiltrarPor.getSelectedItem().toString();
        String estadotitulo=JcbEstadoTitulo.getSelectedItem().toString();
        String datainicio=JftfDatInicio.getText().replaceAll("/", ".");
        String datafim=JftfDatFim.getText().replaceAll("/", ".");
        String campopesq=JtxtPesquisa.getText();
        con.clear();
        if (estadotitulo.equals("Vencido")){
            
                estadotitulo="5";
                }else if (estadotitulo.equals("Anulado")){
                estadotitulo="7";
                }else if(estadotitulo.equals("Pendente")){
                estadotitulo="'4' or tc.estado='11'";        
                }else if (estadotitulo.equals("Quitado")){
                estadotitulo="6";
                }else if (estadotitulo.equals("Todos")){
                estadotitulo="0";
                };
        this.acaoTipoForm();
        this.buscaTitulos(estadotitulo,filtrarpor,datainicio,datafim,campopesq);
    }
    public void pegaDuploClick(){
        TbTitulos.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e ){
                if (e.getClickCount()==2){
                   acaoBtnAlterar();
                } else if(e.getClickCount()==1){
                    validaCelulaMarcada();
                }
            }
          
        }); 
        
        
        TbTitulos.getInputMap(TbTitulos.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke(KeyEvent.VK_SPACE,0), "espaco");
        TbTitulos.getActionMap().put("espaco", new AbstractAction(){
            public void actionPerformed(ActionEvent e){
                if((Boolean)TbTitulos.getValueAt(TbTitulos.getSelectedRow(), 0)==true){
                    TbTitulos.setValueAt(false, TbTitulos.getSelectedRow(), 0);
                    validaCelulaMarcada();
                }else{
                    TbTitulos.setValueAt(true, TbTitulos.getSelectedRow(), 0);
                    validaCelulaMarcada();
                 }
                
            }
        });
        
        /*TbTitulos.addKeyListener(new KeyAdapter() {
            
        });*/
      }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CRUDTitulo dialog = new CRUDTitulo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbEstadoTitulo;
    private javax.swing.JComboBox<String> JcbFiltrarPor;
    private javax.swing.JFormattedTextField JftfDatFim;
    private javax.swing.JFormattedTextField JftfDatInicio;
    private javax.swing.JTextField JtxtPesquisa;
    public static javax.swing.JTable TbTitulos;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBaixarTitulo;
    private javax.swing.JButton btnExcluir;
    public static javax.swing.JButton btnPesq;
    private javax.swing.JComboBox<String> cbTipoTitulo;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTotalreg;
    private javax.swing.JLabel lbTotalregvalor;
    private javax.swing.JTextField lbValorSelecionado;
    private javax.swing.JLabel lbtipo;
    private javax.swing.JTextField txtValortotal;
    // End of variables declaration//GEN-END:variables
}
