/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic.interfac;


import DAO.lancDocumentDAO;
import DAO.produtoDAO;
import Logs.gravarLog;
import classes.ClsDadosInventario;
import classes.clsLocalizaProduto;
import classes.clsaux;

import contrato.escolheImpressao;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import model.clsLancDocCabecalho;
import model.clsLancDocument;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import util.validaDigitosBarras;

/**
 *
 * @author Rodrigo
 */
public class CRUDInventario extends javax.swing.JDialog {

    /**
     * Creates new form CRUDproduto
     */
    public CRUDInventario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        inicia();
    }

    public List<clsLancDocCabecalho> registros= new ArrayList<>();
    lancDocumentDAO dao = new lancDocumentDAO();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbInventario = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbItensRef = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lbLog = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        btnExcluirItem = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(219, 227, 227));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tbInventario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mvto", "Data Lancamento", "Valor total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbInventario.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbInventario.setRowHeight(24);
        tbInventario.getTableHeader().setReorderingAllowed(false);
        tbInventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbInventarioMouseClicked(evt);
            }
        });
        tbInventario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbInventarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbInventarioKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbInventario);
        if (tbInventario.getColumnModel().getColumnCount() > 0) {
            tbInventario.getColumnModel().getColumn(0).setResizable(false);
            tbInventario.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbInventario.getColumnModel().getColumn(1).setResizable(false);
            tbInventario.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbInventario.getColumnModel().getColumn(2).setResizable(false);
            tbInventario.getColumnModel().getColumn(2).setPreferredWidth(80);
        }

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tbItensRef.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbItensRef.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Codigo", "Descrição", "Unidade", "Quantidade", "Valor", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbItensRef.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tbItensRef.setRowHeight(24);
        tbItensRef.getTableHeader().setReorderingAllowed(false);
        tbItensRef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItensRefMouseClicked(evt);
            }
        });
        tbItensRef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbItensRefKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbItensRefKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbItensRef);
        if (tbItensRef.getColumnModel().getColumnCount() > 0) {
            tbItensRef.getColumnModel().getColumn(0).setResizable(false);
            tbItensRef.getColumnModel().getColumn(0).setPreferredWidth(80);
            tbItensRef.getColumnModel().getColumn(1).setResizable(false);
            tbItensRef.getColumnModel().getColumn(1).setPreferredWidth(150);
            tbItensRef.getColumnModel().getColumn(2).setResizable(false);
            tbItensRef.getColumnModel().getColumn(2).setPreferredWidth(250);
            tbItensRef.getColumnModel().getColumn(3).setResizable(false);
            tbItensRef.getColumnModel().getColumn(3).setPreferredWidth(50);
            tbItensRef.getColumnModel().getColumn(4).setResizable(false);
            tbItensRef.getColumnModel().getColumn(4).setPreferredWidth(180);
            tbItensRef.getColumnModel().getColumn(5).setResizable(false);
            tbItensRef.getColumnModel().getColumn(5).setPreferredWidth(120);
            tbItensRef.getColumnModel().getColumn(6).setPreferredWidth(180);
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("- Produtos Referente");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Inventario", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane2.setToolTipText("");
        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane2.setInheritsPopupMenu(true);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton1.setText("Exp. Estoque Atual");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 506, Short.MAX_VALUE)
                .addComponent(lbLog, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Exportar", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButton2.setText("Imp. Estoque XLS");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Layout Arquivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(630, 630, 630))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(509, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Importar", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/prod98.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel3.setText("Cadastro Inventario");
        jLabel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel3FocusGained(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fechar99.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        btnExcluirItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/deletar99.png"))); // NOI18N
        btnExcluirItem.setText("Excluir");
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar97.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnIncluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais99.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("- Arquivos / Produtos/Inventario De Estoque");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluirItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
        int yn= JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o registro selecionado?", "exclusão de registro", JOptionPane.YES_NO_OPTION);
        if (yn== JOptionPane.YES_OPTION){
            
        }

    }//GEN-LAST:event_btnExcluirItemActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
      FrmCadInventario dialog = new FrmCadInventario(new javax.swing.JFrame(), true);
     dialog.setLocationRelativeTo(null);
     dialog.carregarRegistro(registros.get(tbInventario.getSelectedRow()));
     dialog.setVisible(true);
       
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
     FrmCadInventario dialog = new FrmCadInventario(new javax.swing.JFrame(), true);
     dialog.setLocationRelativeTo(null);
     dialog.novoRegistro();
     dialog.setVisible(true);
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void tbInventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbInventarioMouseClicked
       
    }//GEN-LAST:event_tbInventarioMouseClicked

    private void tbInventarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbInventarioKeyPressed
       
    }//GEN-LAST:event_tbInventarioKeyPressed

    private void tbInventarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbInventarioKeyReleased
       
    }//GEN-LAST:event_tbInventarioKeyReleased

    private void tbItensRefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItensRefMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbItensRefMouseClicked

    private void tbItensRefKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbItensRefKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbItensRefKeyPressed

    private void tbItensRefKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbItensRefKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbItensRefKeyReleased

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       
    }//GEN-LAST:event_formWindowActivated

    private void jLabel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel3FocusGained
       
    }//GEN-LAST:event_jLabel3FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        gerarXlsEstoque();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       JOptionPane.showMessageDialog(null, "Layout para importacao, codigo barras, nome, quantidade");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        abrirPesquisaArquivos();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void inicia(){
        tbInventario.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e ){
                if (e.getClickCount()==2){
                   populaTabelaProd();
                } 
            }
          
        }); 
        populaTabelaInventario();
        
     
      }
    
    
  
    
    
    
    public void populaTabelaInventario(){
        registros=dao.buscarListaMovimentosTipo("4");
        DefaultTableModel tb= (DefaultTableModel) tbInventario.getModel();
        tb.setNumRows(0);
        for( clsLancDocCabecalho cad : registros){
            tb.addRow(new Object[]{
               cad.getIdmovimento(),
               clsaux.convertDataExib(cad.getLancamento()),
               clsaux.formataReais(clsaux.capturaValores(cad.getTotal()))
            
            });
        }
        
        
    }
    public void populaTabelaProd(){
        String adc= tbInventario.getValueAt(tbInventario.getSelectedRow(), 0).toString();
        List<clsLancDocument> dados= lancDocumentDAO.buscaItens(adc);
        
        DefaultTableModel tbprod= (DefaultTableModel) tbItensRef.getModel();
        tbprod.setNumRows(0);
        
        for(clsLancDocument dad:dados){
            tbprod.addRow(new Object[]{
                dad.getIdproduto(),
                dad.getBarras(),
                dad.getDescricaofornecedor(),
                dad.getUnidade(),
                clsaux.formato(clsaux.capturaValores(dad.getQuantidade())),
                clsaux.formato(clsaux.capturaValores(dad.getPrecovenda())),
                clsaux.formato(clsaux.capturaValores(dad.getTotal()))
            });
        }
        
    }
    
    public void gerarXlsEstoque(){
       try {
            lbLog.setText("Aguarde, Gerando Registros");
            String caminho="c:/esfhera/adm/expor/estoque"+clsaux.retorDataHora()+".xls";
            HSSFWorkbook book= new HSSFWorkbook();
            HSSFSheet sheet = book.createSheet("estoque");
            HSSFRow cabecalho= sheet.createRow(0);
            cabecalho.createCell(0).setCellValue("Codigo Barras");
            cabecalho.createCell(1).setCellValue("Nome");
            cabecalho.createCell(2).setCellValue("Estoque");
            cabecalho.createCell(3).setCellValue("Custo");
            List<ClsDadosInventario> lista= dao.retornaItensInventario();
            int tamanho=1;
            System.out.println(lista.size());
            for(ClsDadosInventario cls:lista){
                HSSFRow row=sheet.createRow(tamanho);
                row.createCell(0).setCellValue(cls.getBarras());
                row.createCell(1).setCellValue(cls.getNome());
                row.createCell(2).setCellValue(cls.getEstoque());
                row.createCell(3).setCellValue(cls.getCusto());
                tamanho++;
            }  
            FileOutputStream fil= new FileOutputStream(new File(caminho));
            book.write(fil);
            fil.close();
            lbLog.setText("Gerado Com Sucesso");
            JOptionPane.showMessageDialog(null, "Planilha Gerada Com Sucesso!!!\nCaminho Do Arquivo "+caminho);
        } catch (FileNotFoundException ex) {
            lbLog.setText("Falha Ao Gerar");
            gravarLog.main(ex.getMessage());
            Logger.getLogger(CRUDInventario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            lbLog.setText("Falha Ao Gerar");
             gravarLog.main(ex.getMessage());
            Logger.getLogger(CRUDInventario.class.getName()).log(Level.SEVERE, null, ex);
        } 
         
    }
    
    public void importarArquivoEstoque(String caminho){
        try {
            Workbook book= Workbook.getWorkbook(new File(caminho));
            Sheet sheet= book.getSheet(0);
            int tamanhoarquivo=sheet.getRows();
            clsLancDocCabecalho inventario= new clsLancDocCabecalho();
            inventario.setIdmovimento(lancDocumentDAO.insereRegistroBranco("4"));
            inventario.setEmissao(clsaux.retornaData(clsaux.preencheData()));
            inventario.setTotal("0,00");
            
            for (int i=1; i<tamanhoarquivo;i++){
             Cell estoque=sheet.getCell(2,i);
             Cell descricao=sheet.getCell(1,i);
             Cell codbarra=sheet.getCell(0,i);
             insereItem(codbarra.getContents(),descricao.getContents(),estoque.getContents(),inventario,i);
             //indice++;
         }
            inventario.setModelo("99");
            inventario.setDocument("9999");
            inventario.setTotalprod(inventario.getTotal());
            inventario.setIdparceiro("0");
            inventario.setSerie("0");
            inventario.setTipomovimento("4");
            inventario.setLancamento(clsaux.retornaData(clsaux.preencheData()));
            dao.atualizaRegistroMovto(inventario);
        } catch (IOException ex) {
            Logger.getLogger(CRUDInventario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (BiffException ex) {
            Logger.getLogger(CRUDInventario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CRUDInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    }
     private void abrirPesquisaArquivos(){
        int retorno=fileChooser.showOpenDialog(this);
        if (retorno==JFileChooser.APPROVE_OPTION){
            File arquivo=fileChooser.getSelectedFile();
            String caminhoxml=arquivo.getAbsolutePath();
            importarArquivoEstoque(caminhoxml);
        }else{
            JOptionPane.showMessageDialog(null, "Erro ao Localizar Arquivo!!!");
        }
    }
     
     public void insereItem(String barras, String descricao,String estoque,clsLancDocCabecalho inventario,int indice) throws SQLException{
        clsLancDocument item= new clsLancDocument();
        clsLocalizaProduto produto= new clsLocalizaProduto();
        produto.setCodibarra(validaDigitosBarras.preencheCodigo(barras));
        produtoDAO.buscaProduto(produto);
        if(produto!=null){
            item.setBarras(produto.getCodibarra());
            item.setAcrescimo("0.00");
            item.setCfop("0000");
            item.setCodfornecedor(produto.getCodibarra());
            item.setCst("102");
            item.setCusto(clsaux.formato(produto.getPreccusto()));
            item.setQuantidade(clsaux.capturaValor(estoque));
            item.setDesconto("0.00");
            item.setDescricaofornecedor(produto.getDescricao());
            item.setEanComer(produto.getCodibarra());
            item.setFator("1.00");
            item.setIdmovto(inventario.getIdmovimento());
            item.setIdproduto(produto.getIdproduto());
            item.setNcm("00000000");
            item.setNumeroitem(String.valueOf(indice));
            item.setOrigem_produto("0");
            item.setPrecovenda(item.getCusto());
            item.setQntComercial(item.getQuantidade());
            Double total=clsaux.capturaValores(item.getCusto()) * clsaux.capturaValores(item.getQuantidade());
            item.setSubtotal(clsaux.formatoNfe3(total));
            item.setTotal(item.getSubtotal());
            item.setUnidade("UN");
            dao.insereItensReferenteMovto(item);
            inventario.setTotal(clsaux.formatoNfe3(clsaux.capturaValores(inventario.getTotal())+total));
            
        }
        
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
    for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
            UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
           try {
               UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
           } catch (ClassNotFoundException ex) {
               Logger.getLogger(escolheImpressao.class.getName()).log(Level.SEVERE, null, ex);
           } catch (InstantiationException ex) {
               Logger.getLogger(escolheImpressao.class.getName()).log(Level.SEVERE, null, ex);
           } catch (IllegalAccessException ex) {
               Logger.getLogger(escolheImpressao.class.getName()).log(Level.SEVERE, null, ex);
           } catch (UnsupportedLookAndFeelException ex) {
               Logger.getLogger(escolheImpressao.class.getName()).log(Level.SEVERE, null, ex);
           }
}
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CRUDInventario dialog = new CRUDInventario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbLog;
    public static javax.swing.JTable tbInventario;
    public static javax.swing.JTable tbItensRef;
    // End of variables declaration//GEN-END:variables
}
