/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic.interfac;

import DAO.CondicionalDAO;
import DAO.orcamentoDAO;
import classes.ClsCancelamentos;
import model.clsDadosEmpresa;
import classes.clsaux;
import conexoes.conexao;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JDialog;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import model.clsConfig;
import model.clsDadosPagamentoAdm;
import model.clsOrcamento;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import util.CriaMenuOpcoes;

/**
 *
 * @author lucas
 */
public class CRUDCondicional extends javax.swing.JDialog {

    /**
     * Creates new form CRUDCondicional
     */
    public CRUDCondicional(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbAlterar = new javax.swing.JLabel();
        lbAlterar2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbLancamentos = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        ftDataInicio = new javax.swing.JFormattedTextField();
        ftDataTermino = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        JcbCont = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lbTotalreg = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        JcbEstado = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        lbValorTotal = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerênciador de Condicionais");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("Gerencidor de Condicional");

        jPanel4.setBackground(new java.awt.Color(219, 227, 227));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/documentosfiscaos2.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("- Arquivos / Condicionais");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Gerenciador de Condicionais");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 51));
        jLabel10.setText("Incluir");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IncluirFinan.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel9KeyPressed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/DelFinan.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Cancelar");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        lbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mudar2.png"))); // NOI18N
        lbAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAlterarMouseClicked(evt);
            }
        });

        lbAlterar2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbAlterar2.setForeground(new java.awt.Color(148, 148, 0));
        lbAlterar2.setText("Alterar");
        lbAlterar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAlterar2MouseClicked(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close2.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 0));
        jLabel22.setText("Fechar");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAlterar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbAlterar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel7.setBackground(new java.awt.Color(219, 227, 227));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("Filtros");

        jSeparator1.setForeground(new java.awt.Color(0, 102, 102));

        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TbLancamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TbLancamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Conferir", "Parceiro", "Total", "Data Lancamento", "Data Entrega", "Estado", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbLancamentos.setColumnSelectionAllowed(true);
        TbLancamentos.setRowHeight(20);
        TbLancamentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbLancamentos);
        TbLancamentos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (TbLancamentos.getColumnModel().getColumnCount() > 0) {
            TbLancamentos.getColumnModel().getColumn(0).setResizable(false);
            TbLancamentos.getColumnModel().getColumn(0).setPreferredWidth(5);
            TbLancamentos.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Início");

        try {
            ftDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftDataInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            ftDataTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftDataTermino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Término");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Data");

        JcbCont.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JcbCont.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Lançamento", "2- Entrega" }));
        JcbCont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbContActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar.png"))); // NOI18N
        jButton4.setText("Localizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Total de Registros :");

        lbTotalreg.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbTotalreg.setForeground(new java.awt.Color(0, 102, 102));

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Printer.png"))); // NOI18N
        jButton5.setText("Imprimir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Estado");

        JcbEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Andamento", "2- Finalizado", "3- Cancelado", "8- Env. Paerceiro", "9- Env. Producao", "12- Conv.Venda", "15- Conferido", "16- Res. Conferencia" }));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Valor R$:");

        lbValorTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbValorTotal.setForeground(new java.awt.Color(0, 102, 102));

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Nome:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IMPORTAR.png"))); // NOI18N
        jButton1.setText("Conferencia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Reforço.png"))); // NOI18N
        jButton2.setText("Pagamento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcbCont, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14)
                                    .addComponent(ftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(ftDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(JcbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalreg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbTotalreg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JcbCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        jPanel7Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton4});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        frmCadCondicional.tipoform="I";
        frmCadCondicional dialog = new frmCadCondicional(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        frmCadCondicional.tipoform="I";
        frmCadCondicional dialog = new frmCadCondicional(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel9KeyPressed

    }//GEN-LAST:event_jLabel9KeyPressed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
            this.cancela();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.cancela();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void lbAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAlterarMouseClicked
        this.alterarReg();
    }//GEN-LAST:event_lbAlterarMouseClicked

    private void lbAlterar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAlterar2MouseClicked
        this.alterarReg();
    }//GEN-LAST:event_lbAlterar2MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void JcbContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbContActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.pesquisar();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       String prevenda=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 6).toString();
       if(clsConfig.configuracaogeral.getImpressaoCondicionalPadrao().equals("A4")){
           this.imprimirCondicional(prevenda);
       }else{
           try {
               imprimirCondicionalTermica(prevenda);
           } catch (SQLException ex) {
               Logger.getLogger(CRUDCondicional.class.getName()).log(Level.SEVERE, null, ex);
               Logs.gravarLog.main(ex.getMessage());
           } catch (JRException ex) {
               Logger.getLogger(CRUDCondicional.class.getName()).log(Level.SEVERE, null, ex);
                Logs.gravarLog.main(ex.getMessage());
           }
       }
       
       
    }//GEN-LAST:event_jButton5ActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         if(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 5).toString().equals("Em Andamento")||
             TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 5).toString().equals("Res. Conferencia")){
             
                    this.chamarPagamento();
         }else{
             JOptionPane.showMessageDialog(null, " Condicional Não Pode Ser Recebida...\n Verifiue o Estado Da Condicional...");
         }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.verificaItensConferencia();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void inicia(){
        ftDataInicio.setText(clsaux.preencheData());
        ftDataTermino.setText(clsaux.preencheData());
        InputMap imp= this.getRootPane().getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW);
        imp.put(KeyStroke.getKeyStroke(KeyEvent.VK_F1,0),"Novo");
        this.getRootPane().setInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW, imp);
        this.getRootPane().getActionMap().put("Novo", new AbstractAction(){
            public void actionPerformed(ActionEvent ev){
                frmCadCondicional.tipoform="I";
                frmCadCondicional dialog = new frmCadCondicional(new javax.swing.JFrame(), true);
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
          }
        });
        this.listaCliqDireitoMouse();
    }
    
    public void listaCliqDireitoMouse(){
       
                JPopupMenu menu=new JPopupMenu();
                JMenuItem imprimeTermica= new JMenuItem("imprimir Impressora Termica");
                JMenuItem imprimeA4= new JMenuItem("imprimir Impressora A4");
                imprimeA4.addActionListener(new java.awt.event.ActionListener(){
                public void actionPerformed(ActionEvent e ){
                   imprimirCondicional(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 6).toString());
                }
                });
                imprimeTermica.addActionListener(new java.awt.event.ActionListener(){
                public void actionPerformed(ActionEvent e ){
                    try {
                        imprimirCondicionalTermica(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 6).toString());
                    } catch (SQLException ex) {
                        Logger.getLogger(CRUDCondicional.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (JRException ex) {
                        Logger.getLogger(CRUDCondicional.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                });
                menu.add(imprimeTermica);
                menu.add(imprimeA4);
                CriaMenuOpcoes.listaCliqDireitoMouse(TbLancamentos, menu);
     }
            
    public void chamarPagamento(){
        clsDadosPagamentoAdm pag= new clsDadosPagamentoAdm();
        clsOrcamento orc= new clsOrcamento();
        CondicionalDAO con= new CondicionalDAO();
        orc.setId(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 6).toString());
        orc = con.buscaCabecalho(orc);
        pag.setIdcondicional(orc.getId());
        pag.setSubtotal(orc.getTotal());
        pag.setVltotal(orc.getTotal());
        pag.setVlprod(orc.getTotal());
        pag.setDesconto(0.00);
        pag.setTipo("Condicional");
        pag.setVlservico(0.00);
        if(orc.getParceiro()==null||orc.getParceiro().equals(""))pag.setParceiro("0");
        else pag.setParceiro(orc.getParceiro());
        frmPagamentosAdm.pagamento=pag;
        frmPagamentosAdm.orcamento=orc;
        frmPagamentosAdm dialog = new frmPagamentosAdm(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }
    public void pesquisar(){
        try {
            String dtini=ftDataInicio.getText();
            String dtfim=ftDataTermino.getText();
            String tipo=clsaux.retornaId(JcbEstado.getSelectedItem().toString());
            if(tipo.equals("1")){tipo="1 or tv.estado=16";}
            String sql="select  tp.razao_social,\n" +
                    "        tv.total,\n" +
                    "        tv.data_lancamento,\n" +
                    "        tv.data_entregue,\n" +
                    "        tr.descricao,\n" +
                    "        tv.id_prevenda\n" +
                    "from tpre_venda tv\n" +
                    "join tparceiros tp on tp.idparceiro=tv.idcliente\n" +
                    "join testado_operacoes tr on tr.id=tv.estado\n" +
                    "where tv.data_lancamento between ? and ? and tv.estado="+tipo;
           
            PreparedStatement ps = conexao.getPreparedStatement(sql);
            ps.setDate(1, clsaux.retornaData(dtini));
            ps.setDate(2, clsaux.retornaData(dtfim));
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tb = (DefaultTableModel) TbLancamentos.getModel();
            tb.setNumRows(0);
            while(rs.next()){
                tb.addRow(new Object[]{
                    new Boolean(false),
                    rs.getString(1),
                    clsaux.formato(rs.getDouble(2)),
                    clsaux.convertDataExib(rs.getString(3)),
                    clsaux.convertDataExib(rs.getString(4)),
                    rs.getString(5),
                    rs.getString(6)
                });
                
                
            }
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(CRUDCondicional.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void imprimirCondicional(String indice){
        try {
            JDialog viewer = new JDialog(new javax.swing.JFrame(),"Visualização do Relatório", true);
            viewer.setSize(1024,720);
            viewer.setLocationRelativeTo(null);
            JasperDesign jd;
            jd = JRXmlLoader.load(".\\relatorios\\Condicional\\ImpCondicional.jrxml");
            JasperReport jr= JasperCompileManager.compileReport(jd);
            String sqlitens="select  tp.id_produto as codigo,\n" +
                            "        td.nomelongo,\n" +
                            "        tp.valor_unitario as vl_unit,\n" +
                            "        tp.qnt,\n" +
                            "        tp.vl_total as total,td.unid_venda,tp.desconto\n" +
                            " from titens_prevenda tp\n" +
                            "join tprodutos td on tp.id_produto=td.id\n" +
                            "where tp.id_prevenda='"+indice+"'";
            String sqldadoscond="select tv.total,\n" +
                            "       tv.data_lancamento,\n" +
                            "       tp.cnpj,\n" +
                            "       tp.razao_social,\n" +
                            "       tc.rua,\n" +
                            "       tc.bairro,\n" +
                            "       tc.numero,\n" +
                            "       tc.cidade,\n" +
                            "       tc.estado,\n" +
"                                   iif(tv.data_entregue is null, '',tv.data_entregue) dat_ent,\n" +
"                                   tf.nome\n" +
"                             from tpre_venda tv\n" +
"                             join tparceiros tp on tv.idcliente=tp.idparceiro\n" +
"                             join tenderecos tc on tp.idparceiro=tc.id_parceiro\n" +
"                             left join tfuncionarios tf on tv.funcionario=tf.id"+
                             " where tv.id_prevenda='"+indice+"'";
            PreparedStatement ps=conexao.getPreparedStatementResult(sqldadoscond);
            PreparedStatement pst= conexao.getPreparedStatement(sqlitens);
            ResultSet rs = ps.executeQuery();
            rs.first();
            Map parametros = new HashMap();
            parametros.put("total", clsaux.formato(rs.getDouble(1)));
            parametros.put("cliDataEnt", clsaux.convertDataExib(rs.getString(2)));
            parametros.put("cliCpf", rs.getString(3));
            parametros.put("cliNome", rs.getString(4));
            parametros.put("cliRua", rs.getString(5));
            parametros.put("cliBairro", rs.getString(6));
            parametros.put("cliNum", rs.getString(7));
            parametros.put("cliCidadeEstado", rs.getString(8)+"/"+rs.getString(9));
            parametros.put("cliDataRet", rs.getString(10));
            parametros.put("numCondi", indice);
            parametros.put("funcionario", rs.getString(11));
            parametros.put("formapgto", "");
            parametros.put("RAZAO_SOCIAL", clsDadosEmpresa.getRazao());
            parametros.put("RUA", clsDadosEmpresa.getRua());
            parametros.put("NUMERO", clsDadosEmpresa.getNumero());
            parametros.put("BAIRRO", clsDadosEmpresa.getBairro());
            parametros.put("CEP", "00000-000");
            parametros.put("CIDADE", clsDadosEmpresa.getCidade());
            parametros.put("UF", clsDadosEmpresa.getEstado());
            parametros.put("FONE", clsDadosEmpresa.getFone());
            rs.close();
            rs = pst.executeQuery();
            JRResultSetDataSource jrds= new JRResultSetDataSource(rs);
            JasperPrint impre= JasperFillManager.fillReport(jr, parametros, jrds);
            JasperViewer jv = new JasperViewer(impre, true);
            viewer.getContentPane().add(jv.getContentPane());
            viewer.setVisible(true);   
        } catch (JRException ex) {
            Logger.getLogger(CRUDCondicional.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CRUDCondicional.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    public void imprimirCondicionalTermica(String indice) throws SQLException, JRException{
        String caminho=conexao.cam+"Condicional/ImpCondicionalTermica.jasper";
        String sqlitens="select  tp.id_produto as codigo,\n" +
                            "        td.nomelongo,\n" +
                            "        tp.valor_unitario as vl_unit,\n" +
                            "        tp.qnt,\n" +
                            "        tp.vl_total as total,td.unid_venda,tp.desconto\n" +
                            " from titens_prevenda tp\n" +
                            "join tprodutos td on tp.id_produto=td.id\n" +
                            "where tp.id_prevenda='"+indice+"'";
            String sqldadoscond="select tv.total,\n" +
                            "       tv.data_lancamento,\n" +
                            "       tp.cnpj,\n" +
                            "       tp.razao_social,\n" +
                            "       tc.rua,\n" +
                            "       tc.bairro,\n" +
                            "       tc.numero,\n" +
                            "       tc.cidade,\n" +
                            "       tc.estado,\n" +
"                                   iif(tv.data_entregue is null, '',tv.data_entregue) dat_ent,\n" +
"                                   tf.nome,tp.fone,tp.celular\n" +
"                             from tpre_venda tv\n" +
"                             join tparceiros tp on tv.idcliente=tp.idparceiro\n" +
"                             join tenderecos tc on tp.idparceiro=tc.id_parceiro\n" +
"                             left join tfuncionarios tf on tv.funcionario=tf.id"+
                             " where tv.id_prevenda='"+indice+"'";
            PreparedStatement ps=conexao.getPreparedStatementResult(sqldadoscond);
            PreparedStatement pst= conexao.getPreparedStatement(sqlitens);
            ResultSet rs = ps.executeQuery();
            rs.first();
            Map parametros = new HashMap();
            parametros.put("total", clsaux.formato(rs.getDouble(1)));
            parametros.put("prod", clsaux.formato(rs.getDouble(1)));
            parametros.put("desc", "0,00");
            parametros.put("cliDataEnt", clsaux.convertDataExib(rs.getString(2)));
            parametros.put("cnpjcli", rs.getString(3));
            parametros.put("fonecli", rs.getString(12));
            parametros.put("celularcli", rs.getString(13));
            parametros.put("fantasiacli", rs.getString(4));
            parametros.put("cliRua", rs.getString(5));
            parametros.put("cliBairro", rs.getString(6));
            parametros.put("cliNum", rs.getString(7));
            parametros.put("cliCidadeEstado", rs.getString(8)+"/"+rs.getString(9));
            parametros.put("cliDataRet", rs.getString(10));
            parametros.put("numCondi", indice);
            parametros.put("funcionario", rs.getString(11));
            parametros.put("formapgto", "");
            parametros.put("RAZAO_SOCIAL", clsDadosEmpresa.getRazao());
            parametros.put("CNPJEMIT", clsDadosEmpresa.getCnpj());
            parametros.put("EMAIL", clsDadosEmpresa.getEmail());
            parametros.put("RUA", clsDadosEmpresa.getRua());
            parametros.put("NUMERO", clsDadosEmpresa.getNumero());
            parametros.put("BAIRRO", clsDadosEmpresa.getBairro());
            parametros.put("CEP", "00000-000");
            parametros.put("CIDADE", clsDadosEmpresa.getCidade());
            parametros.put("UF", clsDadosEmpresa.getEstado());
            parametros.put("FONE", clsDadosEmpresa.getFone());
            rs.close();
            rs = pst.executeQuery();
            JRResultSetDataSource jrds= new JRResultSetDataSource(rs);
            JasperPrint jp= JasperFillManager.fillReport(caminho, parametros,jrds);
            JasperPrintManager.printPage(jp, 0, false);
    }
    public void alterarReg(){
        if(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 5).toString().equals("Em Andamento")/*||
             TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 5).toString().equals("Res. Conferencia")*/){
            
            String reg= TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 6).toString();
            frmCadCondicional.tipoform="A";
            frmCadCondicional.idregistro= reg; 
            frmCadCondicional dialog = new frmCadCondicional(new javax.swing.JFrame(), true);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Condicional Não Pode Ser Alterada!!!");
        }
    }
    public void verificaItensConferencia(){
        DefaultTableModel tbl = (DefaultTableModel) TbLancamentos.getModel();
        List<String> condicionais= new ArrayList();
        int registros=0;
        int totalregistros= tbl.getRowCount();
        for(int i=0; i<totalregistros; i++){
            if ((Boolean) tbl.getValueAt(i, 0)==true){
                registros++;
                String valorcampo= tbl.getValueAt(i, 6).toString();
                condicionais.add(valorcampo);
                if(TbLancamentos.getValueAt(i, 5).toString().equals("Em Andamento")){}else{
                    registros=0;
                    condicionais.clear();
                }
            }
        }
        if (registros<=0){
            JOptionPane.showMessageDialog(null, "Não é Possivel Conferir!!!\n Nenhum Registro Selecionado Ou Foi Selecionado\n Registros Com Estado Diferente de Em Andamento...");
        }else {
            frmConferenciaCondicional.ids=condicionais;
            frmConferenciaCondicional dialog = new frmConferenciaCondicional(new javax.swing.JFrame(), true);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);
        }
       
    }
    public void cancela(){
       
        int yn= JOptionPane.showConfirmDialog(null, "Deseja Cancelar a Operação?", "Cancelar Operação", JOptionPane.YES_NO_OPTION);
        if (yn== JOptionPane.YES_OPTION){
            ClsCancelamentos canc= new ClsCancelamentos();
            if(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 5).toString().equals("Em Andamento")){
               canc.cancelaCondicionalPeloMovimento(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 6).toString());
            }else if (TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 5).toString().equals("Finalizado")){
             String id= orcamentoDAO.retornaIdMovimento(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 6).toString(), "2");
             canc.cancelarMovimentacaoReferente(id);
            }else if(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 5).toString().equals("Cancelado")){
                JOptionPane.showMessageDialog(null, "Registro Já Cancelado!!!");
            }
           
         }
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDCondicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDCondicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDCondicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDCondicional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CRUDCondicional dialog = new CRUDCondicional(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbCont;
    private javax.swing.JComboBox<String> JcbEstado;
    private javax.swing.JTable TbLancamentos;
    private javax.swing.JFormattedTextField ftDataInicio;
    private javax.swing.JFormattedTextField ftDataTermino;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAlterar;
    private javax.swing.JLabel lbAlterar2;
    private javax.swing.JLabel lbTotalreg;
    private javax.swing.JLabel lbValorTotal;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
