/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic.interfac;

import DAO.clienteDAO;
import DAO.lancDocumentDAO;
import DAO.nfeDAO;
import br.com.swconsultoria.certificado.exception.CertificadoException;
import br.com.swconsultoria.nfe.Nfe;
import br.com.swconsultoria.nfe.dom.ConfiguracoesNfe;
import br.com.swconsultoria.nfe.dom.enuns.DocumentoEnum;
import br.com.swconsultoria.nfe.exception.NfeException;
import br.com.swconsultoria.nfe.schema_4.retConsSitNFe.TRetConsSitNFe;
import classes.ClsEnvioEmail;
import classes.ClsGeraXmlContabilidade;
import model.clsDadosEmpresa;
import model.clsLancDocCabecalho;
import classes.clsaux;
import conexoes.conexao;
import fiscal.clsCancelarNfe;
import fiscal.clsEmiteNfe;
import fiscal.clsEnviaNfce;
import fiscal.clsInutilizarNfe;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.file.Files;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.xml.bind.JAXBException;
import javax.xml.parsers.ParserConfigurationException;
import model.clientes;
import model.clsConfig;
import model.clsNfe;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.xml.sax.SAXException;

/**
 *
 * @author lucas
 */
public class CRUDNfe extends javax.swing.JDialog {

    /**
     * Creates new form CRUDCondicional
     */
    public CRUDNfe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.inicia();
    }
    
    public static String carregaAutomatico="N";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbAlterar = new javax.swing.JLabel();
        lbAlterar2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbLancamentos = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        lbTotalreg = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbValorTotal = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cbModelo = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        JcbEstado = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        ftDataInicio = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        ftDataTermino = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnEnviarNfce = new javax.swing.JButton();
        btnInutilizarNfce = new javax.swing.JButton();
        btnEnvTodas = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnCancelarNfce = new javax.swing.JButton();
        btnInutilizarTodas = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnCancelarNfce1 = new javax.swing.JButton();
        btnEnvTodas1 = new javax.swing.JButton();
        btnEnvTodas2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerênciador de NFe");
        setBackground(new java.awt.Color(219, 227, 227));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("Gerencidor de Condicional");

        jPanel4.setBackground(new java.awt.Color(219, 227, 227));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nfe2.jpg"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("- Arquivos / Nota Fiscal Eletrônica");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Gerenciador de Notas Fiscais");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 102, 51));
        jLabel10.setText("Incluir");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IncluirFinan.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jLabel9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel9KeyPressed(evt);
            }
        });

        lbAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mudar2.png"))); // NOI18N
        lbAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAlterarMouseClicked(evt);
            }
        });

        lbAlterar2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbAlterar2.setForeground(new java.awt.Color(148, 148, 0));
        lbAlterar2.setText("Alterar");
        lbAlterar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAlterar2MouseClicked(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close2.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 0, 0));
        jLabel22.setText("Fechar");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAlterar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(lbAlterar2)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21)
                            .addComponent(lbAlterar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel7.setBackground(new java.awt.Color(219, 227, 227));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        TbLancamentos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TbLancamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Parceiro", "Numero", "Serie", "Modelo", "Total", "Data Lancamento", "Sit. Sefaz", "Cstat", "Tipo Movimento", "Chave Acesso", "Motivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbLancamentos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TbLancamentos.setColumnSelectionAllowed(true);
        TbLancamentos.setRowHeight(20);
        TbLancamentos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbLancamentos);
        TbLancamentos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (TbLancamentos.getColumnModel().getColumnCount() > 0) {
            TbLancamentos.getColumnModel().getColumn(0).setPreferredWidth(70);
            TbLancamentos.getColumnModel().getColumn(1).setPreferredWidth(250);
            TbLancamentos.getColumnModel().getColumn(2).setPreferredWidth(50);
            TbLancamentos.getColumnModel().getColumn(3).setPreferredWidth(50);
            TbLancamentos.getColumnModel().getColumn(4).setPreferredWidth(50);
            TbLancamentos.getColumnModel().getColumn(5).setPreferredWidth(120);
            TbLancamentos.getColumnModel().getColumn(6).setPreferredWidth(150);
            TbLancamentos.getColumnModel().getColumn(7).setPreferredWidth(200);
            TbLancamentos.getColumnModel().getColumn(8).setPreferredWidth(50);
            TbLancamentos.getColumnModel().getColumn(9).setPreferredWidth(70);
            TbLancamentos.getColumnModel().getColumn(10).setPreferredWidth(400);
            TbLancamentos.getColumnModel().getColumn(11).setPreferredWidth(800);
        }

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Total de Registros :");

        lbTotalreg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbTotalreg.setForeground(new java.awt.Color(0, 102, 102));

        jLabel19.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 102, 102));
        jLabel19.setText("Valor R$:");

        lbValorTotal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbValorTotal.setForeground(new java.awt.Color(0, 102, 102));

        jTabbedPane1.setBackground(new java.awt.Color(219, 227, 227));

        jPanel2.setBackground(new java.awt.Color(219, 227, 227));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Data");

        cbModelo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Nfe Data", "2- Nfce Data", "3-Todos" }));
        cbModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbModeloActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("Estado");

        JcbEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JcbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Não Enviada", "2- Autorizada", "3- Canceladas", "4- Com Erros", "5- Todos" }));
        JcbEstado.setSelectedIndex(4);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Início");

        try {
            ftDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftDataInicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Término");

        try {
            ftDataTermino.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftDataTermino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Nome:");

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnPesquisa.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar.png"))); // NOI18N
        btnPesquisa.setText("Localizar");
        btnPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnPesquisaFocusGained(evt);
            }
        });
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbModelo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JcbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNome)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(ftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(ftDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JcbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftDataTermino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisa)
                .addGap(0, 206, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Filtros", jPanel2);

        jPanel3.setBackground(new java.awt.Color(219, 227, 227));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Enviar Nfe");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Cancelar Nfe");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Inutilizar Nfe");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setText("Carta Correção");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton6.setText("Imprimir Nfe");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton7.setText("Enviar E-mail");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton8.setText("Consulta Nfe");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton9.setText("Duplicar NFe");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton8, jButton9});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton7, jButton8});

        jTabbedPane1.addTab("Opções Nfe", jPanel3);

        jPanel5.setBackground(new java.awt.Color(219, 227, 227));

        btnEnviarNfce.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEnviarNfce.setText("Enviar Nfce Pendente");
        btnEnviarNfce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarNfceActionPerformed(evt);
            }
        });

        btnInutilizarNfce.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnInutilizarNfce.setText("Inutilizar Nfce Selecionada");
        btnInutilizarNfce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInutilizarNfceActionPerformed(evt);
            }
        });

        btnEnvTodas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEnvTodas.setText("Enviar Todas Nfce Pendente");
        btnEnvTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvTodasActionPerformed(evt);
            }
        });

        btnCancelarNfce.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelarNfce.setText("Consultar Nfce Selecionada");
        btnCancelarNfce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNfceActionPerformed(evt);
            }
        });

        btnInutilizarTodas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnInutilizarTodas.setText("Inutlizar Todas Nfce");
        btnInutilizarTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInutilizarTodasActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Gerar Xml Contabilidade");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnCancelarNfce1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelarNfce1.setText("Cancelar Nfce Selecionada");
        btnCancelarNfce1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarNfce1ActionPerformed(evt);
            }
        });

        btnEnvTodas1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEnvTodas1.setText("Imprimir Nfce");
        btnEnvTodas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvTodas1ActionPerformed(evt);
            }
        });

        btnEnvTodas2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEnvTodas2.setText("Enviar Via Email");
        btnEnvTodas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnvTodas2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEnvTodas2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEnvTodas1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInutilizarTodas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEnviarNfce, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInutilizarNfce, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(btnEnvTodas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(btnCancelarNfce, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                            .addComponent(btnCancelarNfce1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnEnviarNfce, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInutilizarNfce, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelarNfce1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelarNfce, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(btnEnvTodas1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnvTodas2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnEnvTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInutilizarTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Opções NFCe", jPanel5);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTotalreg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbTotalreg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(560, 560, 560))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 635, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        frmLancamentoNfe.estadoform="I";
        frmLancamentoNfe dialog = new frmLancamentoNfe(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        frmLancamentoNfe.estadoform="I";
        frmLancamentoNfe dialog = new frmLancamentoNfe(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel9KeyPressed

    }//GEN-LAST:event_jLabel9KeyPressed

    private void lbAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAlterarMouseClicked
        this.alterarReg();
    }//GEN-LAST:event_lbAlterarMouseClicked

    private void lbAlterar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAlterar2MouseClicked
        this.alterarReg();
    }//GEN-LAST:event_lbAlterar2MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel22MouseClicked

    private void cbModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbModeloActionPerformed

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        this.pesquisar();
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        enviarNfe();
        this.pesquisar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        int yn= JOptionPane.showConfirmDialog(null, "ATENÇÃO\nO Cancelamento Da Nfe irá Cancelar Também\nToda a Movimentacao Financeira!!!\n\n Deseja "
                + "Realmente Cancelar?", "exclusão de registro", JOptionPane.YES_NO_OPTION);
        if (yn== JOptionPane.YES_OPTION){
           this.cancelarNfe();
           this.pesquisar(); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int yn= JOptionPane.showConfirmDialog(null, "Deseja realmente Inutilizar a NFe selecionada?", "exclusão de registro", JOptionPane.YES_NO_OPTION);
        if (yn== JOptionPane.YES_OPTION){
           this.inutilizarNfe();
           this.pesquisar();
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       ImprimirNfe();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.enviarEmailNfe(
                TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 0).toString()
        );
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnPesquisaFocusGained
        this.pesquisar();
    }//GEN-LAST:event_btnPesquisaFocusGained

    private void btnEnviarNfceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarNfceActionPerformed
        this.enviarNfceOffline();
        this.pesquisar();
    }//GEN-LAST:event_btnEnviarNfceActionPerformed

    private void btnInutilizarNfceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInutilizarNfceActionPerformed
        this.inutilizarNfe();
        this.pesquisar();
    }//GEN-LAST:event_btnInutilizarNfceActionPerformed

    private void btnCancelarNfceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNfceActionPerformed
       this.consultaNfe(DocumentoEnum.NFCE);
       this.pesquisar();
    }//GEN-LAST:event_btnCancelarNfceActionPerformed

    private void btnEnvTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvTodasActionPerformed
       this.enviarTodasNfceOffline();
    }//GEN-LAST:event_btnEnvTodasActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       ClsGeraXmlContabilidade xm= new ClsGeraXmlContabilidade();
       xm.gerarXml(clsaux.retornaData(ftDataInicio.getText()), clsaux.retornaData(ftDataTermino.getText()));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       this.consultaNfe(DocumentoEnum.NFE);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void btnCancelarNfce1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarNfce1ActionPerformed
       cancelarNfe();
    }//GEN-LAST:event_btnCancelarNfce1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       this.duplicarNfe();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnInutilizarTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInutilizarTodasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInutilizarTodasActionPerformed

    private void btnEnvTodas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvTodas1ActionPerformed
        this.imprimeNfce();
    }//GEN-LAST:event_btnEnvTodas1ActionPerformed

    private void btnEnvTodas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnvTodas2ActionPerformed
        this.enviarEmailNfce( TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 0).toString());
    }//GEN-LAST:event_btnEnvTodas2ActionPerformed
    public void inicia(){
        ftDataInicio.setText(clsaux.preencheData());
        ftDataTermino.setText(clsaux.preencheData());
        if (carregaAutomatico.equals("S")){
            JcbEstado.setSelectedIndex(0);
            this.pesquisar();
        }
        jTabbedPane1.setEnabledAt(2, false);
    }
    public void pesquisar(){
        try {
            String dtini=ftDataInicio.getText();
            String dtfim=ftDataTermino.getText();
            String tipo=clsaux.retornaId(JcbEstado.getSelectedItem().toString());
            String modelo=clsaux.retornaId(cbModelo.getSelectedItem().toString());
            
            if(modelo.equals("1")){
                modelo="and tm.id_modelo=55";
                jTabbedPane1.setEnabledAt(2, false);
            }
            else if(modelo.equals("2")){
                modelo="and tm.id_modelo=65";
                jTabbedPane1.setEnabledAt(2, true);
            }
            else {
                modelo="";
                 jTabbedPane1.setEnabledAt(2, true);
            }
            
           
            String sql="select\n" +
                    "    tm.id_mov,\n" +
                    "    tp.razao_social,\n" +
                    "    tm.numero_documento,\n" +
                    "    tm.total,\n" +
                    "    tm.data,\n" +
                    "    tm.data,\n" +
                    "    tn.cstat,\n" +
                    "    td.descricao,tm.chave_acesso, tc.descricao,tm.numero_documento,tm.serie,tm.id_modelo,tn.motivo_sefaz\n" +
                    "from tmovimento tm\n" +
                    "join tparceiros tp on tm.id_parceiro=tp.idparceiro\n" +
                    "join tnota_fiscal tn on tm.id_mov= tn.id_movimento\n" +
                    "join ttipo_documentos td on tm.id_tipo=td.id\n" +
                    "left join tsit_nf_receita tc on tn.cstat=tc.cstat \n"
                    + "   where data between ? and ? "+modelo;
            switch(tipo){
                case "1": sql="select\n" +
                    "    tm.id_mov,\n" +
                    "    tp.razao_social,\n" +
                    "    tm.numero_documento,\n" +
                    "    tm.total,\n" +
                    "    tm.data,\n" +
                    "    tm.data,\n" +
                    "    tn.cstat,\n" +
                    "    td.descricao,tm.chave_acesso, tc.descricao,tm.numero_documento,tm.serie,tm.id_modelo,tn.motivo_sefaz\n" +
                    "from tmovimento tm\n" +
                    "join tparceiros tp on tm.id_parceiro=tp.idparceiro\n" +
                    "join tnota_fiscal tn on tm.id_mov= tn.id_movimento\n" +
                    "join ttipo_documentos td on tm.id_tipo=td.id\n" +
                    "left join tsit_nf_receita tc on tn.cstat=tc.cstat \n"
                    + "   where data between ? and ?  and tn.cstat=0 "+ modelo;
                break;
                case "2": sql="select\n" +
                    "    tm.id_mov,\n" +
                    "    tp.razao_social,\n" +
                    "    tm.numero_documento,\n" +
                    "    tm.total,\n" +
                    "    tm.data,\n" +
                    "    tm.data,\n" +
                    "    tn.cstat,\n" +
                    "    td.descricao,tm.chave_acesso, tc.descricao,tm.numero_documento,tm.serie,tm.id_modelo,tn.motivo_sefaz\n" +
                    "from tmovimento tm\n" +
                    "join tparceiros tp on tm.id_parceiro=tp.idparceiro\n" +
                    "join tnota_fiscal tn on tm.id_mov= tn.id_movimento\n" +
                    "join ttipo_documentos td on tm.id_tipo=td.id\n" +
                    "left join tsit_nf_receita tc on tn.cstat=tc.cstat \n"
                    + "   where data between ? and ?  and (tn.cstat=100 or tn.cstat=150) " + modelo;
                break;
                case "3": sql="select\n" +
                    "    tm.id_mov,\n" +
                    "    tp.razao_social,\n" +
                    "    tm.numero_documento,\n" +
                    "    tm.total,\n" +
                    "    tm.data,\n" +
                    "    tm.data,\n" +
                    "    tn.cstat,\n" +
                    "    td.descricao,tm.chave_acesso, tc.descricao,tm.numero_documento,tm.serie,tm.id_modelo,tn.motivo_sefaz\n" +
                    "from tmovimento tm\n" +
                    "join tparceiros tp on tm.id_parceiro=tp.idparceiro\n" +
                    "join tnota_fiscal tn on tm.id_mov= tn.id_movimento\n" +
                    "join ttipo_documentos td on tm.id_tipo=td.id\n" +
                    "left join tsit_nf_receita tc on tn.cstat=tc.cstat \n"
                    + "   where data between ? and ? and (tn.cstat=101 or tn.cstat=102) " +modelo;
                break;
                case "4": sql="select\n" +
                    "    tm.id_mov,\n" +
                    "    tp.razao_social,\n" +
                    "    tm.numero_documento,\n" +
                    "    tm.total,\n" +
                    "    tm.data,\n" +
                    "    tm.data,\n" +
                    "    tn.cstat,\n" +
                    "    td.descricao,tm.chave_acesso, tc.descricao,tm.numero_documento,tm.serie,tm.id_modelo,tn.motivo_sefaz\n" +
                    "from tmovimento tm\n" +
                    "join tparceiros tp on tm.id_parceiro=tp.idparceiro\n" +
                    "join tnota_fiscal tn on tm.id_mov= tn.id_movimento\n" +
                    "join ttipo_documentos td on tm.id_tipo=td.id\n" +
                    "left join tsit_nf_receita tc on tn.cstat=tc.cstat \n"
                    + "   where data between ? and ? and tn.cstat>150 "+ modelo;
                break;
            }
            PreparedStatement ps = conexao.getPreparedStatement(sql);
            ps.setDate(1, clsaux.retornaData(dtini));
            ps.setDate(2, clsaux.retornaData(dtfim));
            ResultSet rs = ps.executeQuery();
            DefaultTableModel tb = (DefaultTableModel) TbLancamentos.getModel();
            tb.setNumRows(0);
            Double total=0.00;
            int reg=0;
            while(rs.next()){
                tb.addRow(new Object[]{
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(12),
                    rs.getString(13),
                    clsaux.formato(rs.getDouble(4)),
                    clsaux.convertDataExib(rs.getString(5)),
                    rs.getString(10),
                    rs.getString(7),
                    rs.getString(8),
                    rs.getString(9),
                    rs.getString(14)
                });
                total=total+rs.getDouble(4);
                reg++;
            }
            rs.close();
            ps.close();
            this.sinalizaSituacaoNf();
            lbValorTotal.setText(clsaux.formato(total));
            lbTotalreg.setText(""+reg);
        } catch (SQLException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void alterarReg(){
        frmLancamentoNfe.estadoform="A";
        frmLancamentoNfe.idmovimento=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 0).toString();
        frmLancamentoNfe dialog = new frmLancamentoNfe(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }
    
    private void enviarNfe() {
        try {
            Long movimento = Long.parseLong(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 0).toString());
            String cst=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 8).toString();
            if (cst.equals("0")){
                new clsEmiteNfe(movimento);
            }else{
                JOptionPane.showMessageDialog(null, "Não é Possivel Enviar NFe!!!\n");
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Enviando NFe!!!\n"+ex.toString());
            
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void ImprimirNfe(){
        try {
            String chave=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 10).toString();
            String cst=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 8).toString();
            if (cst.equals("100")||cst.equals("150")){
                 clsEmiteNfe.realizaImpresaoNfeAntiga(chave);
            }else{
                JOptionPane.showMessageDialog(null, "NFe Não Autorizada!!!\n");
            }
           
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, "Imprimindo NFe!!!\n"+ex.getMessage());
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException | IOException | SAXException ex) {
            JOptionPane.showMessageDialog(null, "Imprimindo NFe!!!\n"+ex.getMessage());
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    
    
    }
    private void cancelarNfe(){
            Long movimento = Long.parseLong(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 0).toString());
            String chave=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 10).toString();
            String cst=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 8).toString();
            String modelo=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 4).toString();
            if (cst.equals("100")||cst.equals("150")){
                try {
                    new clsCancelarNfe(movimento, chave,modelo);
                } catch (NfeException ex) {
                    JOptionPane.showMessageDialog(null, "Cancelando NFe!!!\n"+ex.getMessage());
                    Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
                } catch (CertificadoException ex) {
                    JOptionPane.showMessageDialog(null, "Cancelando NFe!!!\n"+ex.getMessage());
                    Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
                } catch (JAXBException | IOException ex) {
                    JOptionPane.showMessageDialog(null, "Cancelando NFe!!!\n"+ex.getMessage());
                    Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "NFe Não Autorizada!!!\n");
            }
    
    
    }
    private void inutilizarNfe(){
        clsLancDocCabecalho mov= new clsLancDocCabecalho();
        mov.setIdmovimento(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 0).toString());
        String cst=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 8).toString();
        mov=lancDocumentDAO.buscaCabecalhoDoc(mov);
        if (cst.equals("100")||cst.equals("150")||cst.equals("101")||cst.equals("102")){
             JOptionPane.showMessageDialog(null, "Não é Possivel Inutilizar Nfe!!!\n");
        }else{
            try {
                new clsInutilizarNfe(mov);
            } catch (NfeException ex) {
                 JOptionPane.showMessageDialog(null, "Inutilizando NFe!!!\n"+ex.getMessage());
                Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
            } catch (CertificadoException ex) {
                JOptionPane.showMessageDialog(null, "Inutilizando NFe!!!\n"+ex.getMessage());
                Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
            } catch (JAXBException ex) {
                JOptionPane.showMessageDialog(null, "Inutilizando NFe!!!\n"+ex.getMessage());
                Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Inutilizando NFe!!!\n"+ex.getMessage());
                Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    
    }
    public void sinalizaSituacaoNf(){
        TbLancamentos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected,hasFocus, row, column);
            String desc=(String) TbLancamentos.getValueAt(row, 8);
            if (desc.trim().equals("150")||desc.trim().equals("100")){
                setForeground(new Color(0,153,51));
            } else if (desc.trim().equals("102")){
                setForeground(Color.BLUE);
            }else if (desc.trim().equals("101")){
                 setForeground(Color.red);
            }else{
                setForeground(Color.black);
            }
            return this;
            }
         });
     }
    public void enviarNfceOffline(){
         String mvto=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 0).toString();
         String situacao=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 8).toString();
        try {
            if(situacao.equals("100")||situacao.equals("150")){
                JOptionPane.showMessageDialog(null, "Nota Fiscal Já Enviada");
                
            }else{
                new clsEnviaNfce(Long.parseLong(mvto));
            }
            
        } catch (Exception ex) {
            //JOptionPane.showMessageDialog(null, ex.getMessage());
            Logs.gravarLog.main(ex.getMessage());
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void imprimeNfce(){
        try {
            String mvto=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 0).toString();
            String chave=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 10).toString();
            clsEnviaNfce.realizaImpresaoNfeAntiga(chave, mvto);
        } catch (JRException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void enviarTodasNfceOffline(){
        int tamanho= TbLancamentos.getRowCount();
        for(int i=0; i<tamanho; i++){
             String mvto=TbLancamentos.getValueAt(i, 0).toString();
             String situacao=TbLancamentos.getValueAt(i, 8).toString();
            try {
             if(situacao.equals("100")||situacao.equals("150")){
             }else{
                new clsEnviaNfce(Long.parseLong(mvto));
            }
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    }
    public void inutilizarTodos(){
        clsLancDocCabecalho mov= new clsLancDocCabecalho();
        
          int tamanho= TbLancamentos.getRowCount();
        for(int i=0; i<tamanho; i++){
             String mvto=TbLancamentos.getValueAt(i, 0).toString();
             String cst=TbLancamentos.getValueAt(i, 8).toString();
             mov.setIdmovimento(mvto);
             mov=lancDocumentDAO.buscaCabecalhoDoc(mov);
            try {
             if(cst.equals("100")||cst.equals("150")||cst.equals("101")||cst.equals("102")){
             }else{
                new clsInutilizarNfe(mov);
            }
          } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    
        
    }
    
    
      public void enviarEmailNfce(String mvto){
          
        try {
            clsLancDocCabecalho cd= new clsLancDocCabecalho();
            cd.setIdmovimento(mvto);
            cd=lancDocumentDAO.buscaCabecalhoDoc(cd);
            clsEnviaNfce.salvaPdf(cd.getChaveacesso());
            
            clientes cli= new clientes();
            cli= clienteDAO.buscar("1", cli, cd.getIdparceiro());
            
            String email = JOptionPane.showInputDialog("Informe o seu e-mail:",cli.getEmail());

    
            String caminhoOrigem=clsConfig.configuracaogeral.getCaminhoxml()+"nfce\\xml\\"+cd.getChaveacesso()+".xml";
            String pdf=clsConfig.configuracaogeral.getCaminhoxml()+"Nfce\\pdf\\NFce"+cd.getChaveacesso()+".pdf";
            
            if(email!=null&& email.length()>5){
                ClsEnvioEmail.enviarNfeXmlPdf(caminhoOrigem,pdf, email, "",cd.getDocument());
            }else{
                JOptionPane.showMessageDialog(null, "E-mail Do Destinatario Invalido!!!");
            }
        } catch (JRException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        }
            
            
    }
    public void enviarEmailNfe(String mvto){
            clsLancDocCabecalho cd= new clsLancDocCabecalho();
            cd.setIdmovimento(mvto);
            cd=lancDocumentDAO.buscaCabecalhoDoc(cd);
            
            clientes cli= new clientes();
            cli= clienteDAO.buscar("1", cli, cd.getIdparceiro());
            
            String email = JOptionPane.showInputDialog("Informe o seu e-mail:",cli.getEmail());
    
            String caminhoOrigem=clsConfig.configuracaogeral.getCaminhoxml()+"nfe\\xml\\"+cd.getChaveacesso()+".xml";
            String pdf=clsConfig.configuracaogeral.getCaminhoxml()+"Nfe\\pdf\\NFe"+cd.getChaveacesso()+".pdf";
            
            if(email!=null&& email.length()>5){
                    ClsEnvioEmail.enviarNfeXmlPdf(caminhoOrigem,pdf, email, "",cd.getDocument());
            }else{
                JOptionPane.showMessageDialog(null, "E-mail Do Destinatario Invalido!!!");
            }
            
            
    }
    
    public void consultaNfe(DocumentoEnum doc ){
        try {
            clsLancDocCabecalho mov= new clsLancDocCabecalho();
            clsNfe nf= new clsNfe();
            mov.setIdmovimento(TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 0).toString());
            String cst=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 8).toString();
            mov=lancDocumentDAO.buscaCabecalhoDoc(mov);
            nf=nfeDAO.retornaDadosMovNf(Long.parseLong(mov.getIdmovimento()));
            
            ConfiguracoesNfe con= conexao.iniciaConfifNfe();
            
            String chave= mov.getChaveacesso();
            
            TRetConsSitNFe retorno=Nfe.consultaXml(con, chave, doc);
            
            if(cst.equals("100")||cst.equals("101")||cst.equals("102")||cst.equals("150")){
            }else{
                nf.setCstat(retorno.getCStat());
                nf.setMotivo(retorno.getXMotivo());
                if(retorno.getProtNFe()!=null){
                    nf.setProtocoloaut(retorno.getProtNFe().getInfProt().getNProt());
                
                }
                nfeDAO.inserirMovimentoNfe(nf);
            }
            JOptionPane.showMessageDialog(null, " Status: " + retorno.getCStat() + " - " + retorno.getXMotivo());
            
        } catch (CertificadoException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NfeException ex) {
            Logger.getLogger(CRUDNfe.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
   
    public void duplicarNfe(){
        frmLancamentoNfe.estadoform="D"; // indica que deve ser duplicado o registro da nf
        frmLancamentoNfe.idmvtoOrigemDuplica=TbLancamentos.getValueAt(TbLancamentos.getSelectedRow(), 0).toString();
        frmLancamentoNfe dialog = new frmLancamentoNfe(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDNfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDNfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDNfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDNfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CRUDNfe dialog = new CRUDNfe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbEstado;
    private javax.swing.JTable TbLancamentos;
    private javax.swing.JButton btnCancelarNfce;
    private javax.swing.JButton btnCancelarNfce1;
    private javax.swing.JButton btnEnvTodas;
    private javax.swing.JButton btnEnvTodas1;
    private javax.swing.JButton btnEnvTodas2;
    private javax.swing.JButton btnEnviarNfce;
    private javax.swing.JButton btnInutilizarNfce;
    private javax.swing.JButton btnInutilizarTodas;
    public static javax.swing.JButton btnPesquisa;
    private javax.swing.JComboBox<String> cbModelo;
    private javax.swing.JFormattedTextField ftDataInicio;
    private javax.swing.JFormattedTextField ftDataTermino;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbAlterar;
    private javax.swing.JLabel lbAlterar2;
    private javax.swing.JLabel lbTotalreg;
    private javax.swing.JLabel lbValorTotal;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables

    
}
