/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic.interfac;

import DAO.clienteDAO;
import com.sun.glass.events.KeyEvent;
import model.clientes;
import model.clsDadosEmpresa;
import conexoes.conexao;
import contrato.escolheImpressao;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigo
 */
public class CRUDparceiro extends javax.swing.JDialog {

    /**
     * Creates new form CRUDparceiro
     */
    public CRUDparceiro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.inicia();
        txtpesquisa.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        txtpesquisa = new javax.swing.JTextField();
        BntVendasParceiros = new javax.swing.JButton();
        BtnCreditosParceiros = new javax.swing.JButton();
        BtnTitulosParceiros = new javax.swing.JButton();
        CbEstadoParceiros = new javax.swing.JComboBox<>();
        BtnLocalizaParceiros = new javax.swing.JButton();
        BtnCreditosParceiros1 = new javax.swing.JButton();
        btnGeraTitulo11 = new javax.swing.JButton();
        btnGeraTitulo12 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableParceiros = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluirItem = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTabbedPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));

        jPanel4.setBackground(new java.awt.Color(219, 227, 227));

        txtpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpesquisaActionPerformed(evt);
            }
        });

        BntVendasParceiros.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        BntVendasParceiros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Vendas.png"))); // NOI18N
        BntVendasParceiros.setText("Movimento");
        BntVendasParceiros.setBorder(null);
        BntVendasParceiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BntVendasParceirosActionPerformed(evt);
            }
        });

        BtnCreditosParceiros.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        BtnCreditosParceiros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pagamento.png"))); // NOI18N
        BtnCreditosParceiros.setText("  Créditos");
        BtnCreditosParceiros.setEnabled(false);

        BtnTitulosParceiros.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        BtnTitulosParceiros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ApagarPqno.png"))); // NOI18N
        BtnTitulosParceiros.setText("     Títulos");
        BtnTitulosParceiros.setEnabled(false);

        CbEstadoParceiros.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CbEstadoParceiros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo", "Bloqueado" }));

        BtnLocalizaParceiros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        BtnLocalizaParceiros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BtnLocalizaParceirosFocusGained(evt);
            }
        });
        BtnLocalizaParceiros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLocalizaParceirosActionPerformed(evt);
            }
        });

        BtnCreditosParceiros1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        BtnCreditosParceiros1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pagamento.png"))); // NOI18N
        BtnCreditosParceiros1.setText("Resg Pontos");
        BtnCreditosParceiros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCreditosParceiros1ActionPerformed(evt);
            }
        });

        btnGeraTitulo11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGeraTitulo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/impressora.png"))); // NOI18N
        btnGeraTitulo11.setText("Declarações");
        btnGeraTitulo11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraTitulo11ActionPerformed(evt);
            }
        });

        btnGeraTitulo12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnGeraTitulo12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/relpprod.png"))); // NOI18N
        btnGeraTitulo12.setText("Habitualidade");
        btnGeraTitulo12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeraTitulo12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCreditosParceiros1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbEstadoParceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnLocalizaParceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnGeraTitulo11, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeraTitulo12, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BtnTitulosParceiros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCreditosParceiros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BntVendasParceiros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CbEstadoParceiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnLocalizaParceiros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(btnGeraTitulo12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGeraTitulo11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCreditosParceiros1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCreditosParceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BntVendasParceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnTitulosParceiros, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        jTabbedPane3.addTab("Filtros", jPanel4);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));

        TableParceiros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TableParceiros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tipo", "Razao Social", "Fantasia", "Cnpj", "Incricao Estadual", "Telefone", "Rua", "Bairro", "Cidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableParceiros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TableParceiros.setRowHeight(20);
        TableParceiros.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TableParceiros);
        if (TableParceiros.getColumnModel().getColumnCount() > 0) {
            TableParceiros.getColumnModel().getColumn(0).setResizable(false);
            TableParceiros.getColumnModel().getColumn(0).setPreferredWidth(50);
            TableParceiros.getColumnModel().getColumn(1).setResizable(false);
            TableParceiros.getColumnModel().getColumn(1).setPreferredWidth(90);
            TableParceiros.getColumnModel().getColumn(2).setPreferredWidth(300);
            TableParceiros.getColumnModel().getColumn(3).setPreferredWidth(200);
            TableParceiros.getColumnModel().getColumn(4).setPreferredWidth(120);
            TableParceiros.getColumnModel().getColumn(5).setPreferredWidth(100);
            TableParceiros.getColumnModel().getColumn(6).setPreferredWidth(100);
            TableParceiros.getColumnModel().getColumn(7).setPreferredWidth(300);
            TableParceiros.getColumnModel().getColumn(8).setPreferredWidth(150);
            TableParceiros.getColumnModel().getColumn(9).setPreferredWidth(150);
        }

        jTabbedPane1.addTab("Registros", jScrollPane1);

        jPanel1.setBackground(new java.awt.Color(219, 227, 227));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadcliente.png"))); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Listagem de Parceiros");

        btnIncluir.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IncluirFinan.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mudar2.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluirItem.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnExcluirItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/DelFinan.png"))); // NOI18N
        btnExcluirItem.setText("Excluir");
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        btnFechar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        btnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close2.png"))); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("- Arquivos / Parceiros");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluirItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExcluirItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1)))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLocalizaParceirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLocalizaParceirosActionPerformed
        this.pesquisaParceiro(txtpesquisa.getText());
    }//GEN-LAST:event_BtnLocalizaParceirosActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        Cadclientes.Origem="Cadastro";
        Cadclientes dialog = new Cadclientes(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       this.alterarParceiro();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
        Object[] opcoes = {"Sim", "Não"};
        int opc = JOptionPane.showOptionDialog(null, "Deseja realmente excluir o Parceiro selecionado?", "Exclusao de Parceiros...", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,null, opcoes,opcoes[1]);
        if(opc==0){
           String idparcei=TableParceiros.getValueAt(TableParceiros.getSelectedRow(), 0).toString(); 
           clienteDAO cli = new clienteDAO();
           cli.deletar(idparcei);
           this.pesquisaParceiro("");
        }
    }//GEN-LAST:event_btnExcluirItemActionPerformed

    private void btnGeraTitulo11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraTitulo11ActionPerformed
        String idcli=TableParceiros.getValueAt(TableParceiros.getSelectedRow(), 0).toString();
        escolheImpressao.idparceiro=idcli;
        escolheImpressao dialog = new escolheImpressao(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnGeraTitulo11ActionPerformed

    private void btnGeraTitulo12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeraTitulo12ActionPerformed
        String parc=TableParceiros.getValueAt(TableParceiros.getSelectedRow(), 0).toString();
        frmHabitualidade.cli=parc;
        frmHabitualidade dialog = new frmHabitualidade(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnGeraTitulo12ActionPerformed

    private void BtnCreditosParceiros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCreditosParceiros1ActionPerformed
        String parc=TableParceiros.getValueAt(TableParceiros.getSelectedRow(), 0).toString();
        frmClubePontos.idcliente=parc;
        frmClubePontos dialog = new frmClubePontos(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_BtnCreditosParceiros1ActionPerformed

    private void txtpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpesquisaActionPerformed
       this.pesquisaParceiro(txtpesquisa.getText());
    }//GEN-LAST:event_txtpesquisaActionPerformed

    private void BtnLocalizaParceirosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BtnLocalizaParceirosFocusGained
       this.pesquisaParceiro("");
    }//GEN-LAST:event_BtnLocalizaParceirosFocusGained

    private void BntVendasParceirosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BntVendasParceirosActionPerformed
        FrmMovimentacaoParceiro.parceiro=TableParceiros.getValueAt(TableParceiros.getSelectedRow(), 0).toString();
        FrmMovimentacaoParceiro dialog = new FrmMovimentacaoParceiro(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_BntVendasParceirosActionPerformed
   
    public void inicia(){
        if (clsDadosEmpresa.clube.equals("N")){
            btnGeraTitulo12.setVisible(false);
            btnGeraTitulo11.setVisible(false);
        }
         TableParceiros.addMouseListener(new MouseAdapter(){
            public void mouseClicked(MouseEvent e ){
                if (e.getClickCount()==2){
                   alterarParceiro();
                } 
            }
          
        }); 
        InputMap imp= this.getRootPane().getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW);
        imp.put(KeyStroke.getKeyStroke(KeyEvent.VK_F1,0),"inserir");
        this.getRootPane().setInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW, imp);
        this.getRootPane().getActionMap().put("inserir", new AbstractAction(){
            public void actionPerformed(ActionEvent ev){
               Cadclientes.Origem="Cadastro";
                Cadclientes dialog = new Cadclientes(new javax.swing.JFrame(), true);
                dialog.setVisible(true);
            }
        });
    
    }
    private void pesquisaParceiro(String text) {
               String sqlpesqclientes="select p.idparceiro,\n" +
                                "    p.razao_social,\n" +
                                "    p.cnpj,\n" +
                                "    p.inscricao_estadual,\n" +
                                "    p.fone,\n" +
                                "    e.rua,\n" +
                                "    e.bairro,"
                                  + "e.cidade,p.tipo_parceiro,p.fantasia \n" +
                                "from tparceiros p\n" +
                                "join tenderecos  e on p.idparceiro=e.id_parceiro"
                    + " where p.excluido='N' and (p.razao_social like '%"+text+"%' or p.cnpj like'%"+text+"%' or p.fantasia like'%"+text+"%')";
            PreparedStatement psPesqCliente = conexao.getPreparedStatement(sqlpesqclientes);
            try{
            ResultSet rsPesqCliente = psPesqCliente.executeQuery();
            DefaultTableModel tbresultado= (DefaultTableModel) TableParceiros.getModel();
            tbresultado.setNumRows(0);
            String tipo="";
            while(rsPesqCliente.next()){
                if(rsPesqCliente.getString(9).equals("C"))tipo="Cliente";
                else if (rsPesqCliente.getString(9).equals("F")) tipo="Fornecedor";
                else{
                    tipo="Outros";
                }
                tbresultado.addRow( new Object[]{
                  rsPesqCliente.getString(1),
                    tipo,
                  rsPesqCliente.getString(2),
                  rsPesqCliente.getString(10),
                  rsPesqCliente.getString(3),
                  rsPesqCliente.getString(4),
                  rsPesqCliente.getString(5),
                  rsPesqCliente.getString(6),
                  rsPesqCliente.getString(7),
                  rsPesqCliente.getString(8)
                });
                
            }
            rsPesqCliente.close();
            psPesqCliente.close();
            }catch(SQLException err){
                    JOptionPane.showMessageDialog(null, err.getMessage());
                    System.out.println(err.getMessage());
                 }
    }
    public void alterarParceiro(){
        String idparcei=TableParceiros.getValueAt(TableParceiros.getSelectedRow(), 0).toString();
        clientes cl= new clientes();
        clienteDAO cDAO =new clienteDAO();
        cDAO.buscar(null, cl, idparcei);
        Cadclientes dialog = new Cadclientes(new javax.swing.JFrame(), true);
        dialog.listaDados(cl);
        dialog.setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDparceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDparceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDparceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDparceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CRUDparceiro dialog = new CRUDparceiro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BntVendasParceiros;
    private javax.swing.JButton BtnCreditosParceiros;
    private javax.swing.JButton BtnCreditosParceiros1;
    protected static javax.swing.JButton BtnLocalizaParceiros;
    private javax.swing.JButton BtnTitulosParceiros;
    private javax.swing.JComboBox<String> CbEstadoParceiros;
    private javax.swing.JTable TableParceiros;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGeraTitulo11;
    private javax.swing.JButton btnGeraTitulo12;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField txtpesquisa;
    // End of variables declaration//GEN-END:variables

    

   
}
