package grafic.interfac;
import Controller.BaseLocacao;
import DAO.empresaDAO;
import DAO.permissaoUsuarioDAO;
import Logs.gravarLog;
import classes.ClsVerificaVersao;
import model.clsConfig;
import model.clsDadosEmpresa;
import classes.clsaux;
import conexoes.conexao;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import util.ValidaLicencaServidorOnline;
/**
 *
 * @author lucas
 */
public class formLogarsistema extends javax.swing.JFrame {

    /**
     * Creates new form formLogarsistema
     */
    String nomeUsuarioLogado = null;
    
    public formLogarsistema() {
        initComponents();
        getImage();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        senhaUsuario = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        BtnSair = new javax.swing.JButton();
        BtnLogar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbVersao = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pbCarrega = new javax.swing.JProgressBar();

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("1.0.1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(300, 250));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USUÁRIO :");

        login.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        login.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SENHA :");

        senhaUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        senhaUsuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        senhaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaUsuarioActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102)));

        BtnSair.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancela.png"))); // NOI18N
        BtnSair.setText("SAIR");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        BtnLogar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        BtnLogar.setText("Logar");
        BtnLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLogarActionPerformed(evt);
            }
        });
        BtnLogar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnLogarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(BtnLogar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnLogar)
                    .addComponent(BtnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnLogar, BtnSair});

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logomk.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Versão :");

        lbVersao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Contato: (42)98885-0711");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 102)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 432, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Carregando:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(login)
                                    .addComponent(senhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(pbCarrega, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(senhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addComponent(pbCarrega, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVersao, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLogarActionPerformed
       this.logarsistema();
      /*  this.carregaConfiguraao();
      this.carregaParametrosFinanceiro();
      this.logarsistema();
      this.preecnherDadosempresa();
      this.validarLicenca();
      this.validaPermissoes();*/
    }//GEN-LAST:event_BtnLogarActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_BtnSairActionPerformed

    private void BtnLogarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnLogarKeyPressed
       // this.logarsistema();
    }//GEN-LAST:event_BtnLogarKeyPressed

    private void senhaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaUsuarioActionPerformed
     this.logarsistema();
    }//GEN-LAST:event_senhaUsuarioActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
       senhaUsuario.requestFocus();
    }//GEN-LAST:event_loginActionPerformed
    private void logarsistema(){
        String sql ="select idusuario, nome_usuario from tusuarios where (nome_usuario=? or idusuario=? ) and senha =?";
        String inf= login.getText();
        if(inf.matches("[0-9]+")){
        }else{
            inf="0";
        }
        PreparedStatement p = conexao.getPreparedStatement(sql);
        try {
            p.setString(1, login.getText());
            p.setString(2, inf);
            p.setString(3, senhaUsuario.getText());
            ResultSet re = p.executeQuery();
            if (re.next()){
             clsConfig.usuarioLogado = re.getString(1) + "-" + login.getText();
             nomeUsuarioLogado = re.getString(2);
             BtnLogar.setEnabled(false);
             this.verificaversao();
            }else {
                JOptionPane.showMessageDialog(null, "Usuario ou senha incorretos!!!");
            }
        } catch (SQLException ex) {
             Logger.getLogger(formLogarsistema.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Erro ao buscar dados usuario\n" +ex.getMessage());
        } 
    }
    private void preecnherDadosempresa(){
        try {
            String sqlpeg="select * from tcad_empresa;";
            PreparedStatement ps= conexao.getPreparedStatementResult(sqlpeg);
            ResultSet rs;
            rs = ps.executeQuery();
            rs.first();
            clsDadosEmpresa.setCnpj(rs.getString(2));
            clsDadosEmpresa.setIncricao_estadual(rs.getString(3));
            clsDadosEmpresa.razao=rs.getString(4);
            clsDadosEmpresa.setFantasia(rs.getString(5));
            clsDadosEmpresa.setRua(rs.getString(6));
            clsDadosEmpresa.setBairro(rs.getString(7));
            clsDadosEmpresa.setNumero(rs.getString(8));
            clsDadosEmpresa.setFone(rs.getString(12));
            clsDadosEmpresa.setCidade(rs.getString(17));
            clsDadosEmpresa.setCep(rs.getString("cep"));
            clsDadosEmpresa.setEstado(rs.getString(16));
            clsDadosEmpresa.clube=rs.getString("clube_tiro");
            clsDadosEmpresa.setEmailconador(rs.getString("email_contador"));
            clsDadosEmpresa.setRegime(rs.getString("regime_tributacao"));
            clsDadosEmpresa.setEmail(rs.getString("email"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "erro para buscar dados da empresa !!!"  +ex.getMessage());
            gravarLog.main(ex.getMessage().toString());
            Logger.getLogger(formLogarsistema.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }
    private void carregaConfiguraao(){
        try {
            String sql="select * from tconfig";
            PreparedStatement ps = conexao.getPreparedStatementResult(sql);
            ResultSet rs= ps.executeQuery();
            rs.first();
            String val=null;
            clsConfig.imprimeConsumo=rs.getString("IMPRIME_CONSUMO_TIRO");
            clsConfig.enviaapi=rs.getString("SINCRONIZAR_API");
            clsConfig.usacreditocliente=rs.getString("UTILIZA_CREDITO_CLIENTE");
            clsConfig.datainiciocontrolefinanceiro=clsaux.retornaData(clsaux.convertDataExib(rs.getString("DATA_INI_MOV_CONTA")));
            clsConfig.localizaporcr=rs.getString("pesq_por_cr");
            clsConfig.precCatLanTiro=rs.getString("usa_prec_cat_tiro");
            clsConfig.linhasCupomTiro=rs.getInt("Linhas_cupom");
            
            if (rs.getString("RATEIA_DESCONTO_ITENS").equals("null")||rs.getString("RATEIA_DESCONTO_ITENS").isEmpty()){
                        val="N";
                    } else{
                    val=rs.getString("RATEIA_DESCONTO_ITENS");
            };
            clsConfig.versao=clsaux.trataCampoNulo(rs.getString("VERSAO_SIS"));
            clsConfig.rateiadescontoitens=val;
            clsConfig.validadeSistema=clsaux.retornaData(clsaux.convertDataExib(rs.getString("validade")));
            clsConfig.configuracaogeral.setCertificado(rs.getString("caminho_certificado"));
            clsConfig.configuracaogeral.setSenha(rs.getString("senha_certificado"));
            clsConfig.configuracaogeral.setHamb(rs.getString("ambiente"));
            clsConfig.configuracaogeral.setSerienfe(rs.getString("nfe_serie"));
            clsConfig.configuracaogeral.setUltima_consulta(rs.getDate("ultima_consulta"));
            clsConfig.configuracaogeral.setUltima_verificacao(rs.getDate("ultima_verif"));
            clsConfig.configuracaogeral.setUrllicenca(rs.getString("url_consulta"));
            clsConfig.configuracaogeral.setCalculajuros(rs.getString("controla_juros"));
            clsConfig.configuracaogeral.setPercJuros(rs.getDouble("perc_juros"));
            clsConfig.configuracaogeral.setPercMulta(rs.getDouble("perc_multa"));
            clsConfig.configuracaogeral.setCarencia(rs.getInt("carencia"));
            clsConfig.configuracaogeral.setTipoCertificado(rs.getString("tipo_certificado"));
            clsConfig.configuracaogeral.setCadastroProdAutomatico(rs.getString("CADASTRAITEMAUTCOMPRA"));
            clsConfig.configuracaogeral.setAssociacaoCompra(clsaux.trataCampoNuloConfig(rs.getString("TIPO_ASSOCIACAO_COMPRA")));
            clsConfig.configuracaogeral.setImpressaoCondicionalPadrao(rs.getString("imp_padrao_condi"));
            clsConfig.configuracaogeral.setCaminhoxml(rs.getString("caminhoxml"));
            clsConfig.configuracaogeral.setUsaLocacao(rs.getString("usa_locacao"));
            if(clsConfig.configuracaogeral.getCalculajuros().equals("S")){
                this.calculaJuros();
            }
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(formLogarsistema.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "erro ao carregar configuração \n" +ex.getMessage());
        }
    }
    
    public void carregaParametrosFinanceiro(){
        try {
            String sql="select * from tparametros_financeiro";
            PreparedStatement ps = conexao.getPreparedStatementResult(sql);
            ResultSet rs= ps.executeQuery();
            rs.first();  
            clsConfig.financeiro.setSbCondi(rs.getString("sb_condi"));
            clsConfig.financeiro.setSbConfCaixa(rs.getString("sb_conf_caixa"));
            clsConfig.financeiro.setSbEntrada(rs.getString("sb_entrada"));
            clsConfig.financeiro.setSbOrcamento(rs.getString("sb_orcamento"));
            clsConfig.financeiro.setSbPediso(rs.getString("sb_pedido"));
            clsConfig.financeiro.setTpCondi(rs.getString("tp_condi"));
            clsConfig.financeiro.setTpConfCaixa(rs.getString("tp_conf_caixa"));
            clsConfig.financeiro.setTpEntrada(rs.getString("tp_entrada"));
            clsConfig.financeiro.setTpOrcamento(rs.getString("tp_orcamento"));
            clsConfig.financeiro.setTpPedido(rs.getString("tp_pedido"));
            clsConfig.financeiro.setTpTaxaFinanceira(rs.getString("TP_TAXAS_FINANCEIRAS"));
            clsConfig.financeiro.setSbTaxaFinanceira(rs.getString("SB_TAXAS_FINANCEIRAS"));
            rs.close();
            ps.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(formLogarsistema.class.getName()).log(Level.SEVERE, null, ex);
            Logs.gravarLog.gravaSemMensagem(ex.getMessage());
        }
    }
    
    public void validarLicenca(){
        if(clsaux.retornaData(clsaux.calcularData(3, clsConfig.configuracaogeral.getUltima_consulta())).before(clsaux.retornaData(clsaux.preencheData()))==true){
            //valida se faz mais de 3 dias que foi a ultima consulta ao servidor, se sim vai consultar estado da licenca
            if(empresaDAO.verificaTetativas()<6){
                try {
                    ValidaLicencaServidorOnline val= new ValidaLicencaServidorOnline();
                    val.consultarLicencaValidaCnpj(clsDadosEmpresa.cnpj);
                } catch (IOException ex) {
                    Logs.gravarLog.gravaSemMensagem(ex.getMessage());
                    Logger.getLogger(formLogarsistema.class.getName()).log(Level.SEVERE, null, ex);
                    empresaDAO.increntaTentativa(empresaDAO.verificaTetativas()+1);
                }
            }else{
                if(clsConfig.validadeSistema.before(clsaux.retornaData(clsaux.preencheData()))==true){
                frmValidarSenhaSistema dialog = new frmValidarSenhaSistema(new javax.swing.JFrame(), true);
                dialog.preencheDados(clsDadosEmpresa.getCnpj());
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
          }
        }
        
    }
    public void validaPermissoes(){
        formPrincipal1 principal = new formPrincipal1();
        principal.setVisible(true);
        formPrincipal1.labelEmpresa.setText(clsDadosEmpresa.getRazao());
        formPrincipal1.lbUsuario.setText(nomeUsuarioLogado);
        if(permissaoUsuarioDAO.verificaPermissaoUsuConectado("115")); else {
            JOptionPane.showMessageDialog(null, "Usuario Sem Permissão!!!");
            System.exit(0);
        }
        if(permissaoUsuarioDAO.verificaPermissaoUsuConectado("100"));else formPrincipal1.menuConfig.setVisible(false);
        if(permissaoUsuarioDAO.verificaPermissaoUsuConectado("103"));else formPrincipal1.jMenu7.setEnabled(false);
        if(permissaoUsuarioDAO.verificaPermissaoUsuConectado("116"));else{
            formPrincipal1.menuConferenciaCaixa.setVisible(false);
            formPrincipal1.menuMovimentacaoCaixa.setVisible(false);
        }
        if(permissaoUsuarioDAO.verificaPermissaoUsuConectado("105"));else {
            formPrincipal1.LbContasPagar.setVisible(false);
            formPrincipal1.jMenuItem10.setEnabled(false);
        }
        if(permissaoUsuarioDAO.verificaPermissaoUsuConectado("106"));else {
            formPrincipal1.LbContasReceber.setVisible(false);
            formPrincipal1.jMenuItem11.setEnabled(false);
        }
        if(permissaoUsuarioDAO.verificaPermissaoUsuConectado("110"));else {
            formPrincipal1.lbFluxo.setVisible(false);
            formPrincipal1.jMenuItem9.setEnabled(false);
        }
        if(clsDadosEmpresa.clube.equals("N")){
            formPrincipal1.MenuContrato.setVisible(false);
            formPrincipal1.lbalvo.setVisible(false);
        }
    
    }
    public void calculaJuros(){
        try {
            int diasCarencia=clsConfig.configuracaogeral.getCarencia();
            Double taxajuros=clsConfig.configuracaogeral.getPercJuros()/30;
            Double taxamulta=clsConfig.configuracaogeral.getPercMulta();
            String dataParametro=clsaux.calcularData(-diasCarencia, clsaux.retornaData(clsaux.preencheData()));
            String sql="select tp.valor,tp.id,tp.data_vencimento from tcontas_a_receber_pagar tp where tp.pagar_receber=2 and tp.data_vencimento<?";
            PreparedStatement ps = conexao.getPreparedStatementResult(sql);
            ps.setDate(1, clsaux.retornaData(dataParametro));
            ResultSet rs = ps.executeQuery();
            String sql2="update tcontas_a_receber_pagar tp set tp.multa=?, tp.juros=?,tp.valor_total=tp.multa+tp.juros+tp.valor\n" +
                    "where tp.id=?";
            PreparedStatement ps2= conexao.getPreparedStatement(sql2);
            while(rs.next()){
                Double valor=rs.getDouble(1);
                String id= rs.getString(2);
                int diascobrar=clsaux.calcularDiferencaDatas(clsaux.convertDataExib(rs.getString(3)), dataParametro);
                Double vljuro=diascobrar*taxajuros;
                vljuro=valor*vljuro/100;
                Double vlmulta=valor*taxamulta/100;
                ps2.setDouble(1, vlmulta);
                ps2.setDouble(2, vljuro);
                ps2.setString(3, id);
                ps2.executeUpdate();
               
            }
            ps2.close();
            rs.close();
            ps.close();
            
        } catch (SQLException ex) {
            Logger.getLogger(formLogarsistema.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    
    
    
    }
    public void calculaValoresLocacaoAut(){
        if(clsaux.trataCampoNuloConfig(clsConfig.configuracaogeral.getUsaLocacao()).equals("S")){
            if(clsConfig.configuracaogeral.getUltima_verificacao().before(clsaux.retornaData(clsaux.preencheData()))){
                new BaseLocacao().calculaValoresLocacoes();
            }
            
        }
        
    }
    public void atualizaVerififcacao(){
        try {
            String sql="update tconfig set ultima_verif=current_date";
            PreparedStatement ps = conexao.getPreparedStatement(sql);
            ps.executeUpdate();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(formLogarsistema.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }
    
    
    public void verificaversao(){
        if(ClsVerificaVersao.verificaAtualizaVersao()==true){
            carregaGeral();
            }else{
                    JOptionPane.showMessageDialog(null, "Atenção Não Foi Possivel Atualizar O Sistema!!!");
                }
    }
    
    public void carregaGeral(){
        
            new Thread(){
            @Override
            public void run(){
            pbCarrega.setMinimum(0);
            pbCarrega.setMaximum(70);
            pbCarrega.setValue(10);
            carregaConfiguraao();
            pbCarrega.setValue(20);
            carregaParametrosFinanceiro();
            pbCarrega.setValue(30);
            preecnherDadosempresa();
            pbCarrega.setValue(40);
            //calculaJuros();
            pbCarrega.setValue(50);
            calculaValoresLocacaoAut();
            pbCarrega.setValue(60);
            validarLicenca();
            pbCarrega.setValue(70);
            validaPermissoes();
            atualizaVerififcacao();
            dispose();
            this.interrupt();
            }
        
         }.start();
      
        
        
    }
    
    private void getImage() {
        lbVersao.setText(ClsVerificaVersao.versaoCompilada);
        try{
           // setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/LogoResumida.png")));
            setIconImage(Toolkit.getDefaultToolkit().getImage("c:/esfhera/adm/imagens/LogoResumida.png"));
        
        }catch(Exception ep){
             Logger.getLogger(formPrincipal1.class.getName()).log(Level.SEVERE, null, ep);
            JOptionPane.showMessageDialog(null, "erro ao buscar logo\n"+ ep.getMessage());
            Logs.gravarLog.main(ep.getMessage());
        }
        
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogar;
    private javax.swing.JButton BtnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbVersao;
    private javax.swing.JTextField login;
    private javax.swing.JProgressBar pbCarrega;
    private javax.swing.JPasswordField senhaUsuario;
    // End of variables declaration//GEN-END:variables
}
