/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic.interfac;

import DAO.ContasReceberDAO;
import DAO.MovimentoContaDAO;
import DAO.clienteDAO;
import DAO.lancDocumentDAO;
import DAO.listaDAO;
import DAO.nfeDAO;
import DAO.orcamentoDAO;
import model.clientes;
import model.clsOrcamento;
import model.clsOrcamentoItem;
import model.clsPagamentos;
import classes.clsaux;
import grafic.interfac.pesquisa.formProcuraCliente;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import model.CadContasRecPagar;
import model.CadDocMovConta;
import model.clsConfig;
import model.clsNfTransporte;
import model.clsNfe;
import util.validaDataTabela;

/**
 *
 * @author lucas
 */
public class frmCadOrcamento extends javax.swing.JDialog {

  
    public frmCadOrcamento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.inicia();
    }
    public static String idparceiro=null;
    public static String tipoform="I";
    public static String idregistro=null;
    public static int iditem=0;
    double valortotal=0.00;
    double quantidadetotal=0.00;
    static clsOrcamento orcamento= new clsOrcamento();
    static List<clsOrcamentoItem> itens= new ArrayList();
    orcamentoDAO orcdao=new orcamentoDAO();
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtIdParceiro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbEstado = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDataLanc = new javax.swing.JFormattedTextField();
        cbVendedor = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtIdMov = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtFone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnPesq = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProd = new javax.swing.JTable();
        btnIncluir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        CbFinalizadora = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblParcelas = new javax.swing.JTable();
        lbTroco = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        CbParcelas = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        txtDescTotal = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtDescTotalPerc = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        btnRemover = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lbValorTotal = new javax.swing.JLabel();
        lbVlItens = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbVlAcre = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lbVlDesc = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Pedido De Venda");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(219, 227, 227));

        jPanel2.setBackground(new java.awt.Color(219, 227, 227));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtIdParceiro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdParceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdParceiroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Parceiro:");

        cbEstado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Estado:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Data Lançamento:");

        try {
            txtDataLanc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        cbVendedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Vendedor:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Id:");

        txtIdMov.setEditable(false);
        txtIdMov.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Fone:");

        txtFone.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoneActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Cpf/Cnpj:");

        txtCnpj.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Razão Social:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tipo:");

        cbTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Pedido De Venda", "2- Orçamento" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Novo Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procura.png"))); // NOI18N
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdMov, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtIdParceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataLanc, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdMov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtIdParceiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8)))
                                    .addComponent(btnPesq))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1))
                                .addGap(3, 3, 3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtDataLanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(219, 227, 227));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTabbedPane1.setBackground(new java.awt.Color(219, 227, 227));

        jPanel4.setBackground(new java.awt.Color(219, 227, 227));

        tbProd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Indice", "Codigo", "Descrição", "Qnt", "Unitario", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbProd.setRowHeight(20);
        tbProd.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbProd);
        if (tbProd.getColumnModel().getColumnCount() > 0) {
            tbProd.getColumnModel().getColumn(0).setPreferredWidth(2);
            tbProd.getColumnModel().getColumn(1).setPreferredWidth(30);
            tbProd.getColumnModel().getColumn(2).setPreferredWidth(100);
            tbProd.getColumnModel().getColumn(3).setPreferredWidth(10);
            tbProd.getColumnModel().getColumn(4).setPreferredWidth(10);
            tbProd.getColumnModel().getColumn(5).setPreferredWidth(10);
        }

        btnIncluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluir.setText("Exluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnExcluir, btnIncluir});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnExcluir, btnIncluir});

        jTabbedPane1.addTab("Itens", jPanel4);

        jPanel5.setBackground(new java.awt.Color(219, 227, 227));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Obsercações"));

        txtObs.setColumns(20);
        txtObs.setLineWrap(true);
        txtObs.setRows(5);
        jScrollPane2.setViewportView(txtObs);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel22.setText("Finalizadora:");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("Valor:");

        tblParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Valor", "Id Finalizadora", "Parcela", "Troco"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblParcelas);

        lbTroco.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbTroco.setForeground(new java.awt.Color(255, 51, 0));
        lbTroco.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbTroco.setText("0,00");

        jLabel31.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel31.setText("R$");

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Ok");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        CbParcelas.setEditable(true);
        CbParcelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Falta");

        txtDescTotal.setText("0,00");
        txtDescTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescTotalActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel32.setText("Desconto:");

        txtDescTotalPerc.setText("0,00");
        txtDescTotalPerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescTotalPercActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("%");

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/negativo.png"))); // NOI18N
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(CbFinalizadora, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDescTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescTotalPerc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbTroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel32)
                                .addComponent(txtDescTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CbParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel22)
                                .addComponent(CbFinalizadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton3)
                                .addComponent(btnRemover))
                            .addComponent(jLabel30)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTroco)
                            .addComponent(jLabel31)
                            .addComponent(txtDescTotalPerc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(137, 137, 137))
        );

        jTabbedPane1.addTab("Pagamentos", jPanel5);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnGravar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancela.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lbValorTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbValorTotal.setForeground(new java.awt.Color(204, 51, 0));
        lbValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbValorTotal.setText("0,00");

        lbVlItens.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbVlItens.setForeground(new java.awt.Color(204, 51, 0));
        lbVlItens.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbVlItens.setText("0,00");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Total Itens");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Valor Total");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("R$");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("R$");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("R$");

        lbVlAcre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbVlAcre.setForeground(new java.awt.Color(204, 51, 0));
        lbVlAcre.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbVlAcre.setText("0,00");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("Acrescimo");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("R$");

        lbVlDesc.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        lbVlDesc.setForeground(new java.awt.Color(204, 51, 0));
        lbVlDesc.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbVlDesc.setText("0,00");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("Desconto");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbVlItens, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(12, 12, 12)
                                .addComponent(lbVlAcre, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(8, 8, 8)
                                .addComponent(lbVlDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lbValorTotal, lbVlAcre, lbVlDesc, lbVlItens});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbVlItens, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbVlAcre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbVlDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGravar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        this.gravarRegistro();
        this.dispose();
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
      limpaDados();
      this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        limpaDados();
    }//GEN-LAST:event_formWindowClosing

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void txtIdParceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdParceiroActionPerformed
       this.buscaParceiro();
       
    }//GEN-LAST:event_txtIdParceiroActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(clsaux.capturaValores(lbTroco.getText())>0.00){
            this.calculaValoresFinanceiro();
        }else{
            JOptionPane.showMessageDialog(null, "Valor Total Já Informado!!!");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtDescTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescTotalActionPerformed
      this.calculaDescontos();
    }//GEN-LAST:event_txtDescTotalActionPerformed

    private void txtDescTotalPercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescTotalPercActionPerformed
        Double descCalc=clsaux.capturaValores(lbVlItens.getText())*clsaux.capturaValores(txtDescTotalPerc.getText())/100;
        txtDescTotal.setText(clsaux.formato(descCalc));
        this.calculaDescontos();
    }//GEN-LAST:event_txtDescTotalPercActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
       chamaNovoItem();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
       this.chamaAlterarItem();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        cancelarItemLancado();
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
     txtCnpj.requestFocus();
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjActionPerformed
       txtFone.requestFocus();
    }//GEN-LAST:event_txtCnpjActionPerformed

    private void txtFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoneActionPerformed
        btnIncluir.requestFocus();
    }//GEN-LAST:event_txtFoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      Cadclientes.Origem="Pedido";
      Cadclientes dialog = new Cadclientes(new javax.swing.JFrame(), true);
      dialog.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
        frmCadOrcamento.chamaBuscaParceiro();
    }//GEN-LAST:event_btnPesqActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
       removeValores();
    }//GEN-LAST:event_btnRemoverActionPerformed
    public void inicia(){
        InputMap imp= this.getRootPane().getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW);
        imp.put(KeyStroke.getKeyStroke(KeyEvent.VK_F10,0),"busca");
        imp.put(KeyStroke.getKeyStroke(KeyEvent.VK_F1,0),"novo");
        imp.put(KeyStroke.getKeyStroke(KeyEvent.VK_F6,0),"salva");
        this.getRootPane().setInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW, imp);
        this.getRootPane().getActionMap().put("busca", new AbstractAction(){
            public void actionPerformed(ActionEvent ev){
                    frmCadOrcamento.chamaBuscaParceiro();
                  
            }
        });
         this.getRootPane().getActionMap().put("novo", new AbstractAction(){
            public void actionPerformed(ActionEvent ev){
                  chamaNovoItem();

            }
        });
          this.getRootPane().getActionMap().put("salva", new AbstractAction(){
            public void actionPerformed(ActionEvent ev){
                  gravarRegistro();
                  dispose();
            }
        });
        txtDataLanc.setText(clsaux.preencheData());
        DefaultComboBoxModel cbe=new DefaultComboBoxModel (ContasReceberDAO.estadoTituloParaDoc().toArray());
        cbEstado.setModel(cbe);
        DefaultComboBoxModel cbv=new DefaultComboBoxModel (ContasReceberDAO.vendedor().toArray());
        cbVendedor.setModel(cbv);
         this.carregaInfFinanceiro();
        if (tipoform.equals("I")){
            this.novoRegistro();
        } else if(tipoform.equals("A")){
            this.buscaCabecalho();
            this.buscaItens();
            this.buscaInfFinanceira();
        }
        tblParcelas.getColumnModel().getColumn(0).setCellEditor(validaDataTabela.validaDataDiaMesAno());
        txtIdParceiro.requestFocus();
    }
    public static void chamaBuscaParceiro(){
            formProcuraCliente dialog = new formProcuraCliente(new javax.swing.JFrame(), true);
            formProcuraCliente.idform="10";
            dialog.setVisible(true);
    }
   
    public void chamaNovoItem(){
        frmCadOrcamentoItem.tipoform="I";
        iditem++;
        frmCadOrcamentoItem.idItemBase=String.valueOf(iditem);
        frmCadOrcamentoItem dialog = new frmCadOrcamentoItem(new javax.swing.JFrame(), true);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    
    }
    public void chamaAlterarItem(){
         frmCadOrcamentoItem.tipoform="A";
         frmCadOrcamentoItem.orcamentoItem=itens.get(tbProd.getSelectedRow());
         frmCadOrcamentoItem.indiceitemTabela=tbProd.getSelectedRow();
         frmCadOrcamentoItem dialog = new frmCadOrcamentoItem(new javax.swing.JFrame(), true);
         dialog.setLocationRelativeTo(null);
         dialog.setVisible(true);
    
    }
    public void novoRegistro(){
        orcamentoDAO lt= new orcamentoDAO();
        String idmovimento=lt.inserirRegistro(orcamento);
        txtIdMov.setText(idmovimento);
        idregistro=idmovimento;
        iditem=0;
        orcamento.setId(idmovimento);
    }
    public void gravarRegistro(){
        orcamentoDAO orc= new orcamentoDAO();
        atualizaInfClasse();
        orc.atualizaRegistro(orcamento);
        for(clsOrcamentoItem ite: itens){
            orc.inserirItem(ite);
        }
        this.inserirFinalizadoras();
        JOptionPane.showMessageDialog(null, "Registro Gravado com sucesso");
        iditem=0;
        limpaDados();
        if(clsaux.retornaId(cbTipo.getSelectedItem()).equals("1")){
            this.finalizarRegistro();
        }else{
            CRUDOrcamentos.ultimoPedido=idregistro;
            CRUDOrcamentos.btnLocalizar.requestFocus();
        }
        
        
    }
    
    public void finalizarRegistro(){
        orcamentoDAO os= new orcamentoDAO();
        orcamento.setId(txtIdMov.getText());
        orcamento=os.buscarCabecalho(orcamento);
        String desc= clsaux.capturaValor(txtDescTotal.getText());
        int reg= tblParcelas.getRowCount();
        String vlfina,idfina=null;
        lancDocumentDAO documentDAO = new lancDocumentDAO();
        String parceiro=txtIdParceiro.getText();
        if(parceiro==null||parceiro.equals(""))parceiro="0";
        String mvtogerado=documentDAO.gerarVendaApartirLancamento("Pedido", txtIdMov.getText(), "99", "2", parceiro,"3",desc);
        for (int i=0; i<reg; i++){
            idfina=clsaux.retornaId(tblParcelas.getValueAt(i, 2).toString());
            vlfina= clsaux.formatoNfe(clsaux.capturaValores(tblParcelas.getValueAt(i, 1).toString())-clsaux.capturaValores(tblParcelas.getValueAt(i, 4).toString()));
            String datavenc=tblParcelas.getValueAt(i, 0).toString();
            os.inserirFinalizadora(txtIdMov.getText(), idfina, vlfina,tblParcelas.getValueAt(i, 3).toString(),datavenc);
            System.out.println(vlfina);
            if (Integer.parseInt(idfina)<4||Integer.parseInt(idfina)>6){
                this.gravaMovtoPagVista(vlfina, idfina,mvtogerado,txtIdMov.getText(),parceiro);
            }else if (Integer.parseInt(idfina)>3||Integer.parseInt(idfina)<7){
                this.gravaMovtoPagPrazo(vlfina, idfina,datavenc,mvtogerado,parceiro);
            }
        }
        
        
        String total=lbValorTotal.getText().replaceAll(",", ".");
        orcamento.setEstado("2");
        os.atualizaRegistro(orcamento);
        os.inserirFinalizadoraVendaFinalizada(orcamento.getId(),mvtogerado);
        
        int y=JOptionPane.showConfirmDialog(null, "Deseja Gerar Uma NFe Referente a Venda?", "Gerar Nfe",JOptionPane.YES_NO_OPTION);
        if (y==JOptionPane.YES_OPTION){
           this.gerarNfe(mvtogerado);
           };
         y=JOptionPane.showConfirmDialog(null, "Deseja Imprimir o Pedido?", "Impressão Pedido",JOptionPane.YES_NO_OPTION);
        if (y==JOptionPane.YES_OPTION){
           CRUDOrcamentos.imprimirOrcamento(orcamento.getId());
           };
    }
    
    public void gerarNfe(String mvto){
       clsNfe nf = new clsNfe();
       nf.setId_movimento(mvto);
       nf.setCstat("0");
       nf.setConsfinal("1");
       nf.setFinalidade("1");
       nf.setInddest("1");
       nf.setIndie("1");
       nf.setPrescomp("1");
       nf.setConsfinal("N");
       nfeDAO.gerarNfePartirVenda(nf);
       clsNfTransporte tr= new clsNfTransporte();
       tr.setIdmovimento(mvto);
       tr.setModfrete("9");
       nfeDAO.inserirAtualizaTransporteNf(tr);
       
       CRUDNfe.carregaAutomatico="S";
       CRUDNfe dialog = new CRUDNfe(new javax.swing.JFrame(), true);
       dialog.setLocationRelativeTo(null);
       dialog.setVisible(true);
    
    }
    
     public void gravaMovtoPagVista(String valor,String idfin,String mvt,String origem,String parc){
        MovimentoContaDAO mc= new MovimentoContaDAO();
        CadDocMovConta cadmc= new CadDocMovConta();
        cadmc.setIdconta("1");
        cadmc.setIdparceiro(parc);
        cadmc.setN_doc("");
        cadmc.setData_lancamento(clsaux.retornaData(clsaux.preencheData()));
        cadmc.setTipo_mov(clsConfig.financeiro.getTpPedido());
        cadmc.setSubtipo_mov(clsConfig.financeiro.getSbPediso());
        cadmc.setEntrada(valor);
        cadmc.setSaida("0.00");
        cadmc.setData_venc("");
        cadmc.setIdfinalizadora(idfin);
        cadmc.setObservacao("Rec. Ref. A Pedido : "+origem);
        cadmc.setDesc_mov("movimentacao automatica referente a Pedido : "+origem);
        cadmc.setIdmov(mvt);
        mc.inserir(cadmc);
        
        
        //mc.inserirPorRecebimentoTitulo(1, "1", "14", valor, idfin, "E", pagamento.getParceiro(),"Rec. Ref. "+pagamento.getTipo());
        
       
    }
    public void gravaMovtoPagPrazo(String valor,String idfin, String datavencimento,String mvto,String parc){
        CadContasRecPagar cd = new CadContasRecPagar();
        ContasReceberDAO cr = new ContasReceberDAO();
        cd.setIdmovto(mvto);
        cd.setParceiro(parc);
        cd.setValor(valor);
        cd.setNumero(txtIdMov.getText());
        cd.setEmisao(clsaux.retornaData(clsaux.preencheData()));
        cd.setVencimento(clsaux.retornaData(datavencimento));
        cd.setEstadotitulo("4");
        cd.setTipo_titulo(idfin);
        cd.setConta("1");
        cd.setHistorico("10");
        cd.setTipo("2");
        cd.setIdcontrato("0");
        cd.setBanco("1");
        cd.setVendedor("0");
        cd.setParcela("1");
        cd.setJuros("0.00");
        cd.setDesconto("0.00");
        cd.setSaldo(valor);
        cd.setTipofinanceiro(clsConfig.financeiro.getTpPedido());
        cd.setSubtipofinanceiro(clsConfig.financeiro.getSbPediso());
        cd.setQntParcelas("1");
        cr.inserir(cd);
    }
    public void inserirFinalizadoras(){
        orcamentoDAO orcdao= new orcamentoDAO();
        for(int i=0; i<tblParcelas.getRowCount();i++){
                orcdao.inserirFinalizadora(txtIdMov.getText(), 
                        clsaux.retornaId(tblParcelas.getValueAt(i, 2).toString()),
                        clsaux.capturaValor(tblParcelas.getValueAt(i, 1).toString()),
                        tblParcelas.getValueAt(i, 3).toString(),
                        tblParcelas.getValueAt(i, 0).toString());
        
        }
    }
    public void buscaParceiro(){
        if(clsaux.verificaNulo(txtIdParceiro.getText())==true){
            
        }else{
            clientes cli= new clientes();
            cli= clienteDAO.buscar("null", cli, txtIdParceiro.getText());
            txtCnpj.setText(cli.getCnpj());
            txtNome.setText(cli.getRazaoSocial());
            txtFone.setText(cli.getFone());
            btnIncluir.requestFocus();
            }
    }
    public void limpaDados(){
        itens.clear();
        orcamento= new clsOrcamento();
        iditem=0;
    }
    public void cancelarItemLancado(){
        int yn= JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o registro selecionado?", "exclusão de registro", JOptionPane.YES_NO_OPTION);
        if (yn== JOptionPane.YES_OPTION){
                int indiceitem=tbProd.getSelectedRow();
                itens.get(indiceitem).setEstado("3");
                orcdao.inserirItem(itens.get(indiceitem));
                itens.remove(indiceitem);
                preencherTabela();
                calculaTotais();
        }
    
    }
    
    public void buscaCabecalho(){
        orcamento.setId(idregistro);
        orcamento=orcdao.buscarCabecalho(orcamento);
        txtIdMov.setText(orcamento.getId());
        txtIdParceiro.setText(orcamento.getParceiro());
        txtCnpj.setText(orcamento.getParceiro_cpf());
        txtNome.setText(orcamento.getParceiro_nome());
        txtFone.setText(orcamento.getParceiro_telefone());
        txtObs.setText(orcamento.getObs());
        txtDataLanc.setText(clsaux.convertDataExib(orcamento.getData_lancamento().toString()));
        lbVlItens.setText(clsaux.formato(orcamento.getSubtotal()));
        lbVlAcre.setText(clsaux.formato(orcamento.getAcrescimo()));
        lbVlDesc.setText(clsaux.formato(orcamento.getDesconto()));
        lbValorTotal.setText(clsaux.formato(orcamento.getTotal()));
        clsaux.carregaComboBox(cbEstado, orcamento.getEstado());
        clsaux.carregaComboBox(cbVendedor, orcamento.getVendedor());
        clsaux.carregaComboBox(cbTipo, orcamento.getTipo());
       
    }
    public void buscaItens(){
        orcamentoDAO orc= new orcamentoDAO();
        itens=orc.buscaItens(orcamento.getId());
        iditem= Integer.parseInt(itens.get(itens.size()-1).getIditem());
        
        preencherTabela();
    
    }
    public void buscaInfFinanceira(){
        orcamentoDAO dao= new orcamentoDAO();
        List<clsPagamentos> lista= dao.retornaListaPagamentoPedidoOrcamento(orcamento.getId());
        DefaultTableModel tb= (DefaultTableModel) tblParcelas.getModel();
        Double vlpg=0.00;
        for(clsPagamentos novo:lista){
            tb.addRow(new Object []{
                clsaux.convertDataExib(novo.getDataemissao()),
                novo.getValor(),
                novo.getIdfinalizadora(),
                novo.getParcela()
            });
            vlpg=vlpg+clsaux.capturaValores(novo.getValor());
        }
        
        //vlpg=clsaux.capturaValores(lbValorTotal.getText())-vlpg;
        lbTroco.setText(clsaux.formato(clsaux.capturaValores(lbValorTotal.getText())-vlpg));
        txtvalor.setText(lbTroco.getText());
    }
    public static void preencherTabela(){
        DefaultTableModel tb = (DefaultTableModel) frmCadOrcamento.tbProd.getModel();
        tb.setNumRows(0);
        for (int i=0; i<itens.size(); i++){
            tb.addRow(new Object[]{
            itens.get(i).getIditem(),
            itens.get(i).getCodibarra(),
            itens.get(i).getDescricao(),
            clsaux.formato(itens.get(i).getQnt()),
            clsaux.formato(itens.get(i).getUnitario()),
            clsaux.formato(itens.get(i).getTotal()),
        });
         
        }
      }
    public static void calculaTotais(){
        Double vlitem=0.00,vldesc=0.00,vlacres=0.00,vltotal=0.00;
        for(int i=0; i<itens.size();i++){
            vlitem=vlitem+itens.get(i).getSubtotal();
            vldesc=vldesc+itens.get(i).getDesc();
            vlacres=vlacres+itens.get(i).getAcres();
            vltotal=vltotal+itens.get(i).getTotal();
        }
        lbVlItens.setText(clsaux.formato(vlitem));
        lbVlAcre.setText(clsaux.formato(vlacres));
        lbVlDesc.setText(clsaux.formato(vldesc));
        lbValorTotal.setText(clsaux.formato(vltotal));
        orcamento.setAcrescimo(vlacres);
        orcamento.setDesconto(vldesc);
        orcamento.setSubtotal(vlitem);
        orcamento.setTotal(vltotal);
        orcamentoDAO orc= new orcamentoDAO();
        orc.atualizaRegistro(orcamento);
        
        // funcao atualizar cabecalho documento
        txtvalor.setText(lbValorTotal.getText());
        lbTroco.setText(lbValorTotal.getText());
    }
    public static void atualizaInfClasse(){
        orcamento.setData_lancamento(clsaux.retornaData(txtDataLanc.getText()));
        orcamento.setEstado("1");
        orcamento.setParceiro(txtIdParceiro.getText());
        orcamento.setParceiro_cpf(txtCnpj.getText());
        orcamento.setParceiro_nome(txtNome.getText());
        orcamento.setParceiro_telefone(txtFone.getText());
        orcamento.setVendedor(clsaux.retornaId(cbVendedor.getSelectedItem().toString()));
        orcamento.setTipo(clsaux.retornaId(cbTipo.getSelectedItem().toString()));
        orcamento.setObs(txtObs.getText());
        if(orcamento.getParceiro()==null){
            orcamento.setParceiro("0");
        }
    
    }
    public void carregaInfFinanceiro(){
        DefaultComboBoxModel tbfi= new DefaultComboBoxModel(listaDAO.listapagamento().toArray());
        CbFinalizadora.setModel(tbfi);
        txtvalor.setText(lbValorTotal.getText());
        lbTroco.setText(lbValorTotal.getText());
    }
   
    public void calculaDescontos(){
        Double valor=0.00;
        Double perc=0.00;
        Double vlItens=0.00;
        Double valorItem=0.00;
        vlItens=clsaux.capturaValores(lbVlItens.getText());
        valor=clsaux.capturaValores(txtDescTotal.getText());
        perc=valor*100/vlItens;
        if (valor>vlItens||perc>100){
            JOptionPane.showMessageDialog(null, "Valor de Desconto Informado Invalido!!!", "Desconto Não permitido", HEIGHT);
             valor=0.00;
             perc=0.00;
        }else{
            for(clsOrcamentoItem it: itens){
                valorItem=it.getSubtotal()*perc/100.0;
                if(valor>=valorItem){
                 it.setDesc(valorItem);
                 valor=valor-valorItem;
              }else{
               it.setDesc(valor);
            }
               it.setTotal(it.getSubtotal()-it.getDesc());
           }
        }
        calculaTotais();
    }
    public void calculaValoresFinanceiro(){
        
        String idfinalizadora=clsaux.retornaId(CbFinalizadora.getSelectedItem().toString());
        String nomefinalizadora=clsaux.retornaAposId(CbFinalizadora.getSelectedItem().toString());
        int parcela=Integer.parseInt(CbParcelas.getSelectedItem().toString());
        Double valor= clsaux.capturaValores(txtvalor.getText());
        Double totalgeral=clsaux.capturaValores(lbValorTotal.getText());
        Double falta=clsaux.capturaValores(lbTroco.getText());
        Double troco=0.00;
        Double valorgeral=valor;
        if(idfinalizadora.equals("1")||valor>falta){
            troco=valor-falta;
        }
        DefaultTableModel tbl = (DefaultTableModel) tblParcelas.getModel();
        //tbl.setNumRows(0);
        if (parcela==1){
            tbl.addRow(new Object[]{
                clsaux.preencheData(),
                clsaux.formato(valor),
                idfinalizadora+"-"+nomefinalizadora,
                parcela,
                clsaux.formato(troco)
                });
        }else if (parcela > 1){
           
            valor= valor/parcela;
            valor= clsaux.capturaValores(clsaux.formato(valor));
            for (int i=1; i<=parcela; i++){
                if(i==parcela){
                    valor=valorgeral;
                }
                tbl.addRow(new Object []{
                    clsaux.calcularDataVencimento(i*30),
                    clsaux.formato(valor),
                    idfinalizadora+"-"+nomefinalizadora,
                    i,
                    "0,00"
                });
                valorgeral=valorgeral-valor;
            }
        }
        lbTroco.setText(clsaux.formato((totalgeral-valorgeral)));
     
        txtvalor.setText("");
        
    }
    public void removeValores(){
        DefaultTableModel tbl = (DefaultTableModel) tblParcelas.getModel();
        tbl.setNumRows(0);
        lbTroco.setText(lbValorTotal.getText());
        txtvalor.setText("");
        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCadOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCadOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCadOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCadOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCadOrcamento dialog = new frmCadOrcamento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbFinalizadora;
    private javax.swing.JComboBox<String> CbParcelas;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnPesq;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> cbEstado;
    private static javax.swing.JComboBox<String> cbTipo;
    protected static javax.swing.JComboBox<String> cbVendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private static javax.swing.JLabel lbTroco;
    private static javax.swing.JLabel lbValorTotal;
    private static javax.swing.JLabel lbVlAcre;
    private static javax.swing.JLabel lbVlDesc;
    private static javax.swing.JLabel lbVlItens;
    public static javax.swing.JTable tbProd;
    private javax.swing.JTable tblParcelas;
    public static javax.swing.JTextField txtCnpj;
    private static javax.swing.JFormattedTextField txtDataLanc;
    private static javax.swing.JTextField txtDescTotal;
    private static javax.swing.JTextField txtDescTotalPerc;
    public static javax.swing.JTextField txtFone;
    private javax.swing.JTextField txtIdMov;
    public static javax.swing.JTextField txtIdParceiro;
    public static javax.swing.JTextField txtNome;
    private static javax.swing.JTextArea txtObs;
    private static javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
