/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic.interfac;

import DAO.balancaDAO;
import DAO.listaInfAdcDAO;
import model.clsBalanca;
import classes.clsaux;
import conexoes.conexao;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.apache.commons.lang3.StringUtils;

/**
 *
 * @author Mk Solucoes
 */
public class frmEnvioCargaBalanca extends javax.swing.JDialog {

    /**
     * Creates new form frmEnvioCargaBalanca
     */
    
    
    
    String produtos="";
    public frmEnvioCargaBalanca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregaDados();
    }

    public void carregaDados(){
      DefaultComboBoxModel dfBalanca = new DefaultComboBoxModel(listaInfAdcDAO.retornaBalanca().toArray());
      cbBalanca.setModel(dfBalanca);
      cbBalanca.setSelectedIndex(1);
      
    
    }
    
    public void dadosBalanca(){
        clsBalanca bal= new clsBalanca();
        bal.setCod(clsaux.retornaId(cbBalanca.getSelectedItem().toString()));
        bal=balancaDAO.retornaBalanca(bal);
        txtcaminho.setText(bal.getCaminho());
    }
    public void buscaItensExportar(){
        try {
            String sql="select iif(char_length(tp.nomecurto)>25, substring(tp.nomecurto from 1 for 24), cast ((tp.nomecurto) as varchar(25))), \n" +
                    "        tb.codigo_barras,\n" +
                    "        tb.dias_validade,\n" +
                    "        tb.pesavel,\n" +
                    "       cast ((tc.preco_venda) as numeric(6,2))\n" +
                    " from tbarras tb\n" +
                    " join tprodutos tp on tp.id=tb.id_produto\n" +
                    " join tprecos tc on tp.id=tc.id\n" +
                    " where tb.id_balanca>0";
            PreparedStatement ps = conexao.getPreparedStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
                this.montaLinhaProduto(rs.getInt(2), rs.getString(1), rs.getString(5), rs.getInt(3), rs.getString(4));
            
            }
            gravarArquivo();
        } catch (SQLException ex) {
            Logger.getLogger(frmEnvioCargaBalanca.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    
    }
    
    public void montaLinhaProduto(int codigo,String descricao,String preco,int diasvalidade,String pesavel){
        String prod="";
        if(pesavel.equals("Sim")){
            pesavel="0";
        }else{
            pesavel="1";
        }
        String codig=String.format("%06d", codigo);
        String prec=String.format("%06d", Integer.parseInt(preco.replace(".", "")));
        String val=String.format("%03d", diasvalidade);
        descricao= StringUtils.rightPad(descricao, 25, "");
        String descritivo2=StringUtils.leftPad("", 25, "");
        String descritivo3=StringUtils.leftPad("", 35, "");
        String descritivo4=StringUtils.leftPad("", 35, "");        
        prod="01"+pesavel+codig+ prec+val+descricao+descritivo2+"0000000000000000110000000000000000000000000000000000000000000000000000000000000000000000|01|"+descritivo3
                +descritivo4+"000000000000000000"+prec+"0||0|| \n";
        
        //produto.add(prod);
        produtos=produtos+prod;
    
    }
    
    public void gravarArquivo(){
        FileWriter arq=null;
        try {
            String chavenfe=txtcaminho.getText();
            arq = new FileWriter(chavenfe);
            PrintWriter gravarArq = new PrintWriter(arq);
            gravarArq.printf(produtos);
            arq.close();
            JOptionPane.showMessageDialog(null, "Arquivo Gerado Com Sucesso!!!");
            this.dispose();
        } catch (IOException ex) {
            Logger.getLogger(frmEnvioCargaBalanca.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao gerar arquivo \n" +ex.getMessage());
        } finally {
            
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEnviar = new javax.swing.JButton();
        txtcaminho = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbBalanca = new javax.swing.JComboBox<>();
        rbTodos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exportação Balança");

        jPanel1.setBackground(new java.awt.Color(219, 227, 227));

        btnEnviar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEnviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtcaminho.setEditable(false);
        txtcaminho.setText("c:\\toledo\\Itensmgv.txt");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Caminho:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Balanças:");

        cbBalanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBalancaActionPerformed(evt);
            }
        });

        rbTodos.setBackground(new java.awt.Color(219, 227, 227));
        rbTodos.setSelected(true);
        rbTodos.setText("Todos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcaminho, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(btnEnviar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBalanca, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbTodos)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbBalanca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbTodos))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtcaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEnviar)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbBalancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBalancaActionPerformed
        this.dadosBalanca();
    }//GEN-LAST:event_cbBalancaActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
       this.buscaItensExportar();
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEnvioCargaBalanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEnvioCargaBalanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEnvioCargaBalanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEnvioCargaBalanca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmEnvioCargaBalanca dialog = new frmEnvioCargaBalanca(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> cbBalanca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JTextField txtcaminho;
    // End of variables declaration//GEN-END:variables
}
