/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic.interfac;

import grafic.interfac.pesquisa.localizaProduto;
import DAO.custosDAO;
import DAO.lancDocumentDAO;
import DAO.listaInfAdcDAO;
import classes.ClsParametrizaTributos;
import model.Cst;
import model.clsLancDocument;
import model.clsPisCofins;
import classes.clsaux;
import com.sun.glass.events.KeyEvent;
import conexoes.conexao;
import java.awt.event.ActionEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.DefaultComboBoxModel;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import model.clsNfe;
import util.validaDigitosBarras;

/**
 *
 * @author Rodrigo
 */
public class frmLancamentoItemNfe extends javax.swing.JDialog {

    /**
     * Creates new form LancamentoItemDocumento
     */
    public frmLancamentoItemNfe(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.inicializa();
    }
     String iditem=null;
     public static String estadoform="O";
     public static int linha=-1;
     public static clsLancDocument item= new clsLancDocument();
     clsNfe nf= new clsNfe();
     String direcao="";
     public void inicializa(){
        DefaultComboBoxModel dfunidc= new DefaultComboBoxModel(listaInfAdcDAO.pegaUnid().toArray());
        cbUnidvenda.setModel(dfunidc);
        InputMap imp= this.getRootPane().getInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW);
        imp.put(KeyStroke.getKeyStroke(KeyEvent.VK_F10,0),"busca_item");
        this.getRootPane().setInputMap(JPanel.WHEN_IN_FOCUSED_WINDOW, imp);
        this.getRootPane().getActionMap().put("busca_item", new AbstractAction(){
            public void actionPerformed(ActionEvent ev){
                localizaProduto dialog = new localizaProduto(new javax.swing.JFrame(), true); 
                localizaProduto.idchamado="5";
                dialog.setVisible(true);
            }
        });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodBarras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNomeproduto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbUnidvenda = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtIditem = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtcst = new javax.swing.JTextField();
        txtdesccst = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtcfop = new javax.swing.JTextField();
        btnPesq = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btnGravar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtQnt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAcresc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtValorunitario = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtValortotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFator = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtvlfrete = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtvlseguro = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtvloutras = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtncm = new javax.swing.JTextField();
        txtcest = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtcbenef = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtredicms = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtbaseicms = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtvlicms = new javax.swing.JTextField();
        cbmodbc = new javax.swing.JComboBox<>();
        txtaliqicms = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txtdesoneracaoicms = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        txtbasest = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        txtvlst = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtcstpis = new javax.swing.JTextField();
        txtdescpis = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txtbasepis = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txtaliqpis = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txtaliqcofins = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txtvlpis = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        txtvlcofins = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        txtcstipi = new javax.swing.JTextField();
        txtdescipi = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtbaseipi = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtaliqipi = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        txtvlipi = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editando Lançamento");
        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(219, 227, 227));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Barras :");

        txtCodBarras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCodBarras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodBarrasFocusLost(evt);
            }
        });
        txtCodBarras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodBarrasActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Nome :");

        txtNomeproduto.setEditable(false);
        txtNomeproduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Venda :");

        cbUnidvenda.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Id Item:");

        txtIditem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIditem.setEnabled(false);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel22.setText("CST:");

        txtcst.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcst.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtdesccst.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdesccst.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel23.setText("CFOP:");

        txtcfop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcfop.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        btnPesq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procura.png"))); // NOI18N
        btnPesq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesqActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbUnidvenda, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIditem, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNomeproduto)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcst, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtdesccst, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcfop)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbUnidvenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(txtIditem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(btnPesq, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNomeproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtcst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdesccst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtcfop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));

        btnGravar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancela.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnGravar, jButton2});

        jPanel7.setBackground(new java.awt.Color(219, 227, 227));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Qtde:");

        txtQnt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtQnt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtQnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQntActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Acresc :");

        txtAcresc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAcresc.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAcresc.setText("0,00");
        txtAcresc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAcrescFocusLost(evt);
            }
        });
        txtAcresc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcrescActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Desc. :");

        txtDesconto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDesconto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtDesconto.setText("0,00");
        txtDesconto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescontoFocusLost(evt);
            }
        });
        txtDesconto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescontoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Unitario :");

        txtValorunitario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtValorunitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtValorunitario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorunitarioFocusLost(evt);
            }
        });
        txtValorunitario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorunitarioActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Total :");

        txtValortotal.setEditable(false);
        txtValortotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtValortotal.setForeground(new java.awt.Color(102, 0, 0));
        txtValortotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Fator :");

        txtFator.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setText("Vl Frete:");

        txtvlfrete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtvlfrete.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtvlfrete.setText("0,00");
        txtvlfrete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtvlfreteFocusLost(evt);
            }
        });
        txtvlfrete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvlfreteActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setText("Seguro:");

        txtvlseguro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtvlseguro.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtvlseguro.setText("0,00");
        txtvlseguro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtvlseguroFocusLost(evt);
            }
        });
        txtvlseguro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvlseguroActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setText("Outras:");

        txtvloutras.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtvloutras.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtvloutras.setText("0,00");
        txtvloutras.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtvloutrasFocusLost(evt);
            }
        });
        txtvloutras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvloutrasActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setText("NCM:");

        txtncm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtncm.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtcest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcest.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setText("CEST:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel21.setText("CBenef:");

        txtcbenef.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcbenef.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addComponent(jLabel18))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jLabel17))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel9)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorunitario, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFator, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvloutras, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvlseguro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAcresc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtValortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcbenef, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtncm, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcest, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtvlfrete, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(256, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAcresc, txtDesconto, txtFator, txtQnt, txtValortotal, txtValorunitario, txtcbenef, txtvlfrete, txtvloutras, txtvlseguro});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtQnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txtncm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtValorunitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtFator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(txtcbenef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValortotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtvloutras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtvlfrete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtvlseguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAcresc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Informações", jPanel7);

        jPanel8.setBackground(new java.awt.Color(219, 227, 227));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), null));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel25.setText("Mod BC:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel27.setText("Red. BC:");

        txtredicms.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel31.setText("Aliq:");

        txtbaseicms.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtbaseicms.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel32.setText("BC Icms:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel33.setText("VL Icms:");

        txtvlicms.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtvlicms.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cbmodbc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbmodbc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0- Margem Valor Agregado", "1- Pauta", "2- Preço Tabelado Max", "3- Valor Da Operação" }));
        cbmodbc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbmodbcActionPerformed(evt);
            }
        });

        txtaliqicms.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtaliqicms.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel35.setText("Des:");

        txtdesoneracaoicms.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdesoneracaoicms.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel36.setText("BC ST:");

        txtbasest.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtbasest.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel37.setText("Vl ST:");

        txtvlst.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtvlst.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setText("Pis/Cofins:");

        txtcstpis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcstpis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtdescpis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdescpis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setText("Base:");

        txtbasepis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtbasepis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel40.setText("Aliq. Pis:");

        txtaliqpis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtaliqpis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtaliqpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaliqpisActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel41.setText("Aliq. Cofins:");

        txtaliqcofins.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtaliqcofins.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtaliqcofins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaliqcofinsActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setText("Vl Pis:");

        txtvlpis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtvlpis.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtvlpis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvlpisActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setText("Vl Cofins:");

        txtvlcofins.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtvlcofins.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtvlcofins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvlcofinsActionPerformed(evt);
            }
        });

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setText("IPI Cst:");

        txtcstipi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcstipi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtdescipi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdescipi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setText("Base:");

        txtbaseipi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtbaseipi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setText("Aliq. IPI:");

        txtaliqipi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtaliqipi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtaliqipi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaliqipiActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel48.setText("Substituição Tributaria");

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel49.setText("IPI");

        jLabel50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel50.setText("Valor:");

        txtvlipi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtvlipi.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbmodbc, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtredicms, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbaseicms, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtvlicms, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtaliqicms)
                                    .addComponent(txtdesoneracaoicms))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel38)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtaliqpis, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(txtvlpis)
                                    .addComponent(txtbasepis))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(jLabel41)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtaliqcofins, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel43)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtvlcofins))))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(txtcstpis, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtdescpis)))
                        .addGap(108, 108, 108))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtvlst, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbasest, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel44, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtvlipi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtbaseipi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtcstipi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtdescipi, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtaliqipi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(jLabel25)
                            .addComponent(cbmodbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel27)
                            .addComponent(txtredicms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(29, 29, 29))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtbaseicms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32)
                                    .addComponent(txtaliqicms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtvlicms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33)
                                    .addComponent(txtdesoneracaoicms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel35)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcstpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdescpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbasepis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtaliqpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel41)
                            .addComponent(txtaliqcofins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtvlpis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43)
                            .addComponent(txtvlcofins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))))
                .addGap(47, 47, 47)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbasest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtvlst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcstipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44)
                            .addComponent(txtdescipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtbaseipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtvlipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50)
                            .addComponent(txtaliqipi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Impostos", jPanel8);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addGap(13, 13, 13)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        linha=-1;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtCodBarrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodBarrasActionPerformed
       this.pegaItem(validaDigitosBarras.preencheCodigo(txtCodBarras.getText()));
    }//GEN-LAST:event_txtCodBarrasActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
       this.gravaItem();
    }//GEN-LAST:event_btnGravarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       if (estadoform.equals("A")){
           this.alteraItem();
       } else {
           //txtIditem.setText(String.valueOf(frmLancamentoNfe.numeitem));
           this.alteraItem();
    }
    }//GEN-LAST:event_formComponentShown

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        linha=-1;
    }//GEN-LAST:event_formWindowClosed

    private void cbmodbcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbmodbcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbmodbcActionPerformed

    private void txtaliqpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaliqpisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaliqpisActionPerformed

    private void txtaliqcofinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaliqcofinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaliqcofinsActionPerformed

    private void txtvlpisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvlpisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvlpisActionPerformed

    private void txtvlcofinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvlcofinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvlcofinsActionPerformed

    private void txtaliqipiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaliqipiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaliqipiActionPerformed

    private void txtCodBarrasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodBarrasFocusLost
         //this.pegaItem(txtCodBarras.getText());
    }//GEN-LAST:event_txtCodBarrasFocusLost

    private void txtvloutrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvloutrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvloutrasActionPerformed

    private void txtvloutrasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvloutrasFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvloutrasFocusLost

    private void txtvlseguroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvlseguroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvlseguroActionPerformed

    private void txtvlseguroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvlseguroFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvlseguroFocusLost

    private void txtvlfreteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvlfreteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvlfreteActionPerformed

    private void txtvlfreteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtvlfreteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtvlfreteFocusLost

    private void txtValorunitarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorunitarioActionPerformed
        btnGravar.requestFocus();
    }//GEN-LAST:event_txtValorunitarioActionPerformed

    private void txtValorunitarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorunitarioFocusLost
        this.calculaTotal();
    }//GEN-LAST:event_txtValorunitarioFocusLost

    private void txtDescontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescontoActionPerformed
        this.calculaTotal();
    }//GEN-LAST:event_txtDescontoActionPerformed

    private void txtDescontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescontoFocusLost
        this.calculaTotal();
    }//GEN-LAST:event_txtDescontoFocusLost

    private void txtAcrescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcrescActionPerformed
        this.calculaTotal();
    }//GEN-LAST:event_txtAcrescActionPerformed

    private void txtAcrescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAcrescFocusLost
        this.calculaTotal();
    }//GEN-LAST:event_txtAcrescFocusLost

    private void txtQntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQntActionPerformed
        txtValorunitario.requestFocus();
    }//GEN-LAST:event_txtQntActionPerformed

    private void btnPesqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesqActionPerformed
       localizaProduto dialog = new localizaProduto(new javax.swing.JFrame(), true); 
                localizaProduto.idchamado="5";
                dialog.setVisible(true);
    }//GEN-LAST:event_btnPesqActionPerformed
    public void pegaItem(String codigobarra){
        String sqlitem="select   tp.id,\n" +
                        "        tp.nomelongo,\n" +
                        "        tp.unid_venda,\n" +
                        "        tb.codigo_barras,\n" +
                        "        tb.referencia,\n" +
                        "        tb.fator,\n" +
                        "        tc.preco_venda,\n" +
                        "        tc.ncm,\n" +
                        "        tc.sit_tributaria,tc.pis_saida\n" +
                        "        from tprodutos tp\n" +
                        "join tbarras tb on tp.id=tb.id_produto\n" +
                        "join tprecos tc on tp.id=tc.id\n" +
                        "where tb.codigo_barras=? and tp.excluido='N'";
        PreparedStatement psp= conexao.getPreparedStatementResult(sqlitem);
        try {
            psp.setString(1, codigobarra);
            ResultSet rsp= psp.executeQuery();
            rsp.first();
            iditem=rsp.getString(1);
            txtNomeproduto.setText(rsp.getString(2));
            txtFator.setText(rsp.getString(6));
            txtncm.setText(rsp.getString(8));
            txtcst.setText(rsp.getString(9));
            txtValorunitario.setText(clsaux.formato(rsp.getDouble(7)));
            cbUnidvenda.setSelectedItem(rsp.getString(3));
            txtcstpis.setText(rsp.getString(10));
            rsp.close();
            psp.close();
            this.carregaTributos();
            txtQnt.requestFocus();
        } catch (SQLException ex) {
            Logger.getLogger(frmLancamentoItemNfe.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Produto Não Encontrado");
            txtCodBarras.setText("");
        }
    
    }
    public void inicializa(clsNfe cl,String interno){
        this.nf=cl;
        if(interno.equals("3")||interno.equals("10")){
            this.direcao="E";
        }else{
            this.direcao="S";
        }
    }
    public void carregaTributos(){
        String cst=txtcst.getText().trim();
        txtcfop.setText(new ClsParametrizaTributos().parametricaCfopConformeCstNfe(cst, nf.getFinalidade(), direcao, nf.getInddest()));
        clsPisCofins pis=listaInfAdcDAO.retornaPis(txtcstpis.getText());
        txtdescpis.setText(pis.getDescricao());
        txtaliqpis.setText(pis.getAliq_pis());
        txtaliqcofins.setText(pis.getAliq_cofins());
        Cst cs=listaInfAdcDAO.retornaCst(cst);
        txtdesccst.setText(cs.GetDescricao());
    }
    public void calculaTotal(){
        Double qnt,vuni,vtotal,acres,desc,outras,seguro,frete,vlipi,vlst,vlicms=0.00;
        qnt=Double.parseDouble(txtQnt.getText().replaceAll(",","."));
        vuni=Double.parseDouble(txtValorunitario.getText().replaceAll(",", "."));
        acres=Double.parseDouble(txtAcresc.getText().replaceAll(",", "."));
        desc=Double.parseDouble(txtDesconto.getText().replaceAll(",", "."));
        outras=clsaux.capturaValores(txtvloutras.getText());
        seguro=clsaux.capturaValores(txtvlseguro.getText());
        frete=clsaux.capturaValores(txtvlfrete.getText());
        vlipi=clsaux.capturaValores(txtvlipi.getText());
        vlst=clsaux.capturaValores(txtvlst.getText());
        vlicms=clsaux.capturaValores(txtvlicms.getText());
        vtotal=qnt*vuni-desc+acres+outras+seguro+frete+vlipi;
        if(txtcst.getText().equals("10")){
            vtotal=vtotal+vlst;
        }
        txtValortotal.setText(clsaux.formato(vtotal));
    }
    public void gravaItem(){
        
        lancDocumentDAO ldDAO= new lancDocumentDAO();
        item.setIdmovto(frmLancamentoNfe.idmovimento);
        item.setIdproduto(iditem);
        item.setBarras(txtCodBarras.getText());
        item.setDescricaofornecedor(txtNomeproduto.getText());
        item.setQuantidade(txtQnt.getText().replaceAll(",", "."));
        item.setPrecovenda(txtValorunitario.getText().replaceAll(",", "."));
        item.setAcrescimo(txtAcresc.getText().replaceAll(",", "."));
        item.setDesconto(txtDesconto.getText().replaceAll(",", "."));
        item.setTotal(txtValortotal.getText().replaceAll(",", "."));
        item.setUnidade(cbUnidvenda.getSelectedItem().toString());
        item.setNumeroitem(txtIditem.getText());
        item.setValor_outras( txtvloutras.getText());
        item.setValor_frete(txtvlfrete.getText());
        item.setValor_seguro(txtvloutras.getText());
        item.setNcm(txtncm.getText());
        item.setCst(txtcst.getText());
        item.setRed_bc(clsaux.capturaValor(txtredicms.getText()));
        item.setBase_icms(clsaux.capturaValor(txtbaseicms.getText()));
        item.setValor_icms(clsaux.capturaValor(txtvlicms.getText()));
        item.setAliq_icms(clsaux.capturaValor(txtaliqicms.getText()));
        item.setBase_st(clsaux.capturaValor(txtbasest.getText()));
        item.setValor_st(clsaux.capturaValor(txtvlst.getText()));
        item.setPis_cofins(txtcstpis.getText());
        item.setBase_pis(clsaux.capturaValor(txtbasepis.getText()));
        item.setAliq_pis(clsaux.capturaValor(txtaliqpis.getText()));
        item.setAliq_cofins(clsaux.capturaValor(txtaliqcofins.getText()));
        item.setValor_pis(clsaux.capturaValor(txtvlpis.getText()));
        item.setValor_cofins(clsaux.capturaValor(txtvlcofins.getText()));
        item.setCstipi(txtcstipi.getText());
        item.setBase_ipi(clsaux.capturaValor(txtbaseipi.getText()));
        item.setAliq_ipi(clsaux.capturaValor(txtaliqipi.getText()));
        item.setValor_ipi(clsaux.capturaValor(txtvlipi.getText()));
        item.setCfop(txtcfop.getText());
        DefaultTableModel tb= (DefaultTableModel) frmLancamentoNfe.tbItens.getModel();
        if (estadoform.equals("A")){
          frmLancamentoNfe.itens.set(linha, item);
        } else {
           frmLancamentoNfe.itens.add(item);
        }
        iditem=null;
        frmLancamentoNfe.numeitem++;
        frmLancamentoNfe.populaTabelaItens();
        frmLancamentoNfe.calculaTotalDoc();
        this.dispose();
    }
    public void alteraItem(){
        txtCodBarras.setText(item.getBarras());
        txtNomeproduto.setText(item.getDescricaofornecedor());
        txtIditem.setText(item.getNumeroitem());
        txtQnt.setText(item.getQuantidade());
        txtValorunitario.setText(item.getPrecovenda());
        txtValortotal.setText(item.getTotal());
        cbUnidvenda.setSelectedItem(item.getUnidade());
        txtAcresc.setText(item.getAcrescimo());
        txtDesconto.setText(item.getDesconto());
        iditem=item.getIdproduto();
        txtvloutras.setText(clsaux.trataCampoNulo(item.getValor_outras()));
        txtvlseguro.setText(clsaux.trataCampoNulo(item.getValor_seguro()));
        txtvlfrete.setText(clsaux.trataCampoNulo(item.getValor_frete()));
        txtncm.setText(item.getNcm());
        txtcest.setText(item.getCest());
        txtcbenef.setText(item.getCbenef());
        txtcst.setText(item.getCst());
        txtredicms.setText(clsaux.trataCampoNulo(item.getRed_bc()));
        txtbaseicms.setText(clsaux.trataCampoNulo(item.getBase_icms()));
        txtvlicms.setText(clsaux.trataCampoNulo(item.getValor_icms()));
        txtaliqicms.setText(clsaux.trataCampoNulo(item.getAliq_icms()));
        txtbasest.setText(clsaux.trataCampoNulo(item.getBase_st()));
        txtvlst.setText(clsaux.trataCampoNulo(item.getValor_st()));
        txtcstpis.setText(item.getPis_cofins());
        txtbasepis.setText(clsaux.trataCampoNulo(item.getBase_pis()));
        txtaliqpis.setText(clsaux.trataCampoNulo(item.getAliq_pis()));
        txtaliqcofins.setText(clsaux.trataCampoNulo(item.getAliq_cofins()));
        txtvlpis.setText(clsaux.trataCampoNulo(item.getValor_pis()));
        txtvlcofins.setText(clsaux.trataCampoNulo(item.getValor_cofins()));
        txtcstipi.setText(clsaux.trataCampoNulo(item.getCstipi()));
        txtbaseipi.setText(clsaux.trataCampoNulo(item.getBase_ipi()));
        txtaliqipi.setText(clsaux.trataCampoNulo(item.getAliq_ipi()));
        txtvlipi.setText(clsaux.trataCampoNulo(item.getValor_ipi()));
        txtcfop.setText(item.getCfop());
        if(estadoform.equals("A"))carregaTributos();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLancamentoItemNfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLancamentoItemNfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLancamentoItemNfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLancamentoItemNfe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmLancamentoItemNfe dialog = new frmLancamentoItemNfe(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnPesq;
    private javax.swing.JComboBox<String> cbUnidvenda;
    private javax.swing.JComboBox<String> cbmodbc;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtAcresc;
    public static javax.swing.JTextField txtCodBarras;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtFator;
    private javax.swing.JTextField txtIditem;
    private javax.swing.JTextField txtNomeproduto;
    private javax.swing.JTextField txtQnt;
    private javax.swing.JTextField txtValortotal;
    private javax.swing.JTextField txtValorunitario;
    private javax.swing.JTextField txtaliqcofins;
    private javax.swing.JTextField txtaliqicms;
    private javax.swing.JTextField txtaliqipi;
    private javax.swing.JTextField txtaliqpis;
    private javax.swing.JTextField txtbaseicms;
    private javax.swing.JTextField txtbaseipi;
    private javax.swing.JTextField txtbasepis;
    private javax.swing.JTextField txtbasest;
    private javax.swing.JTextField txtcbenef;
    private javax.swing.JTextField txtcest;
    private javax.swing.JTextField txtcfop;
    private javax.swing.JTextField txtcst;
    private javax.swing.JTextField txtcstipi;
    private javax.swing.JTextField txtcstpis;
    private javax.swing.JTextField txtdesccst;
    private javax.swing.JTextField txtdescipi;
    private javax.swing.JTextField txtdescpis;
    private javax.swing.JTextField txtdesoneracaoicms;
    private javax.swing.JTextField txtncm;
    private javax.swing.JTextField txtredicms;
    private javax.swing.JTextField txtvlcofins;
    private javax.swing.JTextField txtvlfrete;
    private javax.swing.JTextField txtvlicms;
    private javax.swing.JTextField txtvlipi;
    private javax.swing.JTextField txtvloutras;
    private javax.swing.JTextField txtvlpis;
    private javax.swing.JTextField txtvlseguro;
    private javax.swing.JTextField txtvlst;
    // End of variables declaration//GEN-END:variables
}
