/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relatorios;

import DAO.listaDAO;
import DAO.listaGrupDAO;
import model.clsDadosEmpresa;
import classes.clsaux;
import conexoes.conexao;
import java.awt.HeadlessException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author RKochhann
 */
public class relEstoque extends javax.swing.JDialog {

    /**
     * Creates new form relEstoque
     */
    public relEstoque(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ftInicial = new javax.swing.JFormattedTextField();
        ftFinal = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cbGrupo = new javax.swing.JComboBox<>();
        ckGrupo = new javax.swing.JRadioButton();
        ckPositivo = new javax.swing.JRadioButton();
        ckNegativo = new javax.swing.JRadioButton();
        ckZerado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Apuração De Estoque");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102)));
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        jButton1.setText("Gerar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Inicial :");

        try {
            ftInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftInicial.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        try {
            ftFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftFinal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setText("Final :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ftFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ftFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        ckGrupo.setBackground(new java.awt.Color(255, 255, 255));
        ckGrupo.setText("Grupo:");
        ckGrupo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ckGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckGrupoActionPerformed(evt);
            }
        });

        ckPositivo.setBackground(new java.awt.Color(255, 255, 255));
        ckPositivo.setText("Somente Positivos");
        ckPositivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckPositivoActionPerformed(evt);
            }
        });

        ckNegativo.setBackground(new java.awt.Color(255, 255, 255));
        ckNegativo.setText("Somente Negativos");
        ckNegativo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckNegativoActionPerformed(evt);
            }
        });

        ckZerado.setBackground(new java.awt.Color(255, 255, 255));
        ckZerado.setText("Estoque 0");
        ckZerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckZeradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ckZerado)
                    .addComponent(ckNegativo)
                    .addComponent(ckPositivo)
                    .addComponent(cbGrupo, 0, 160, Short.MAX_VALUE)
                    .addComponent(ckGrupo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(ckGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckPositivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckNegativo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckZerado)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
       
       
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.camposSelecionados();
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown

    }//GEN-LAST:event_jPanel2ComponentShown

    private void ckGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckGrupoActionPerformed
        DefaultComboBoxModel cb= new DefaultComboBoxModel(listaGrupDAO.listagrupo().toArray());
        if(ckGrupo.isSelected()){
            cbGrupo.setModel(cb);
        } else {
            cb.removeAllElements();
            cbGrupo.setModel(cb);
        }
    }//GEN-LAST:event_ckGrupoActionPerformed

    private void ckPositivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckPositivoActionPerformed
      ckNegativo.setSelected(false);
      ckZerado.setSelected(false);
    }//GEN-LAST:event_ckPositivoActionPerformed

    private void ckNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckNegativoActionPerformed
       ckPositivo.setSelected(false);
       ckZerado.setSelected(false);
    }//GEN-LAST:event_ckNegativoActionPerformed

    private void ckZeradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckZeradoActionPerformed
        ckPositivo.setSelected(false);
        ckNegativo.setSelected(false);
    }//GEN-LAST:event_ckZeradoActionPerformed

    public void relEstoque(String sql2, String qtdtotal2) throws JRException, SQLException{
       try {
       JDialog viewer = new JDialog(new javax.swing.JFrame(),"Visualização do Relatório", true);
                viewer.setSize(1024,720);
                viewer.setLocationRelativeTo(null);
                JasperDesign jd;
                jd = JRXmlLoader.load(".\\relatorios\\relestoque.jrxml");
                JasperReport jr= JasperCompileManager.compileReport(jd);
                PreparedStatement ps=conexao.getPreparedStatementResult(qtdtotal2);
                PreparedStatement pst= conexao.getPreparedStatement(sql2);
                ResultSet rs = ps.executeQuery();
                rs.first();  
                String estoque=rs.getString(1);                
                String tcustos=rs.getString(2);
                String tvendas=rs.getString(3);
                String tlucros=rs.getString(4);
                rs=pst.executeQuery();
                JRResultSetDataSource jrds= new JRResultSetDataSource(rs);
                Map parametros = new HashMap();
                parametros.put("RAZAO_SOCIAL", clsDadosEmpresa.getRazao());
                parametros.put("RUA", clsDadosEmpresa.getRua());
                parametros.put("NUMERO", clsDadosEmpresa.getNumero());
                parametros.put("BAIRRO", clsDadosEmpresa.getBairro());
                parametros.put("CEP", "00000-000");
                parametros.put("CIDADE", clsDadosEmpresa.getCidade());
                parametros.put("UF", clsDadosEmpresa.getEstado());
                parametros.put("FONE", clsDadosEmpresa.getFone());
                parametros.put("dtini",ftInicial.getText());
                parametros.put("dtfim",ftFinal.getText());
                parametros.put("estoque",estoque);
                parametros.put("tvenda",tvendas);
                parametros.put("tcusto",tcustos);
                parametros.put("tlucro",tlucros);
                JasperPrint impre= JasperFillManager.fillReport(jr, parametros, jrds);
                JasperViewer jv = new JasperViewer(impre, true);
                viewer.getContentPane().add(jv.getContentPane());
                viewer.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(relCReceber.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch(HeadlessException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
          }        
        
    
    }
    public void validaCondicao(){
        if(ckPositivo.isSelected()){
            ckNegativo.setSelected(false);
            ckZerado.setSelected(false);
        }else if(ckNegativo.isSelected()){
            ckPositivo.setSelected(false);
            ckZerado.setSelected(false);
        } else if(ckZerado.isSelected()){
            ckPositivo.setSelected(false);
            ckNegativo.setSelected(false);
        }
    }
    public void camposSelecionados(){
         try {
        Date dtini, dtfim=null;
        String sql2 = null, qtdtotal2=null;
        dtini=clsaux.retornaData(ftInicial.getText());
        dtfim=clsaux.retornaData(ftFinal.getText());
        String grupo=null;
        if (ckGrupo.isSelected()){
           grupo=clsaux.retornaId(cbGrupo.getSelectedItem().toString());
                if(ckPositivo.isSelected()){
                    sql2="select tp.nomelongo,\n" +
                            "                    tb.baixa_barra as codigobaixa,\n" +
                            "                    te.estoque,\n" +
                            "                    cast ((tr.preco_custo)as numeric (5,2))as Custo,\n" +
                            "                    cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                    cast ((tr.preco_venda)as numeric (5,2))as Venda,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                    from tprodutos tp\n" +
                            "                    join tbarras tb on tp.id=tb.id_produto\n" +
                            "                    join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                    join tprecos tr on tp.id=tr.id\n" +
                            "                    where tp.excluido='N' and tp.id_grupo='"+grupo+"' and te.estoque>0\n" +
                            "                    Group by 1,2,3,4,6";
                    qtdtotal2="  select\n" +
                            "                         sum (te.estoque)as qtde,\n" +
                            "                         cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                         from tprodutos tp\n" +
                            "                         join tbarras tb on tp.id=tb.id_produto\n" +
                            "                         join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                         join tprecos tr on tp.id=tr.id\n" +
                            "                         where tp.excluido='N' and tp.id_grupo='"+grupo+"' and te.estoque>0\n"
                            ;
                } else if(ckNegativo.isSelected()){
                    sql2="select tp.nomelongo,\n" +
                            "                    tb.baixa_barra as codigobaixa,\n" +
                            "                    te.estoque,\n" +
                            "                    cast ((tr.preco_custo)as numeric (5,2))as Custo,\n" +
                            "                    cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                    cast ((tr.preco_venda)as numeric (5,2))as Venda,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                    from tprodutos tp\n" +
                            "                    join tbarras tb on tp.id=tb.id_produto\n" +
                            "                    join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                    join tprecos tr on tp.id=tr.id\n" +
                            "                    where tp.excluido='N' and tp.id_grupo='"+grupo+"' and te.estoque<0\n" +
                            "                    Group by 1,2,3,4,6";
                    qtdtotal2="  select\n" +
                            "                         sum (te.estoque)as qtde,\n" +
                            "                         cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                         from tprodutos tp\n" +
                            "                         join tbarras tb on tp.id=tb.id_produto\n" +
                            "                         join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                         join tprecos tr on tp.id=tr.id\n" +
                            "                         where tp.excluido='N' and tp.id_grupo='"+grupo+"' and te.estoque<0\n"
                            ;
                    
                    
                } else if(ckZerado.isSelected()){
                    sql2="select tp.nomelongo,\n" +
                            "                    tb.baixa_barra as codigobaixa,\n" +
                            "                    te.estoque,\n" +
                            "                    cast ((tr.preco_custo)as numeric (5,2))as Custo,\n" +
                            "                    cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                    cast ((tr.preco_venda)as numeric (5,2))as Venda,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                    from tprodutos tp\n" +
                            "                    join tbarras tb on tp.id=tb.id_produto\n" +
                            "                    join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                    join tprecos tr on tp.id=tr.id\n" +
                            "                    where tp.excluido='N' and tp.id_grupo='"+grupo+"' and te.estoque=0\n" +
                            "                    Group by 1,2,3,4,6";
                    qtdtotal2="  select\n" +
                            "                         sum (te.estoque)as qtde,\n" +
                            "                         cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                         from tprodutos tp\n" +
                            "                         join tbarras tb on tp.id=tb.id_produto\n" +
                            "                         join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                         join tprecos tr on tp.id=tr.id\n" +
                            "                         where tp.excluido='N' and tp.id_grupo='"+grupo+"' and te.estoque=0\n"
                            ;
                } else{
                    sql2="select tp.nomelongo,\n" +
                            "                    tb.baixa_barra as codigobaixa,\n" +
                            "                    te.estoque,\n" +
                            "                    cast ((tr.preco_custo)as numeric (5,2))as Custo,\n" +
                            "                    cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                    cast ((tr.preco_venda)as numeric (5,2))as Venda,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                    from tprodutos tp\n" +
                            "                    join tbarras tb on tp.id=tb.id_produto\n" +
                            "                    join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                    join tprecos tr on tp.id=tr.id\n" +
                            "                    where tp.excluido='N' and tp.id_grupo='"+grupo+"'\n" +
                            "                    Group by 1,2,3,4,6";
                    qtdtotal2="  select\n" +
                            "                         sum (te.estoque)as qtde,\n" +
                            "                         cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                         from tprodutos tp\n" +
                            "                         join tbarras tb on tp.id=tb.id_produto\n" +
                            "                         join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                         join tprecos tr on tp.id=tr.id\n" +
                            "                         where tp.excluido='N' and tp.id_grupo='"+grupo+"' \n"
                            ;
                    
                }
                
            
        } else{
             if(ckPositivo.isSelected()){
                    sql2="select tp.nomelongo,\n" +
                            "                    tb.baixa_barra as codigobaixa,\n" +
                            "                    te.estoque,\n" +
                            "                    cast ((tr.preco_custo)as numeric (5,2))as Custo,\n" +
                            "                    cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                    cast ((tr.preco_venda)as numeric (5,2))as Venda,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                    from tprodutos tp\n" +
                            "                    join tbarras tb on tp.id=tb.id_produto\n" +
                            "                    join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                    join tprecos tr on tp.id=tr.id\n" +
                            "                    where tp.excluido='N'  and te.estoque>0\n" +
                            "                    Group by 1,2,3,4,6";
                    qtdtotal2="  select\n" +
                            "                         sum (te.estoque)as qtde,\n" +
                            "                         cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                         from tprodutos tp\n" +
                            "                         join tbarras tb on tp.id=tb.id_produto\n" +
                            "                         join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                         join tprecos tr on tp.id=tr.id\n" +
                            "                         where tp.excluido='N'  and te.estoque>0\n"
                            ;
                } else if(ckNegativo.isSelected()){
                    sql2="select tp.nomelongo,\n" +
                            "                    tb.baixa_barra as codigobaixa,\n" +
                            "                    te.estoque,\n" +
                            "                    cast ((tr.preco_custo)as numeric (5,2))as Custo,\n" +
                            "                    cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                    cast ((tr.preco_venda)as numeric (5,2))as Venda,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                    from tprodutos tp\n" +
                            "                    join tbarras tb on tp.id=tb.id_produto\n" +
                            "                    join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                    join tprecos tr on tp.id=tr.id\n" +
                            "                    where tp.excluido='N' and te.estoque<0\n" +
                            "                    Group by 1,2,3,4,6";
                    qtdtotal2="  select\n" +
                            "                         sum (te.estoque)as qtde,\n" +
                            "                         cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                         from tprodutos tp\n" +
                            "                         join tbarras tb on tp.id=tb.id_produto\n" +
                            "                         join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                         join tprecos tr on tp.id=tr.id\n" +
                            "                         where tp.excluido='N' and te.estoque<0\n"
                            ;
                    
                    
                } else if(ckZerado.isSelected()){
                    sql2="select tp.nomelongo,\n" +
                            "                    tb.baixa_barra as codigobaixa,\n" +
                            "                    te.estoque,\n" +
                            "                    cast ((tr.preco_custo)as numeric (5,2))as Custo,\n" +
                            "                    cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                    cast ((tr.preco_venda)as numeric (5,2))as Venda,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                    from tprodutos tp\n" +
                            "                    join tbarras tb on tp.id=tb.id_produto\n" +
                            "                    join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                    join tprecos tr on tp.id=tr.id\n" +
                            "                    where tp.excluido='N' and te.estoque=0\n" +
                            "                    Group by 1,2,3,4,6";
                    qtdtotal2="  select\n" +
                            "                         sum (te.estoque)as qtde,\n" +
                            "                         cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                         from tprodutos tp\n" +
                            "                         join tbarras tb on tp.id=tb.id_produto\n" +
                            "                         join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                         join tprecos tr on tp.id=tr.id\n" +
                            "                         where tp.excluido='N' and te.estoque=0\n"
                            ;
                } else{
                    sql2="select tp.nomelongo,\n" +
                            "                    tb.baixa_barra as codigobaixa,\n" +
                            "                    te.estoque,\n" +
                            "                    cast ((tr.preco_custo)as numeric (5,2))as Custo,\n" +
                            "                    cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                    cast ((tr.preco_venda)as numeric (5,2))as Venda,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                    cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                    from tprodutos tp\n" +
                            "                    join tbarras tb on tp.id=tb.id_produto\n" +
                            "                    join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                    join tprecos tr on tp.id=tr.id\n" +
                            "                    where tp.excluido='N' and tp.id_grupo='"+grupo+"'\n" +
                            "                    Group by 1,2,3,4,6";
                    qtdtotal2="  select\n" +
                            "                         sum (te.estoque)as qtde,\n" +
                            "                         cast (sum(tr.preco_custo*te.estoque)as numeric (5,2)) as TCusto,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)as numeric (5,2)) as TVenda ,\n" +
                            "                         cast (sum(tr.preco_venda*te.estoque)-(sum(tr.preco_custo*te.estoque))as numeric (5,2)) as Lucro\n" +
                            "                         from tprodutos tp\n" +
                            "                         join tbarras tb on tp.id=tb.id_produto\n" +
                            "                         join stp_calc_estoque ('"+dtini+"','"+dtfim+"') te on te.codproduto=tb.baixa_barra\n" +
                            "                         join tprecos tr on tp.id=tr.id\n" +
                            "                         where tp.excluido='N'\n"
                            ;
                    
                }
        }
        this.relEstoque(sql2, qtdtotal2);
        } catch (JRException ex) {
                Logger.getLogger(relEstoque.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(relEstoque.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(relEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(relEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(relEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(relEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                relEstoque dialog = new relEstoque(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JRadioButton ckGrupo;
    private javax.swing.JRadioButton ckNegativo;
    private javax.swing.JRadioButton ckPositivo;
    private javax.swing.JRadioButton ckZerado;
    private javax.swing.JFormattedTextField ftFinal;
    private javax.swing.JFormattedTextField ftInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
