/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relatorios;


import model.clsDadosEmpresa;
import classes.clsaux;
import DAO.listaInfAdcDAO;
import DAO.listaGrupDAO;
import DAO.produtoDAO;
import classes.clsRelVendasProdutosPerc;
import conexoes.conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanArrayDataSource;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

public class relVendasporProdutosPercentual extends javax.swing.JDialog {

    /**
     * Creates new form relVendasporProdutos
     */
    public relVendasporProdutosPercentual(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //this.inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbGrupo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ftFinal = new javax.swing.JFormattedTextField();
        ftInicial = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório - Vendas Por Produtos");

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102)));
        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        jButton1.setText("Gerar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 153, 102), new java.awt.Color(0, 153, 102), null));

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        jLabel5.setText("Grupos :");

        cbGrupo.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        cbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0-Todos" }));
        cbGrupo.setEnabled(false);
        cbGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel3.setText("Inicial :");

        try {
            ftFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftFinal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        try {
            ftInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftInicial.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLabel4.setText("Final ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ftFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ftFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.relVendas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
       
    }//GEN-LAST:event_jPanel2ComponentShown

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
       
    }//GEN-LAST:event_jPanel1ComponentShown

    private void cbGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGrupoActionPerformed

   public void inicia(){
       DefaultComboBoxModel df = new DefaultComboBoxModel (listaGrupDAO.listagrupo().toArray());
       cbGrupo.setModel(df);
       cbGrupo.setSelectedIndex(0);
       
        DefaultComboBoxModel pr = new DefaultComboBoxModel (produtoDAO.listaprodutos().toArray());
       //cbProd.setModel(pr);
       //cbProd.setSelectedItem("0 -Geral");
       
}
    
    public void relVendas(){
       Date dtini, dtfim=null;
       String grupo,prod,filtro=null;
       dtini=clsaux.retornaData(ftInicial.getText());
       dtfim=clsaux.retornaData(ftFinal.getText());
       grupo=clsaux.retornaId(cbGrupo.getSelectedItem().toString()).trim();
      // prod=clsaux.retornaId(cbProd.getSelectedItem().toString()).trim();
       try {
       JDialog viewer = new JDialog(new javax.swing.JFrame(),"Visualização do Relatório", true);
                viewer.setSize(1024,720);
                viewer.setLocationRelativeTo(null);
                JasperDesign jd;
                
                String sql = null,qtdtotal=null;
                
                jd = JRXmlLoader.load(".\\relatorios\\relvendasPerc.jrxml");
                JasperReport jr= JasperCompileManager.compileReport(jd);
                 sql="select tb.codigo_barras,\n" +
"                                         tp.nomelongo,\n" +
"                                         cast (sum (ti.quantidade)as numeric(5)) as Quantidade,\n" +
"                                         cast (sum (ti.total)as numeric (5,2))as Total,\n" +
"                                         cast (sum((ti.quantidade)*ti.cust_unitario)as numeric (5,2)) as Custo,\n" +
"                                         cast (sum (ti.total )- sum((ti.quantidade)*ti.cust_unitario)as numeric (5,2)) as Lucro,\n" +
"                                             cast ((sum (ti.total)- sum((ti.quantidade)*ti.cust_unitario))/ sum (ti.total)*100 as numeric(5,2)) as porcentagem\n" +
"                                         from titens ti\n" +
"                                         join tprodutos tp on ti.id_prod=tp.id\n" +
"                                         join tprecos tr on ti.id_prod=tr.id\n" +
"                                         join tmovimento tm on ti.id_mov=tm.id_mov\n" +
"                                         join tbarras tb on tp.id=tb.id_produto\n" +
"                                         where tm.id_tipo='2'and tm.dat_finalizacao between '"+dtini+"' and '"+dtfim+"'\n" +
"                                         and tm.estado='2' and ti.estado='2'\n" +
"                                         or\n" +
"                                         tm.dat_finalizacao between '"+dtini+"' and '"+dtfim+"'\n" +
"                                         and tm.id_tipo='1' and tm.estado='2' and ti.estado='2'\n" +
"                                         or\n" +
"                                         tm.dat_finalizacao between '"+dtini+"' and '"+dtfim+"'\n" +
"                                         and tm.id_tipo='5' and tm.estado='2' and ti.estado='2'\n" +
"                                         GROUP BY 1,2\n" +
"                                         ORDER BY tp.nomelongo";
                 
                //PreparedStatement ps=conexao.getPreparedStatementResult(qtdtotal);
                PreparedStatement pst= conexao.getPreparedStatementResult(sql);
                ResultSet rs = pst.executeQuery();
                List beans= new ArrayList();
                
                while(rs.next()){
                    clsRelVendasProdutosPerc cr=new clsRelVendasProdutosPerc();
                    cr.setCODIGO_BARRAS(rs.getString(1));
                    cr.setNOMELONGO(rs.getString(2));
                    cr.setQUANTIDADE(rs.getString(3));
                    cr.setTOTAL(rs.getString(4));
                    cr.setCUSTO(rs.getString(5));
                    cr.setLUCRO(rs.getString(6));
                    cr.setPORCENTAGEM(rs.getString(7));
                    cr.setCRESC30(this.busca30(rs.getString(1),rs.getDouble(3)));
                    cr.setCRESC60("20");
                    beans.add(cr);
                }
                /*String qtde=rs.getString(1);
                String tvendas=rs.getString(2);
                String tcustos=rs.getString(3);
                String tlucros=rs.getString(4);
                String tporce=rs.getString(5);*/
                
                
                rs=pst.executeQuery();
                JRDataSource jrds= new JRBeanArrayDataSource(beans.toArray());
                Map parametros = new HashMap();
                parametros.put("RAZAO_SOCIAL", clsDadosEmpresa.getRazao());
                parametros.put("RUA", clsDadosEmpresa.getRua());
                parametros.put("NUMERO", clsDadosEmpresa.getNumero());
                parametros.put("BAIRRO", clsDadosEmpresa.getBairro());
                parametros.put("CEP", "00000-000");
                parametros.put("CIDADE", clsDadosEmpresa.getCidade());
                parametros.put("UF", clsDadosEmpresa.getEstado());
                parametros.put("FONE", clsDadosEmpresa.getFone());
                    parametros.put("dtini",ftInicial.getText());
                parametros.put("dtfim",ftFinal.getText());
                parametros.put("qtdevendas","00");
                parametros.put("tvenda","00");
                parametros.put("tcusto","00");
                parametros.put("tlucro","00");
                parametros.put("tporcent", "00");
                JasperPrint impre= JasperFillManager.fillReport(jr, parametros, jrds);
                JasperViewer jv = new JasperViewer(impre, true);
                viewer.getContentPane().add(jv.getContentPane());
                viewer.setVisible(true);
                
            
        } catch (JRException ex) {
            Logger.getLogger(relCReceber.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException exx) {
            Logger.getLogger(relCReceber.class.getName()).log(Level.SEVERE, null, exx);
            JOptionPane.showMessageDialog(null, exx.getMessage());
        } catch(java.lang.Throwable e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
                
       
    
    }
    public String busca30(String cod,Double venda){
        String ret=null;
        try {
            Date dataini30,datafim30=null;
            datafim30=clsaux.retornaData(ftInicial.getText());
            dataini30=clsaux.retornaData(clsaux.calcularData(-30,datafim30));
            System.out.println(dataini30);
            
            String sql="select tb.codigo_barras,\n" +
                    "                                         tp.nomelongo,\n" +
                    "                                         cast (sum (ti.quantidade)as numeric(5)) as Quantidade\n" +
                    "                                         from titens ti\n" +
                    "                                         join tprodutos tp on ti.id_prod=tp.id\n" +
                    "                                         join tprecos tr on ti.id_prod=tr.id\n" +
                    "                                         join tmovimento tm on ti.id_mov=tm.id_mov\n" +
                    "                                         join tbarras tb on tp.id=tb.id_produto\n" +
                    "                                         where ti.codi_barra='"+cod+"' and tm.id_tipo='2'and tm.dat_finalizacao between '"+dataini30+"' and '"+datafim30+"'\n" +
                    "                                         and tm.estado='2' and ti.estado='2'\n" +
                    "                                         or\n" +
                    "                                         tm.dat_finalizacao between '"+dataini30+"' and '"+datafim30+"'\n" +
                    "                                         and ti.codi_barra='"+cod+"' and tm.id_tipo='1' and tm.estado='2' and ti.estado='2'\n" +
                    "                                         or\n" +
                    "                                         tm.dat_finalizacao between '"+dataini30+"' and '"+datafim30+"'\n" +
                    "                                         and ti.codi_barra='"+cod+"' and tm.id_tipo='5' and tm.estado='2' and ti.estado='2'\n" +
                    "                                         GROUP BY 1,2\n" +
                    "                                         ORDER BY tp.nomelongo";
            System.out.println(sql);
            PreparedStatement ps = conexao.getPreparedStatementResult(sql);
            ResultSet rs = ps.executeQuery();
            rs.first();
            Double venda30=rs.getDouble(3);
            Double calculo= venda*100/venda30-100;
            ret=clsaux.formato(calculo);
           
        } catch (SQLException ex) {
            Logger.getLogger(relVendasporProdutosPercentual.class.getName()).log(Level.SEVERE, null, ex);
        }
        
     return ret;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(relVendasporProdutosPercentual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(relVendasporProdutosPercentual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(relVendasporProdutosPercentual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(relVendasporProdutosPercentual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                relVendasporProdutosPercentual dialog = new relVendasporProdutosPercentual(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGrupo;
    private javax.swing.JFormattedTextField ftFinal;
    private javax.swing.JFormattedTextField ftInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
