/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package titulos;

import DAO.ContasReceberDAO;
import DAO.MovimentoContaDAO;
import DAO.lancamentoTiroDAO;
import DAO.listaDAO;
import model.CadContasRecPagar;
import classes.clsaux;
import conexoes.conexao;
import grafic.interfac.CRUDTitulo;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.clsConfig;

/**
 *
 * @author Lucas
 */
public class FormBaixaTitulos extends javax.swing.JDialog {

    /**
     * Creates new form FormBaixaTitulos
     */
    public FormBaixaTitulos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.preencheTipoForm();
        this.carregacomponentes();
        this.somaTitulos();
    }
    String tipoform=null;
    public static String idparceir=null;
    public static List<CadContasRecPagar> lista= new ArrayList<>();
    String vljurosvalida,vlmultavalida,vldescontovalida="";
    String titulosOriginarios="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblValores = new javax.swing.JTable();
        JcbFinalizadora = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lbFalta = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSubtotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMulta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnTotal = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtJuros = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        JcbConta = new javax.swing.JComboBox<>();
        JcbTipo = new javax.swing.JComboBox<>();
        JcbSubTipo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ckTipoCad = new javax.swing.JCheckBox();
        ftDataConsiderar = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        btnBaixar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbRecParc = new javax.swing.JCheckBox();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Baixa de Títulos");
        setBackground(new java.awt.Color(219, 227, 227));

        jPanel1.setBackground(new java.awt.Color(219, 227, 227));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));

        tblValores.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        tblValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Finalizadora", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblValores);
        if (tblValores.getColumnModel().getColumnCount() > 0) {
            tblValores.getColumnModel().getColumn(0).setResizable(false);
            tblValores.getColumnModel().getColumn(0).setPreferredWidth(2);
            tblValores.getColumnModel().getColumn(1).setResizable(false);
            tblValores.getColumnModel().getColumn(1).setPreferredWidth(125);
            tblValores.getColumnModel().getColumn(2).setResizable(false);
            tblValores.getColumnModel().getColumn(2).setPreferredWidth(15);
        }

        JcbFinalizadora.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        JcbFinalizadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbFinalizadoraActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Valor :");

        txtValor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        btnAdicionar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Incluir.png"))); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Falta :");

        lbFalta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbFalta.setForeground(new java.awt.Color(255, 0, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Pagamento :");

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Sub Total:");

        btnSubtotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSubtotal.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Multa:");

        txtMulta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMulta.setText("0,00");
        txtMulta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMultaFocusLost(evt);
            }
        });
        txtMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMultaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Desc:");

        txtDesc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDesc.setText("0,00");
        txtDesc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescFocusLost(evt);
            }
        });
        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Total:");

        btnTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnTotal.setForeground(new java.awt.Color(0, 153, 0));
        btnTotal.setEnabled(false);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Juros:");

        txtJuros.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtJuros.setText("0,00");
        txtJuros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJurosFocusLost(evt);
            }
        });
        txtJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJurosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtJuros, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTotal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubtotal, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMulta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionar)
                            .addComponent(JcbFinalizadora, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(32, 32, 32)
                            .addComponent(lbFalta, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(JcbFinalizadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addComponent(btnAdicionar)
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbFalta, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102), new java.awt.Color(0, 102, 102)));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel11.setText("Títulos Referentes");

        jTable2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Movimento", "Data", "Sub Total", "Juros", "Multa", "Desconto", "Total", "Pago", "Tipo", "Sub Tipo", "Obs", "Vendedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
            jTable2.getColumnModel().getColumn(7).setResizable(false);
            jTable2.getColumnModel().getColumn(8).setResizable(false);
            jTable2.getColumnModel().getColumn(9).setResizable(false);
            jTable2.getColumnModel().getColumn(10).setResizable(false);
            jTable2.getColumnModel().getColumn(11).setPreferredWidth(50);
        }

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setToolTipText("");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JcbConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JcbConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbContaActionPerformed(evt);
            }
        });

        JcbTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JcbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbTipoActionPerformed(evt);
            }
        });

        JcbSubTipo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JcbSubTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcbSubTipoActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Conta:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Tipo Movimentação:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Subtipo Movimentação:");

        ckTipoCad.setBackground(new java.awt.Color(255, 255, 255));
        ckTipoCad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ckTipoCad.setSelected(true);
        ckTipoCad.setText("Utilizar Tipo e SubTipo do Cadastro");
        ckTipoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckTipoCadActionPerformed(evt);
            }
        });

        ftDataConsiderar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pagamento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        try {
            ftDataConsiderar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftDataConsiderar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcbSubTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JcbConta, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ckTipoCad, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ftDataConsiderar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcbConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JcbSubTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ckTipoCad)
                    .addComponent(ftDataConsiderar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        jLabel12.setText("Financeiro");

        btnBaixar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBaixar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Confirma.png"))); // NOI18N
        btnBaixar.setText("Baixar");
        btnBaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaixarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancela.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbRecParc.setBackground(new java.awt.Color(255, 255, 255));
        cbRecParc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbRecParc.setText("Receber Parcial");
        cbRecParc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRecParcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btnBaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(cbRecParc, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRecParc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBaixar)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void JcbFinalizadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbFinalizadoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbFinalizadoraActionPerformed

    private void JcbSubTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbSubTipoActionPerformed
      
    }//GEN-LAST:event_JcbSubTipoActionPerformed

    private void JcbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbTipoActionPerformed
       String idtipo=clsaux.retornaId(JcbTipo.getSelectedItem().toString());
       DefaultComboBoxModel cbsub= new DefaultComboBoxModel(listaDAO.listasubgrup(idtipo).toArray());
       JcbSubTipo.setModel(cbsub);
    }//GEN-LAST:event_JcbTipoActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        String fin= clsaux.retornaId(JcbFinalizadora.getSelectedItem().toString());
        Double informado=Double.parseDouble(txtValor.getText().replaceAll(",", "."));
        if (fin.equals("8")){
            Double valor=lancamentoTiroDAO.retornaCreditoDisponivel(idparceir);
            if (informado>valor){
                    JOptionPane.showMessageDialog(null, "Saldo de Uso de Credito Insuficiente\nValor Disponivel R$ "+clsaux.formato(valor));
            } else{
                this.insereValorTbl();
            }
        } else{
            this.insereValorTbl();
        }
        txtMulta.setEditable(false);
        txtDesc.setEditable(false);
        
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnBaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaixarActionPerformed
        Double ft= Double.parseDouble(lbFalta.getText().replace(",","."));
        if(ft==0.00){
           this.baixartitulo(); 
        } else if (ft>0.00){
            if(cbRecParc.isSelected()){
                this.baixartitulo();
            }else {
                JOptionPane.showMessageDialog(null, "       Ainda falta valor !!!\n Se preferir marque a opção Receber Parcial,\n"
                        + "e gere um novo contas a receber com o restante...");
            }
        }
        
        
        
    }//GEN-LAST:event_btnBaixarActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorActionPerformed

    private void JcbContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcbContaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcbContaActionPerformed

    private void cbRecParcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRecParcActionPerformed
       // JOptionPane.showMessageDialog(null, "marcou");
        this.divideValorTitulos();
    }//GEN-LAST:event_cbRecParcActionPerformed

    private void txtMultaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMultaFocusLost
       
    }//GEN-LAST:event_txtMultaFocusLost

    private void txtDescFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescFocusLost
        String total=String.valueOf(Double.parseDouble(btnTotal.getText().replaceAll(",", "."))-Double.parseDouble(txtDesc.getText().replaceAll(",",".")));
        btnTotal.setText(total);
        lbFalta.setText(total);
    }//GEN-LAST:event_txtDescFocusLost

    private void ckTipoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckTipoCadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckTipoCadActionPerformed

    private void txtJurosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJurosFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJurosFocusLost

    private void txtMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMultaActionPerformed
        calcularEncargos();
        txtJuros.requestFocus();
    }//GEN-LAST:event_txtMultaActionPerformed

    private void txtJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJurosActionPerformed
       calcularEncargos();
       txtValor.requestFocus();
    }//GEN-LAST:event_txtJurosActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
      txtMulta.requestFocus();
    }//GEN-LAST:event_txtDescActionPerformed
    public void carregacomponentes(){
        DefaultComboBoxModel cbcont= new DefaultComboBoxModel (listaDAO.listaconta().toArray());
        DefaultComboBoxModel cbtipo= new DefaultComboBoxModel(listaDAO.listatipo(tipoform).toArray());
        DefaultComboBoxModel cbfin= new DefaultComboBoxModel(listaDAO.listapagamento().toArray());
        DefaultComboBoxModel cbsub= new DefaultComboBoxModel(listaDAO.listasubgrup("1").toArray());
        JcbConta.setModel(cbcont);
        JcbTipo.setModel(cbtipo);
        JcbFinalizadora.setModel(cbfin);
        JcbSubTipo.setModel(cbsub);
        this.carrega();
        this.preencheTipoFinanceiro();
        ftDataConsiderar.setText(clsaux.preencheData());
    }
    public void insereValorTbl(){
        String valordigi= txtValor.getText().replaceAll(",",".");
        String id= JcbFinalizadora.getSelectedItem().toString();
        Double valor=Double.parseDouble(valordigi);
        Double valortotal=Double.parseDouble(lbFalta.getText().replaceAll(",","."));
        if (valor>valortotal){
            JOptionPane.showMessageDialog(null, "O valor digitano nao pode ser maior que o valor faltante!!!");
        }else {
        DefaultTableModel tb = (DefaultTableModel) tblValores.getModel();
        tb.addRow(new Object[]{
            clsaux.retornaId(id),
            clsaux.retornaAposId(id),
            valordigi
        });
        lbFalta.setText(clsaux.formato(valortotal-valor));
        txtValor.setText(null);
        txtValor.requestFocus();
        }
    }
    public void carrega(){
          DefaultTableModel tbdest=(DefaultTableModel)jTable2.getModel();
          Object marcado=false;
          for (CadContasRecPagar novo: lista){
              Object[] objdest = {novo.getIdtitulo(),
                                  novo.getIdmovto(),
                                  novo.getEmisao(),
                                  novo.getValor(),
                                  novo.getJuros(),
                                  novo.getMulta(),
                                  novo.getDesconto(),
                                  novo.getValortotal(),
                                  novo.getValortotal(),
                                  clsaux.retornaId(novo.getTipofinanceiro()),
                                  clsaux.retornaId(novo.getSubtipofinanceiro()),
                                  novo.getObservacao(),
                                  novo.getVendedor()
              };
              tbdest.addRow(objdest);
              titulosOriginarios=titulosOriginarios+"-"+novo.getIdtitulo();
              }
           }
    
    public void baixartitulo(){
        lancamentoTiroDAO ln = new lancamentoTiroDAO();
        MovimentoContaDAO mvDAO =new MovimentoContaDAO();
        ContasReceberDAO crDAO= new ContasReceberDAO();
        String valor,idfinalizadora=null;
        if (cbRecParc.isSelected()){
            int tamamnhorestante=jTable2.getRowCount();
            Double vltitulores=0.00;
            for(int i=0;i<tamamnhorestante;i++){
               vltitulores= clsaux.capturaValores(jTable2.getValueAt(i,7).toString())-clsaux.capturaValores(jTable2.getValueAt(i,8).toString());
               if(vltitulores>0){
                    this.inserirTituloValorRestante(
                            jTable2.getValueAt(i,9).toString(),
                            jTable2.getValueAt(i,10).toString(),
                            vltitulores.toString(),
                            jTable2.getValueAt(i,12).toString());
               }
            }
        }
        String tipo,subtipo=null;
        int conta= Integer.parseInt(clsaux.retornaId(JcbConta.getSelectedItem().toString()));
        tipo= clsaux.retornaId(JcbTipo.getSelectedItem().toString());
        subtipo= clsaux.retornaId(JcbSubTipo.getSelectedItem().toString());
        DefaultTableModel tbvalor = (DefaultTableModel) tblValores.getModel();
        String vend="0";
        int tamanho = tbvalor.getRowCount();
        for (int i=0; i<tamanho;i++){
            idfinalizadora= tbvalor.getValueAt(i, 0).toString();
            valor= tbvalor.getValueAt(i, 2).toString();
            vend=clsaux.trataCampoNulo(jTable2.getValueAt(i, 12));
            if(ckTipoCad.isSelected()==false){
                mvDAO.inserirPorRecebimentoTitulo(conta, tipo, subtipo, valor, idfinalizadora,tipoform,idparceir,"Ent. Ref. Recebimento Titulo",clsaux.capturaValor(txtJuros.getText()),
                        clsaux.capturaValor(txtMulta.getText()),"",ftDataConsiderar.getText(),vend);
            }
            if (idfinalizadora.equals("8")){
                ln.rateioValorBaixarPorUsoCredito(idparceir, Double.parseDouble(valor), "", "");
            }
            }
        tamanho=0;
        DefaultTableModel tbtitu= (DefaultTableModel) jTable2.getModel();
        tamanho= tbtitu.getRowCount();
        for (int i=0; i<tamanho; i++){
            String idmovimentoreceber=null;
            idmovimentoreceber = tbtitu.getValueAt(i, 0).toString();
            tipo=tbtitu.getValueAt(i, 9).toString();
            subtipo=tbtitu.getValueAt(i, 10).toString();
            String vlreceber= tbtitu.getValueAt(i, 8).toString().replaceAll(",", ".");
            String jr=clsaux.capturaValor(tbtitu.getValueAt(i, 4).toString());
            String mt=clsaux.capturaValor(tbtitu.getValueAt(i, 5).toString());
            String obs=clsaux.trataCampoNulo(tbtitu.getValueAt(i, 11));
            vend= clsaux.trataCampoNulo(tbtitu.getValueAt(i, 12));
            crDAO.baixarTitulo(idmovimentoreceber,vlreceber);
            if(ckTipoCad.isSelected()==true&& clsaux.capturaValores(vlreceber)>0){
              mvDAO.inserirPorRecebimentoTitulo(conta, tipo, subtipo, vlreceber, idfinalizadora,tipoform,idparceir,"Ent. Ref. Recebimento Titulo "+idmovimentoreceber,jr,mt,obs,ftDataConsiderar.getText(),vend);
            }
          }
        JOptionPane.showMessageDialog(null, "Baixa efetuada com sucesso :) ");
        CRUDTitulo.btnPesq.requestFocus();
        this.dispose();
    }
    public void inserirTituloValorRestante(String tipo,String sub,String valor,String vend){
        CadContasRecPagar cr = new CadContasRecPagar();
        ContasReceberDAO crDAO= new ContasReceberDAO();
        cr.setParceiro(idparceir);
        cr.setValor(valor);
        cr.setEmisao(clsaux.retornaData(clsaux.preencheData()));
        cr.setTipo_titulo("1");
        cr.setConta("1");
        cr.setHistorico("5");
        if (tipoform=="S"){
            cr.setTipo("1");
            cr.setSaldo(valor);
        }else {
            cr.setTipo("2");
            cr.setSaldo(valor);
        }
        cr.setEstadotitulo("11");
        cr.setJuros("0.00");
        cr.setDesconto("0.00");
        cr.setParcela("1");
        cr.setVendedor(clsaux.trataCampoNulo(vend));
        cr.setTipofinanceiro(tipo);
        cr.setSubtipofinanceiro(sub);
        Calendar cd = Calendar.getInstance();
        SimpleDateFormat ft = new SimpleDateFormat("dd/MM/yyyy");
        cd.add(Calendar.DAY_OF_MONTH, 30);
        cr.setVencimento(clsaux.retornaData(ft.format(cd.getTime())));
        cr.setObservacao("Titulo gerado Sobre Valor Restante dos titulos "+titulosOriginarios);
        cr.setQntParcelas("1");
        crDAO.inserir(cr);
    }
    public void preencheTipoForm(){
        tipoform=CRUDTitulo.tipo;
    }
    public void somaTitulos(){
        int numlinhas= jTable2.getRowCount();
        Double total=0.00,juros=0.00,multa=0.00;
        for (int i=0; i<numlinhas; i++){
            total = total+Double.parseDouble(jTable2.getValueAt(i, 7).toString().replaceAll(",", "."));
            juros= juros+clsaux.capturaValores(jTable2.getValueAt(i, 4).toString());
            multa= multa+clsaux.capturaValores(jTable2.getValueAt(i, 5).toString());
            if(jTable2.getValueAt(i, 9).toString().equals("0")||jTable2.getValueAt(i, 10).toString().equals("0")){
                ckTipoCad.setSelected(false);
                ckTipoCad.setEnabled(false);
            }
        }
        btnSubtotal.setText(clsaux.formato(total));
        btnTotal.setText(clsaux.formato(total));
        lbFalta.setText(clsaux.formato(total));
        txtValor.setText(clsaux.formato(total));
        txtMulta.setText(clsaux.formato(multa));
        txtJuros.setText(clsaux.formato(juros));
        vljurosvalida=txtJuros.getText();
        vlmultavalida=txtMulta.getText();
        vldescontovalida=txtDesc.getText();
        txtValor.requestFocus();
    }
    public void divideValorTitulos(){
        Double valordigitado=0.00;
        int linha=tblValores.getRowCount();
        for (int i=0; i<linha;i++){
            valordigitado=valordigitado+Double.parseDouble(tblValores.getValueAt(i, 2).toString().replaceAll(",", "."));
            }
        linha= jTable2.getRowCount();
        Double perc=valordigitado*100/clsaux.capturaValores(btnTotal.getText());
        DefaultTableModel tbl = (DefaultTableModel) jTable2.getModel();
        for (int l=0; l<linha; l++){
            Double vltitulo=0.00;
            vltitulo=Double.parseDouble(jTable2.getValueAt(l, 7).toString().replaceAll(",", "."));
            vltitulo=vltitulo*perc/100.0;
            vltitulo=clsaux.capturaValores(clsaux.formato(vltitulo));
            if(valordigitado>=vltitulo){
                 jTable2.setValueAt(vltitulo, l, 8);
                 valordigitado=clsaux.capturaValores(clsaux.formato(valordigitado-vltitulo));
                
            }else{
                 jTable2.setValueAt(valordigitado, l, 8);
            }
        }
    }
    public void preencheTipoFinanceiro(){
        try {
            //funcão para pegar o tipo financeiro do primeiro titulo como padrão
            String movtofinanceiro=jTable2.getValueAt(0, 0).toString();
            String conta,tipo,subtipo=null;
            String sql="select tc.id_tipo_financeiro,\n" +
                        "        tm.descricao_movimento,\n" +
                        "        tc.id_subtipo_financeiro,\n" +
                        "        tm1.descricao_movimento,\n" +
                        "        tc.id_conta,\n" +
                        "        th.nome_conta\n" +
                        "  from tcontas_a_receber_pagar tc\n" +
                        "left join ttipo_movimento tm on tc.id_tipo_financeiro=tm.id_tipo\n" +
                        "left join ttipo_movimento tm1 on tc.id_subtipo_financeiro=tm1.id_tipo\n" +
                        "left join tconta th on tc.id_conta=th.id_conta\n" +
                        "where tc.id=?";
            PreparedStatement ps = conexao.getPreparedStatementResult(sql);
            ps.setString(1, movtofinanceiro);
            ResultSet rs = ps.executeQuery();
            rs.first();
            tipo=rs.getString(1)+"- "+rs.getString(2);
            subtipo=rs.getString(3)+"- "+rs.getString(4);
            conta=rs.getString(5)+"- "+rs.getString(6);
            JcbConta.setSelectedItem(conta);
            JcbTipo.setSelectedItem(tipo);
            JcbSubTipo.setSelectedItem(subtipo);
            rs.close();
            ps.close();
        } catch (SQLException ex) {
            Logger.getLogger(FormBaixaTitulos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void calcularEncargos(){
        String total=String.valueOf(Double.parseDouble(btnTotal.getText().replaceAll(",", "."))+Double.parseDouble(txtMulta.getText().replaceAll(",",".")));
        btnTotal.setText(total);
        lbFalta.setText(total);
        if(vlmultavalida.equals(txtMulta.getText())){
        }else{
            // calcula os titulos rateando o novo valor da multa
            recalculaTabela();
        }if(vljurosvalida.equals(txtJuros.getText())){
        }else{
             recalculaTabela();
        }
        somaTitulos();
    }
    public void recalculaTabela(){
        Double juro=clsaux.capturaValores(txtJuros.getText());
        Double multa=clsaux.capturaValores(txtMulta.getText());
        Double vl=0.00;
        int titulos=jTable2.getRowCount();
        juro=juro/titulos;
        multa=multa/titulos;
        for(int i=0; i<titulos; i++){
            vl= clsaux.capturaValores(jTable2.getValueAt(i, 3).toString());
            vl=vl+juro+multa;
            jTable2.setValueAt(juro, i, 4);
            jTable2.setValueAt(multa, i, 5);
            jTable2.setValueAt(vl, i, 7);
            jTable2.setValueAt(vl, i, 8);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBaixaTitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBaixaTitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBaixaTitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBaixaTitulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormBaixaTitulos dialog = new FormBaixaTitulos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JcbConta;
    private javax.swing.JComboBox<String> JcbFinalizadora;
    private javax.swing.JComboBox<String> JcbSubTipo;
    private javax.swing.JComboBox<String> JcbTipo;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBaixar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JTextField btnSubtotal;
    private javax.swing.JTextField btnTotal;
    private javax.swing.JCheckBox cbRecParc;
    private javax.swing.JCheckBox ckTipoCad;
    private javax.swing.JFormattedTextField ftDataConsiderar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    public static javax.swing.JTable jTable2;
    private javax.swing.JLabel lbFalta;
    private javax.swing.JTable tblValores;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtJuros;
    private javax.swing.JTextField txtMulta;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
